using Basalt.BedrockProtocol.Enums;
using Basalt.BedrockProtocol.NBT;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace Basalt.BedrockProtocol.Types;

public sealed class LevelSettings : DataType {
    public ulong Seed;
    public SpawnSettings SpawnSettings = new();
    public GeneratorType GeneratorType;
    public GameType GameType;
    public bool Hardcore;
    public Difficulty GameDifficulty;
    public BlockPos DefaultSpawnBlockPosition = new();
    public bool AchievementsDisabled;
    public EditorWorldType EditorWorldType;
    public bool CreatedInEditor;
    public bool ExportedFromEditor;
    public int DayCycleStopTime;
    public EducationEditionOffer EducationEditionOffer;
    public bool EducationFeaturesEnabled;
    public string EducationProductId = string.Empty;
    public float RainLevel;
    public float LightningLevel;
    public bool ConfirmedPlatformLockedContent;
    public bool MultiplayerGameIntent;
    public bool LanBroadcastIntent;
    public GamePublishSetting XboxLiveBroadcastSetting;
    public GamePublishSetting PlatformBroadcastSetting;
    public bool CommandsEnabled;
    public bool TexturePacksRequired;
    public GameRulesChangedPacketData Rules = new();
    public Experiments Experiments = new();
    public bool BonusChestEnabled;
    public bool StartWithMapEnabled;
    public PlayerPermissionLevel PlayerPermissions;
    public int ServerChunkTickRange;
    public bool LockedBehaviorPack;
    public bool LockedResourcePack;
    public bool FromLockedTemplate;
    public bool UseMsaGamertagsOnly;
    public bool FromWorldTemplate;
    public bool WorldTemplateOptionLocked;
    public bool OnlySpawnV1Villagers;
    public bool PersonaDisabled;
    public bool CustomSkinsDisabled;
    public bool EmoteChatMuted;
    public string BaseGameVersion = string.Empty;
    public int LimitedWorldWidth;
    public int LimitedWorldDepth;
    public bool NetherType;
    public EduSharedUriResource EduSharedUriResource = new();
    public bool? OverrideForceExperimentalGameplay;
    public ChatRestrictionLevel ChatRestrictionLevel;
    public bool DisablePlayerInteractions;
    public int ServerEditorConnectionPolicy;
    public bool AllowAnonymousBlockDropsInEditorWorlds;

    public override void Write(ref BinaryWriter writer) {
        writer.WriteUInt64(Seed, true);
        SpawnSettings.Write(ref writer);
        writer.WriteZigZag((int)GeneratorType);
        writer.WriteZigZag((int)GameType);
        writer.WriteBool(Hardcore);
        writer.WriteZigZag((int)GameDifficulty);
        DefaultSpawnBlockPosition.Write(ref writer);
        writer.WriteBool(AchievementsDisabled);
        writer.WriteZigZag((int)EditorWorldType);
        writer.WriteBool(CreatedInEditor);
        writer.WriteBool(ExportedFromEditor);
        writer.WriteZigZag(DayCycleStopTime);
        writer.WriteVarUInt((uint)EducationEditionOffer);
        writer.WriteBool(EducationFeaturesEnabled);
        writer.WriteVarString(EducationProductId);
        writer.WriteF32(RainLevel, true);
        writer.WriteF32(LightningLevel, true);
        writer.WriteBool(ConfirmedPlatformLockedContent);
        writer.WriteBool(MultiplayerGameIntent);
        writer.WriteBool(LanBroadcastIntent);
        writer.WriteZigZag((int)XboxLiveBroadcastSetting);
        writer.WriteZigZag((int)PlatformBroadcastSetting);
        writer.WriteBool(CommandsEnabled);
        writer.WriteBool(TexturePacksRequired);
        Rules.Write(ref writer);
        Experiments.Write(ref writer);
        writer.WriteBool(BonusChestEnabled);
        writer.WriteBool(StartWithMapEnabled);
        writer.WriteUInt8((byte)PlayerPermissions);
        writer.WriteInt32(ServerChunkTickRange, true);
        writer.WriteBool(LockedBehaviorPack);
        writer.WriteBool(LockedResourcePack);
        writer.WriteBool(FromLockedTemplate);
        writer.WriteBool(UseMsaGamertagsOnly);
        writer.WriteBool(FromWorldTemplate);
        writer.WriteBool(WorldTemplateOptionLocked);
        writer.WriteBool(OnlySpawnV1Villagers);
        writer.WriteBool(PersonaDisabled);
        writer.WriteBool(CustomSkinsDisabled);
        writer.WriteBool(EmoteChatMuted);
        writer.WriteVarString(BaseGameVersion);
        writer.WriteInt32(LimitedWorldWidth, true);
        writer.WriteInt32(LimitedWorldDepth, true);
        writer.WriteBool(NetherType);
        EduSharedUriResource.Write(ref writer);
        writer.WriteBool(OverrideForceExperimentalGameplay is not null);
        if (OverrideForceExperimentalGameplay is bool overrideForceExperimentalGameplay)
            writer.WriteBool(overrideForceExperimentalGameplay);
        writer.WriteUInt8((byte)ChatRestrictionLevel);
        writer.WriteBool(DisablePlayerInteractions);
        writer.WriteZigZag(ServerEditorConnectionPolicy);
        writer.WriteBool(AllowAnonymousBlockDropsInEditorWorlds);
    }

    public override void Read(ref BinaryReader reader) {
        Seed = reader.ReadUInt64(true);
        SpawnSettings.Read(ref reader);
        GeneratorType = (GeneratorType)reader.ReadZigZag();
        GameType = (GameType)reader.ReadZigZag();
        Hardcore = reader.ReadBool();
        GameDifficulty = (Difficulty)reader.ReadZigZag();
        DefaultSpawnBlockPosition.Read(ref reader);
        AchievementsDisabled = reader.ReadBool();
        EditorWorldType = (EditorWorldType)reader.ReadZigZag();
        CreatedInEditor = reader.ReadBool();
        ExportedFromEditor = reader.ReadBool();
        DayCycleStopTime = reader.ReadZigZag();
        EducationEditionOffer = (EducationEditionOffer)reader.ReadVarUInt();
        EducationFeaturesEnabled = reader.ReadBool();
        EducationProductId = reader.ReadVarString();
        RainLevel = reader.ReadF32(true);
        LightningLevel = reader.ReadF32(true);
        ConfirmedPlatformLockedContent = reader.ReadBool();
        MultiplayerGameIntent = reader.ReadBool();
        LanBroadcastIntent = reader.ReadBool();
        XboxLiveBroadcastSetting = (GamePublishSetting)reader.ReadZigZag();
        PlatformBroadcastSetting = (GamePublishSetting)reader.ReadZigZag();
        CommandsEnabled = reader.ReadBool();
        TexturePacksRequired = reader.ReadBool();
        Rules.Read(ref reader);
        Experiments.Read(ref reader);
        BonusChestEnabled = reader.ReadBool();
        StartWithMapEnabled = reader.ReadBool();
        PlayerPermissions = (PlayerPermissionLevel)reader.ReadUInt8();
        ServerChunkTickRange = reader.ReadInt32(true);
        LockedBehaviorPack = reader.ReadBool();
        LockedResourcePack = reader.ReadBool();
        FromLockedTemplate = reader.ReadBool();
        UseMsaGamertagsOnly = reader.ReadBool();
        FromWorldTemplate = reader.ReadBool();
        WorldTemplateOptionLocked = reader.ReadBool();
        OnlySpawnV1Villagers = reader.ReadBool();
        PersonaDisabled = reader.ReadBool();
        CustomSkinsDisabled = reader.ReadBool();
        EmoteChatMuted = reader.ReadBool();
        BaseGameVersion = reader.ReadVarString();
        LimitedWorldWidth = reader.ReadInt32(true);
        LimitedWorldDepth = reader.ReadInt32(true);
        NetherType = reader.ReadBool();
        EduSharedUriResource.Read(ref reader);
        OverrideForceExperimentalGameplay = reader.ReadBool() ? reader.ReadBool() : null;
        ChatRestrictionLevel = (ChatRestrictionLevel)reader.ReadUInt8();
        DisablePlayerInteractions = reader.ReadBool();
        ServerEditorConnectionPolicy = reader.ReadZigZag();
        AllowAnonymousBlockDropsInEditorWorlds = reader.ReadBool();
    }
}
