<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_")).Core</RootNamespace>

    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Protocol\Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Basalt.Binary" Version="0.1.0" />
    <PackageReference Include="Basalt.RakNet" Version="0.1.0" />
    <PackageReference Include="McMaster.NETCore.Plugins" Version="2.0.0" />
    <PackageReference Include="LevelDB.Standard" Version="2.1.6.1" />
    <PackageReference Include="Tracy-CSharp" Version="0.13.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Protocol\Data\**\*.json">
      <Link>Protocol\Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <LogicalName>Protocol.Data.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
