namespace Basalt.BedrockProtocol.Enums;

public enum SoundIdentifier {
    ItemUseOn,
    Hit,
    Step,
    Fly,
    Jump,
    Break,
    Place,
    HeavyStep,
    Gallop,
    Fall,
    Ambient,
    AmbientBaby,
    AmbientInWater,
    Breathe,
    Death,
    DeathInWater,
    DeathToZombie,
    Hurt,
    HurtInWater,
    Mad,
    Boost,
    Bow,
    SquishBig,
    SquishSmall,
    FallBig,
    FallSmall,
    Splash,
    Fizz,
    Flap,
    Swim,
    Drink,
    Eat,
    Takeoff,
    Shake,
    Plop,
    Land,
    Saddle,
    Armor,
    ArmorPlace,
    AddChest,
    Throw,
    Attack,
    AttackNoDamage,
    AttackStrong,
    Warn,
    Shear,
    Milk,
    Thunder,
    Explode,
    Fire,
    Ignite,
    Fuse,
    Stare,
    Spawn,
    Shoot,
    BreakBlock,
    Launch,
    Blast,
    LargeBlast,
    Twinkle,
    Remedy,
    Unfect,
    LevelUp,
    BowHit,
    BulletHit,
    ExtinguishFire,
    ItemFizz,
    ChestOpen,
    ChestClosed,
    ShulkerBoxOpen,
    ShulkerBoxClosed,
    EnderChestOpen,
    EnderChestClosed,
    PowerOn,
    PowerOff,
    Attach,
    Detach,
    Deny,
    Tripod,
    Pop,
    DropSlot,
    Note,
    Thorns,
    PistonIn,
    PistonOut,
    Portal,
    Water,
    LavaPop,
    Lava,
    Burp,
    BucketFillWater,
    BucketFillLava,
    BucketEmptyWater,
    BucketEmptyLava,
    EquipChain,
    EquipDiamond,
    EquipGeneric,
    EquipGold,
    EquipIron,
    EquipLeather,
    EquipElytra,
    Record13,
    RecordCat,
    RecordBlocks,
    RecordChirp,
    RecordFar,
    RecordMall,
    RecordMellohi,
    RecordStal,
    RecordStrad,
    RecordWard,
    Record11,
    RecordWait,
    RecordNull,
    Flop,
    GuardianCurse,
    MobWarning,
    MobWarningBaby,
    Teleport,
    ShulkerOpen,
    ShulkerClose,
    Haggle,
    HaggleYes,
    HaggleNo,
    HaggleIdle,
    ChorusGrow,
    ChorusDeath,
    Glass,
    PotionBrewed,
    CastSpell,
    PrepareAttackSpell,
    PrepareSummon,
    PrepareWololo,
    Fang,
    Charge,
    TakePicture,
    PlaceLeashKnot,
    BreakLeashKnot,
    AmbientGrowl,
    AmbientWhine,
    AmbientPant,
    AmbientPurr,
    AmbientPurreow,
    DeathMinVolume,
    DeathMidVolume,
    ImitateBlaze,
    ImitateCaveSpider,
    ImitateCreeper,
    ImitateElderGuardian,
    ImitateEnderDragon,
    ImitateEnderman,
    ImitateEndermite,
    ImitateEvocationIllager,
    ImitateGhast,
    ImitateHusk,
    ImitateIllusionIllager,
    ImitateMagmaCube,
    ImitatePolarBear,
    ImitateShulker,
    ImitateSilverfish,
    ImitateSkeleton,
    ImitateSlime,
    ImitateSpider,
    ImitateStray,
    ImitateVex,
    ImitateVindicationIllager,
    ImitateWitch,
    ImitateWither,
    ImitateWitherSkeleton,
    ImitateWolf,
    ImitateZombie,
    ImitateZombiePigman,
    ImitateZombieVillager,
    EnderEyePlaced,
    EndPortalCreated,
    AnvilUse,
    BottleDragonBreath,
    PortalTravel,
    TridentHit,
    TridentReturn,
    TridentRiptide1,
    TridentRiptide2,
    TridentRiptide3,
    TridentThrow,
    TridentThunder,
    TridentHitGround,
    Default,
    FletchingTableUse,
    ElemConstructOpen,
    IceBombHit,
    BalloonPop,
    LtReactionIceBomb,
    LtReactionBleach,
    LtReactionElephantToothpaste,
    LtReactionElephantToothpaste2,
    LtReactionGlowStick,
    LtReactionGlowStick2,
    LtReactionLuminol,
    LtReactionSalt,
    LtReactionFertilizer,
    LtReactionFireball,
    LtReactionMagnesiumSalt,
    LtReactionMiscFire,
    LtReactionFire,
    LtReactionMiscExplosion,
    LtReactionMiscMystical,
    LtReactionMiscMystical2,
    LtReactionProduct,
    SparklerUse,
    GlowStickUse,
    SparklerActive,
    ConvertToDrowned,
    BucketFillFish,
    BucketEmptyFish,
    BubbleColumnUpwards,
    BubbleColumnDownwards,
    BubblePop,
    BubbleUpInside,
    BubbleDownInside,
    HurtBaby,
    DeathBaby,
    StepBaby,
    SpawnBaby,
    Born,
    TurtleEggBreak,
    TurtleEggCrack,
    TurtleEggHatched,
    LayEgg,
    TurtleEggAttacked,
    BeaconActivate,
    BeaconAmbient,
    BeaconDeactivate,
    BeaconPower,
    ConduitActivate,
    ConduitAmbient,
    ConduitAttack,
    ConduitDeactivate,
    ConduitShort,
    Swoop,
    BambooSaplingPlace,
    PreSneeze,
    Sneeze,
    AmbientTame,
    Scared,
    ScaffoldingClimb,
    CrossbowLoadingStart,
    CrossbowLoadingMiddle,
    CrossbowLoadingEnd,
    CrossbowShoot,
    CrossbowQuickChargeStart,
    CrossbowQuickChargeMiddle,
    CrossbowQuickChargeEnd,
    AmbientAggressive,
    AmbientWorried,
    CantBreed,
    ShieldBlock,
    LecternBookPlace,
    GrindstoneUse,
    Bell,
    CampfireCrackle,
    Roar,
    Stun,
    SweetBerryBushHurt,
    SweetBerryBushPick,
    CartographyTableUse,
    StonecutterUse,
    ComposterEmpty,
    ComposterFill,
    ComposterFillLayer,
    ComposterReady,
    BarrelOpen,
    BarrelClose,
    RaidHorn,
    LoomUse,
    AmbientInRaid,
    UicartographyTableUse,
    UistonecutterUse,
    UiloomUse,
    SmokerUse,
    BlastFurnaceUse,
    SmithingTableUse,
    Screech,
    Sleep,
    FurnaceUse,
    MooshroomConvert,
    MilkSuspiciously,
    Celebrate,
    JumpPrevent,
    AmbientPollinate,
    BeehiveDrip,
    BeehiveEnter,
    BeehiveExit,
    BeehiveWork,
    BeehiveShear,
    HoneybottleDrink,
    AmbientCave,
    Retreat,
    ConvertToZombified,
    Admire,
    StepLava,
    Tempt,
    Panic,
    Angry,
    AmbientMoodWarpedForest,
    AmbientMoodSoulsandValley,
    AmbientMoodNetherWastes,
    AmbientMoodBasaltDeltas,
    AmbientMoodCrimsonForest,
    RespawnAnchorCharge,
    RespawnAnchorDeplete,
    RespawnAnchorSetSpawn,
    RespawnAnchorAmbient,
    SoulEscapeQuiet,
    SoulEscapeLoud,
    RecordPigstep,
    LinkCompassToLodestone,
    UseSmithingTable,
    EquipNetherite,
    AmbientLoopWarpedForest,
    AmbientLoopSoulsandValley,
    AmbientLoopNetherWastes,
    AmbientLoopBasaltDeltas,
    AmbientLoopCrimsonForest,
    AmbientAdditionWarpedForest,
    AmbientAdditionSoulsandValley,
    AmbientAdditionNetherWastes,
    AmbientAdditionBasaltDeltas,
    AmbientAdditionCrimsonForest,
    SculkSensorPowerOn,
    SculkSensorPowerOff,
    BucketFillPowderSnow,
    BucketEmptyPowderSnow,
    PointedDripstoneCauldronDripWater,
    PointedDripstoneCauldronDripLava,
    PointedDripstoneDripWater,
    PointedDripstoneDripLava,
    CaveVinesPickBerries,
    BigDripleafTiltDown,
    BigDripleafTiltUp,
    CopperWaxOn,
    CopperWaxOff,
    Scrape,
    PlayerHurtDrown,
    PlayerHurtOnFire,
    PlayerHurtFreeze,
    UseSpyglass,
    StopUsingSpyglass,
    AmethystBlockChime,
    AmbientScreamer,
    HurtScreamer,
    DeathScreamer,
    MilkScreamer,
    JumpToBlock,
    PreRam,
    PreRamScreamer,
    RamImpact,
    RamImpactScreamer,
    SquidInkSquirt,
    GlowSquidInkSquirt,
    ConvertToStray,
    CakeAddCandle,
    ExtinguishCandle,
    AmbientCandle,
    BlockClick,
    BlockClickFail,
    SculkCatalystBloom,
    SculkShriekerShriek,
    WardenNearbyClose,
    WardenNearbyCloser,
    WardenNearbyClosest,
    WardenSlightlyAngry,
    RecordOtherside,
    Tongue,
    CrackIronGolem,
    RepairIronGolem,
    Listening,
    Heartbeat,
    HornBreak,
    SculkSpread,
    SculkCharge,
    SculkSensorPlace,
    SculkShriekerPlace,
    GoatCall0,
    GoatCall1,
    GoatCall2,
    GoatCall3,
    GoatCall4,
    GoatCall5,
    GoatCall6,
    GoatCall7,
    ImitateWarden,
    ListeningAngry,
    ItemGiven,
    ItemTaken,
    Disappeared,
    Reappeared,
    DrinkMilk,
    FrogspawnHatched,
    LaySpawn,
    FrogspawnBreak,
    SonicBoom,
    SonicCharge,
    ItemThrown,
    Record5,
    ConvertToFrog,
    RecordPlaying,
    EnchantingTableUse,
    StepSand,
    DashReady,
    BundleDropContents,
    BundleInsert,
    BundleRemoveOne,
    PressurePlateClickOff,
    PressurePlateClickOn,
    ButtonClickOff,
    ButtonClickOn,
    DoorOpen,
    DoorClose,
    TrapdoorOpen,
    TrapdoorClose,
    FenceGateOpen,
    FenceGateClose,
    Insert,
    Pickup,
    InsertEnchanted,
    PickupEnchanted,
    Brush,
    BrushCompleted,
    ShatterDecoratedPot,
    BreakDecoratedPot,
    SnifferEggCrack,
    SnifferEggHatched,
    WaxedSignInteractFail,
    RecordRelic,
    Bump,
    PumpkinCarve,
    ConvertHuskToZombie,
    PigDeath,
    HoglinZombified,
    AmbientUnderwaterEnter,
    AmbientUnderwaterExit,
    BottleFill,
    BottleEmpty,
    CrafterCraft,
    CrafterFail,
    DecoratedPotInsert,
    DecoratedPotInsertFail,
    CrafterDisableSlot,
    TrialSpawnerOpenShutter,
    TrialSpawnerEjectItem,
    TrialSpawnerDetectPlayer,
    TrialSpawnerSpawnMob,
    TrialSpawnerCloseShutter,
    TrialSpawnerAmbient,
    CopperBulbTurnOn,
    CopperBulbTurnOff,
    AmbientInAir,
    BreezeWindChargeBurst,
    ImitateBreeze,
    ArmadilloBrush,
    ArmadilloScuteDrop,
    EquipWolf,
    UnequipWolf,
    Reflect,
    VaultOpenShutter,
    VaultCloseShutter,
    VaultEjectItem,
    VaultInsertItem,
    VaultInsertItemFail,
    VaultAmbient,
    VaultActivate,
    VaultDeactive,
    HurtReduced,
    WindChargeBurst,
    ImitateBogged,
    WolfArmourCrack,
    WolfArmourBreak,
    WolfArmourRepair,
    MaceSmashAir,
    MaceSmashGround,
    TrialSpawnerChargeActivate,
    TrialSpawnerAmbientOminous,
    OminiousItemSpawnerSpawnItem,
    OminousBottleEndUse,
    MaceHeavySmashGround,
    OminousItemSpawnerSpawnItemBegin,
    ApplyEffectBadOmen,
    ApplyEffectRaidOmen,
    ApplyEffectTrialOmen,
    OminousItemSpawnerAboutToSpawnItem,
    RecordCreator,
    RecordCreatorMusicBox,
    RecordPrecipice,
    VaultRejectRewardedPlayer,
    ImitateDrowned,
    ImitateCreaking,
    BundleInsertFailed,
    SpongeAbsorb,
    BlockCreakingHeartTrail,
    CreakingHeartSpawn,
    Activate,
    Deactivate,
    Freeze,
    Unfreeze,
    Open,
    OpenLong,
    Close,
    CloseLong,
    ImitatePhantom,
    ImitateZoglin,
    ImitateGuardian,
    ImitateRavager,
    ImitatePillager,
    PlaceInWater,
    StateChange,
    ImitateHappyGhast,
    UniqueGeneric,
    RecordTears,
    TheEndLightFlash,
    LeadLeash,
    LeadUnleash,
    LeadBreak,
    Unsaddle,
    EquipCopper,
    RecordLavaChicken,
    PlaceItem,
    SingleItemSwap,
    MultiItemSwap,
    ItemEnchantLunge1,
    ItemEnchantLunge2,
    ItemEnchantLunge3,
    AttackCritical,
    ItemSpearAttackHit,
    ItemSpearAttackMiss,
    ItemWoodenSpearAttackHit,
    ItemWoodenSpearAttackMiss,
    ImitateParched,
    ImitateCamelHusk,
    ItemSpearUse,
    ItemWoodenSpearUse,
    SaddleInWater,
    ItemStoneSpearAttackHit,
    ItemIronSpearAttackHit,
    ItemCopperSpearAttackHit,
    ItemGoldenSpearAttackHit,
    ItemDiamondSpearAttackHit,
    ItemNetheriteSpearAttackHit,
    ItemStoneSpearAttackMiss,
    ItemIronSpearAttackMiss,
    ItemCopperSpearAttackMiss,
    ItemGoldenSpearAttackMiss,
    ItemDiamondSpearAttackMiss,
    ItemNetheriteSpearAttackMiss,
    ItemStoneSpearUse,
    ItemIronSpearUse,
    ItemCopperSpearUse,
    ItemGoldenSpearUse,
    ItemDiamondSpearUse,
    ItemNetheriteSpearUse,
    PauseGrowth,
    ResetGrowth,
    PushedByPlayer,
    Bounce,
    SlimeLanding,
    AbsorbBlock,
    EjectBlock,
    GeyserEruptionStart,
    GeyserEruptionActive,
    RecordBounce,
    BucketFillLandAnimal,
    BucketEmptyLandAnimal,
    GeyserContinuousEruptionStart,
    GeyserContinuousEruptionActive,
    Undefined,
}

public static class SoundIdentifierExtensions {
    public static string ToProtocolString(this SoundIdentifier sound) => sound switch {
            SoundIdentifier.ItemUseOn => "item.use.on",
            SoundIdentifier.Hit => "hit",
            SoundIdentifier.Step => "step",
            SoundIdentifier.Fly => "fly",
            SoundIdentifier.Jump => "jump",
            SoundIdentifier.Break => "break",
            SoundIdentifier.Place => "place",
            SoundIdentifier.HeavyStep => "heavy.step",
            SoundIdentifier.Gallop => "gallop",
            SoundIdentifier.Fall => "fall",
            SoundIdentifier.Ambient => "ambient",
            SoundIdentifier.AmbientBaby => "ambient.baby",
            SoundIdentifier.AmbientInWater => "ambient.in.water",
            SoundIdentifier.Breathe => "breathe",
            SoundIdentifier.Death => "death",
            SoundIdentifier.DeathInWater => "death.in.water",
            SoundIdentifier.DeathToZombie => "death.to.zombie",
            SoundIdentifier.Hurt => "hurt",
            SoundIdentifier.HurtInWater => "hurt.in.water",
            SoundIdentifier.Mad => "mad",
            SoundIdentifier.Boost => "boost",
            SoundIdentifier.Bow => "bow",
            SoundIdentifier.SquishBig => "squish.big",
            SoundIdentifier.SquishSmall => "squish.small",
            SoundIdentifier.FallBig => "fall.big",
            SoundIdentifier.FallSmall => "fall.small",
            SoundIdentifier.Splash => "splash",
            SoundIdentifier.Fizz => "fizz",
            SoundIdentifier.Flap => "flap",
            SoundIdentifier.Swim => "swim",
            SoundIdentifier.Drink => "drink",
            SoundIdentifier.Eat => "eat",
            SoundIdentifier.Takeoff => "takeoff",
            SoundIdentifier.Shake => "shake",
            SoundIdentifier.Plop => "plop",
            SoundIdentifier.Land => "land",
            SoundIdentifier.Saddle => "saddle",
            SoundIdentifier.Armor => "armor",
            SoundIdentifier.ArmorPlace => "mob.armor_stand.place",
            SoundIdentifier.AddChest => "add.chest",
            SoundIdentifier.Throw => "throw",
            SoundIdentifier.Attack => "attack",
            SoundIdentifier.AttackNoDamage => "attack.nodamage",
            SoundIdentifier.AttackStrong => "attack.strong",
            SoundIdentifier.Warn => "warn",
            SoundIdentifier.Shear => "shear",
            SoundIdentifier.Milk => "milk",
            SoundIdentifier.Thunder => "thunder",
            SoundIdentifier.Explode => "explode",
            SoundIdentifier.Fire => "fire",
            SoundIdentifier.Ignite => "ignite",
            SoundIdentifier.Fuse => "fuse",
            SoundIdentifier.Stare => "stare",
            SoundIdentifier.Spawn => "spawn",
            SoundIdentifier.Shoot => "shoot",
            SoundIdentifier.BreakBlock => "break.block",
            SoundIdentifier.Launch => "launch",
            SoundIdentifier.Blast => "blast",
            SoundIdentifier.LargeBlast => "large.blast",
            SoundIdentifier.Twinkle => "twinkle",
            SoundIdentifier.Remedy => "remedy",
            SoundIdentifier.Unfect => "unfect",
            SoundIdentifier.LevelUp => "levelup",
            SoundIdentifier.BowHit => "bow.hit",
            SoundIdentifier.BulletHit => "bullet.hit",
            SoundIdentifier.ExtinguishFire => "extinguish.fire",
            SoundIdentifier.ItemFizz => "item.fizz",
            SoundIdentifier.ChestOpen => "chest.open",
            SoundIdentifier.ChestClosed => "chest.closed",
            SoundIdentifier.ShulkerBoxOpen => "shulkerbox.open",
            SoundIdentifier.ShulkerBoxClosed => "shulkerbox.closed",
            SoundIdentifier.EnderChestOpen => "enderchest.open",
            SoundIdentifier.EnderChestClosed => "enderchest.closed",
            SoundIdentifier.PowerOn => "power.on",
            SoundIdentifier.PowerOff => "power.off",
            SoundIdentifier.Attach => "attach",
            SoundIdentifier.Detach => "detach",
            SoundIdentifier.Deny => "deny",
            SoundIdentifier.Tripod => "tripod",
            SoundIdentifier.Pop => "pop",
            SoundIdentifier.DropSlot => "drop.slot",
            SoundIdentifier.Note => "note",
            SoundIdentifier.Thorns => "thorns",
            SoundIdentifier.PistonIn => "piston.in",
            SoundIdentifier.PistonOut => "piston.out",
            SoundIdentifier.Portal => "portal",
            SoundIdentifier.Water => "water",
            SoundIdentifier.LavaPop => "lava.pop",
            SoundIdentifier.Lava => "lava",
            SoundIdentifier.Burp => "burp",
            SoundIdentifier.BucketFillWater => "bucket.fill.water",
            SoundIdentifier.BucketFillLava => "bucket.fill.lava",
            SoundIdentifier.BucketEmptyWater => "bucket.empty.water",
            SoundIdentifier.BucketEmptyLava => "bucket.empty.lava",
            SoundIdentifier.EquipChain => "armor.equip_chain",
            SoundIdentifier.EquipDiamond => "armor.equip_diamond",
            SoundIdentifier.EquipGeneric => "armor.equip_generic",
            SoundIdentifier.EquipGold => "armor.equip_gold",
            SoundIdentifier.EquipIron => "armor.equip_iron",
            SoundIdentifier.EquipLeather => "armor.equip_leather",
            SoundIdentifier.EquipElytra => "armor.equip_elytra",
            SoundIdentifier.Record13 => "record.13",
            SoundIdentifier.RecordCat => "record.cat",
            SoundIdentifier.RecordBlocks => "record.blocks",
            SoundIdentifier.RecordChirp => "record.chirp",
            SoundIdentifier.RecordFar => "record.far",
            SoundIdentifier.RecordMall => "record.mall",
            SoundIdentifier.RecordMellohi => "record.mellohi",
            SoundIdentifier.RecordStal => "record.stal",
            SoundIdentifier.RecordStrad => "record.strad",
            SoundIdentifier.RecordWard => "record.ward",
            SoundIdentifier.Record11 => "record.11",
            SoundIdentifier.RecordWait => "record.wait",
            SoundIdentifier.RecordNull => "record.null",
            SoundIdentifier.Flop => "flop",
            SoundIdentifier.GuardianCurse => "elderguardian.curse",
            SoundIdentifier.MobWarning => "mob.warning",
            SoundIdentifier.MobWarningBaby => "mob.warning.baby",
            SoundIdentifier.Teleport => "teleport",
            SoundIdentifier.ShulkerOpen => "shulker.open",
            SoundIdentifier.ShulkerClose => "shulker.close",
            SoundIdentifier.Haggle => "haggle",
            SoundIdentifier.HaggleYes => "haggle.yes",
            SoundIdentifier.HaggleNo => "haggle.no",
            SoundIdentifier.HaggleIdle => "haggle.idle",
            SoundIdentifier.ChorusGrow => "chorusgrow",
            SoundIdentifier.ChorusDeath => "chorusdeath",
            SoundIdentifier.Glass => "glass",
            SoundIdentifier.PotionBrewed => "potion.brewed",
            SoundIdentifier.CastSpell => "cast.spell",
            SoundIdentifier.PrepareAttackSpell => "prepare.attack",
            SoundIdentifier.PrepareSummon => "prepare.summon",
            SoundIdentifier.PrepareWololo => "prepare.wololo",
            SoundIdentifier.Fang => "fang",
            SoundIdentifier.Charge => "charge",
            SoundIdentifier.TakePicture => "camera.take_picture",
            SoundIdentifier.PlaceLeashKnot => "leashknot.place",
            SoundIdentifier.BreakLeashKnot => "leashknot.break",
            SoundIdentifier.AmbientGrowl => "growl",
            SoundIdentifier.AmbientWhine => "whine",
            SoundIdentifier.AmbientPant => "pant",
            SoundIdentifier.AmbientPurr => "purr",
            SoundIdentifier.AmbientPurreow => "purreow",
            SoundIdentifier.DeathMinVolume => "death.min.volume",
            SoundIdentifier.DeathMidVolume => "death.mid.volume",
            SoundIdentifier.ImitateBlaze => "imitate.blaze",
            SoundIdentifier.ImitateCaveSpider => "imitate.cave_spider",
            SoundIdentifier.ImitateCreeper => "imitate.creeper",
            SoundIdentifier.ImitateElderGuardian => "imitate.elder_guardian",
            SoundIdentifier.ImitateEnderDragon => "imitate.ender_dragon",
            SoundIdentifier.ImitateEnderman => "imitate.enderman",
            SoundIdentifier.ImitateEndermite => "imitate.endermite",
            SoundIdentifier.ImitateEvocationIllager => "imitate.evocation_illager",
            SoundIdentifier.ImitateGhast => "imitate.ghast",
            SoundIdentifier.ImitateHusk => "imitate.husk",
            SoundIdentifier.ImitateIllusionIllager => "imitate.illusion_illager",
            SoundIdentifier.ImitateMagmaCube => "imitate.magma_cube",
            SoundIdentifier.ImitatePolarBear => "imitate.polar_bear",
            SoundIdentifier.ImitateShulker => "imitate.shulker",
            SoundIdentifier.ImitateSilverfish => "imitate.silverfish",
            SoundIdentifier.ImitateSkeleton => "imitate.skeleton",
            SoundIdentifier.ImitateSlime => "imitate.slime",
            SoundIdentifier.ImitateSpider => "imitate.spider",
            SoundIdentifier.ImitateStray => "imitate.stray",
            SoundIdentifier.ImitateVex => "imitate.vex",
            SoundIdentifier.ImitateVindicationIllager => "imitate.vindication_illager",
            SoundIdentifier.ImitateWitch => "imitate.witch",
            SoundIdentifier.ImitateWither => "imitate.wither",
            SoundIdentifier.ImitateWitherSkeleton => "imitate.wither_skeleton",
            SoundIdentifier.ImitateWolf => "imitate.wolf",
            SoundIdentifier.ImitateZombie => "imitate.zombie",
            SoundIdentifier.ImitateZombiePigman => "imitate.zombie_pigman",
            SoundIdentifier.ImitateZombieVillager => "imitate.zombie_villager",
            SoundIdentifier.EnderEyePlaced => "block.end_portal_frame.fill",
            SoundIdentifier.EndPortalCreated => "block.end_portal.spawn",
            SoundIdentifier.AnvilUse => "random.anvil_use",
            SoundIdentifier.BottleDragonBreath => "bottle.dragonbreath",
            SoundIdentifier.PortalTravel => "portal.travel",
            SoundIdentifier.TridentHit => "item.trident.hit",
            SoundIdentifier.TridentReturn => "item.trident.return",
            SoundIdentifier.TridentRiptide1 => "item.trident.riptide_1",
            SoundIdentifier.TridentRiptide2 => "item.trident.riptide_2",
            SoundIdentifier.TridentRiptide3 => "item.trident.riptide_3",
            SoundIdentifier.TridentThrow => "item.trident.throw",
            SoundIdentifier.TridentThunder => "item.trident.thunder",
            SoundIdentifier.TridentHitGround => "item.trident.hit_ground",
            SoundIdentifier.Default => "default",
            SoundIdentifier.FletchingTableUse => "block.fletching_table.use",
            SoundIdentifier.ElemConstructOpen => "elemconstruct.open",
            SoundIdentifier.IceBombHit => "icebomb.hit",
            SoundIdentifier.BalloonPop => "balloonpop",
            SoundIdentifier.LtReactionIceBomb => "lt.reaction.icebomb",
            SoundIdentifier.LtReactionBleach => "lt.reaction.bleach",
            SoundIdentifier.LtReactionElephantToothpaste => "lt.reaction.epaste",
            SoundIdentifier.LtReactionElephantToothpaste2 => "lt.reaction.epaste2",
            SoundIdentifier.LtReactionGlowStick => "lt.reaction.glow_stick",
            SoundIdentifier.LtReactionGlowStick2 => "lt.reaction.glow_stick2",
            SoundIdentifier.LtReactionLuminol => "lt.reaction.luminol",
            SoundIdentifier.LtReactionSalt => "lt.reaction.salt",
            SoundIdentifier.LtReactionFertilizer => "lt.reaction.fertilizer",
            SoundIdentifier.LtReactionFireball => "lt.reaction.fireball",
            SoundIdentifier.LtReactionMagnesiumSalt => "lt.reaction.mgsalt",
            SoundIdentifier.LtReactionMiscFire => "lt.reaction.miscfire",
            SoundIdentifier.LtReactionFire => "lt.reaction.fire",
            SoundIdentifier.LtReactionMiscExplosion => "lt.reaction.miscexplosion",
            SoundIdentifier.LtReactionMiscMystical => "lt.reaction.miscmystical",
            SoundIdentifier.LtReactionMiscMystical2 => "lt.reaction.miscmystical2",
            SoundIdentifier.LtReactionProduct => "lt.reaction.product",
            SoundIdentifier.SparklerUse => "sparkler.use",
            SoundIdentifier.GlowStickUse => "glowstick.use",
            SoundIdentifier.SparklerActive => "sparkler.active",
            SoundIdentifier.ConvertToDrowned => "convert_to_drowned",
            SoundIdentifier.BucketFillFish => "bucket.fill.fish",
            SoundIdentifier.BucketEmptyFish => "bucket.empty.fish",
            SoundIdentifier.BubbleColumnUpwards => "bubble.up",
            SoundIdentifier.BubbleColumnDownwards => "bubble.down",
            SoundIdentifier.BubblePop => "bubble.pop",
            SoundIdentifier.BubbleUpInside => "bubble.upinside",
            SoundIdentifier.BubbleDownInside => "bubble.downinside",
            SoundIdentifier.HurtBaby => "hurt.baby",
            SoundIdentifier.DeathBaby => "death.baby",
            SoundIdentifier.StepBaby => "step.baby",
            SoundIdentifier.SpawnBaby => "spawn.baby",
            SoundIdentifier.Born => "born",
            SoundIdentifier.TurtleEggBreak => "block.turtle_egg.break",
            SoundIdentifier.TurtleEggCrack => "block.turtle_egg.crack",
            SoundIdentifier.TurtleEggHatched => "block.turtle_egg.hatch",
            SoundIdentifier.LayEgg => "lay_egg",
            SoundIdentifier.TurtleEggAttacked => "block.turtle_egg.attack",
            SoundIdentifier.BeaconActivate => "beacon.activate",
            SoundIdentifier.BeaconAmbient => "beacon.ambient",
            SoundIdentifier.BeaconDeactivate => "beacon.deactivate",
            SoundIdentifier.BeaconPower => "beacon.power",
            SoundIdentifier.ConduitActivate => "conduit.activate",
            SoundIdentifier.ConduitAmbient => "conduit.ambient",
            SoundIdentifier.ConduitAttack => "conduit.attack",
            SoundIdentifier.ConduitDeactivate => "conduit.deactivate",
            SoundIdentifier.ConduitShort => "conduit.short",
            SoundIdentifier.Swoop => "swoop",
            SoundIdentifier.BambooSaplingPlace => "block.bamboo_sapling.place",
            SoundIdentifier.PreSneeze => "presneeze",
            SoundIdentifier.Sneeze => "sneeze",
            SoundIdentifier.AmbientTame => "ambient.tame",
            SoundIdentifier.Scared => "scared",
            SoundIdentifier.ScaffoldingClimb => "block.scaffolding.climb",
            SoundIdentifier.CrossbowLoadingStart => "crossbow.loading.start",
            SoundIdentifier.CrossbowLoadingMiddle => "crossbow.loading.middle",
            SoundIdentifier.CrossbowLoadingEnd => "crossbow.loading.end",
            SoundIdentifier.CrossbowShoot => "crossbow.shoot",
            SoundIdentifier.CrossbowQuickChargeStart => "crossbow.quick_charge.start",
            SoundIdentifier.CrossbowQuickChargeMiddle => "crossbow.quick_charge.middle",
            SoundIdentifier.CrossbowQuickChargeEnd => "crossbow.quick_charge.end",
            SoundIdentifier.AmbientAggressive => "ambient.aggressive",
            SoundIdentifier.AmbientWorried => "ambient.worried",
            SoundIdentifier.CantBreed => "cant_breed",
            SoundIdentifier.ShieldBlock => "item.shield.block",
            SoundIdentifier.LecternBookPlace => "item.book.put",
            SoundIdentifier.GrindstoneUse => "block.grindstone.use",
            SoundIdentifier.Bell => "block.bell.hit",
            SoundIdentifier.CampfireCrackle => "block.campfire.crackle",
            SoundIdentifier.Roar => "roar",
            SoundIdentifier.Stun => "stun",
            SoundIdentifier.SweetBerryBushHurt => "block.sweet_berry_bush.hurt",
            SoundIdentifier.SweetBerryBushPick => "block.sweet_berry_bush.pick",
            SoundIdentifier.CartographyTableUse => "block.cartography_table.use",
            SoundIdentifier.StonecutterUse => "block.stonecutter.use",
            SoundIdentifier.ComposterEmpty => "block.composter.empty",
            SoundIdentifier.ComposterFill => "block.composter.fill",
            SoundIdentifier.ComposterFillLayer => "block.composter.fill_success",
            SoundIdentifier.ComposterReady => "block.composter.ready",
            SoundIdentifier.BarrelOpen => "block.barrel.open",
            SoundIdentifier.BarrelClose => "block.barrel.close",
            SoundIdentifier.RaidHorn => "raid.horn",
            SoundIdentifier.LoomUse => "block.loom.use",
            SoundIdentifier.AmbientInRaid => "ambient.in.raid",
            SoundIdentifier.UicartographyTableUse => "ui.cartography_table.take_result",
            SoundIdentifier.UistonecutterUse => "ui.stonecutter.take_result",
            SoundIdentifier.UiloomUse => "ui.loom.take_result",
            SoundIdentifier.SmokerUse => "block.smoker.smoke",
            SoundIdentifier.BlastFurnaceUse => "block.blastfurnace.fire_crackle",
            SoundIdentifier.SmithingTableUse => "block.smithing_table.use",
            SoundIdentifier.Screech => "screech",
            SoundIdentifier.Sleep => "sleep",
            SoundIdentifier.FurnaceUse => "block.furnace.lit",
            SoundIdentifier.MooshroomConvert => "convert_mooshroom",
            SoundIdentifier.MilkSuspiciously => "milk_suspiciously",
            SoundIdentifier.Celebrate => "celebrate",
            SoundIdentifier.JumpPrevent => "jump.prevent",
            SoundIdentifier.AmbientPollinate => "ambient.pollinate",
            SoundIdentifier.BeehiveDrip => "block.beehive.drip",
            SoundIdentifier.BeehiveEnter => "block.beehive.enter",
            SoundIdentifier.BeehiveExit => "block.beehive.exit",
            SoundIdentifier.BeehiveWork => "block.beehive.work",
            SoundIdentifier.BeehiveShear => "block.beehive.shear",
            SoundIdentifier.HoneybottleDrink => "drink.honey",
            SoundIdentifier.AmbientCave => "ambient.cave",
            SoundIdentifier.Retreat => "retreat",
            SoundIdentifier.ConvertToZombified => "converted_to_zombified",
            SoundIdentifier.Admire => "admire",
            SoundIdentifier.StepLava => "step_lava",
            SoundIdentifier.Tempt => "tempt",
            SoundIdentifier.Panic => "panic",
            SoundIdentifier.Angry => "angry",
            SoundIdentifier.AmbientMoodWarpedForest => "ambient.warped_forest.mood",
            SoundIdentifier.AmbientMoodSoulsandValley => "ambient.soulsand_valley.mood",
            SoundIdentifier.AmbientMoodNetherWastes => "ambient.nether_wastes.mood",
            SoundIdentifier.AmbientMoodBasaltDeltas => "ambient.basalt_deltas.mood",
            SoundIdentifier.AmbientMoodCrimsonForest => "ambient.crimson_forest.mood",
            SoundIdentifier.RespawnAnchorCharge => "respawn_anchor.charge",
            SoundIdentifier.RespawnAnchorDeplete => "respawn_anchor.deplete",
            SoundIdentifier.RespawnAnchorSetSpawn => "respawn_anchor.set_spawn",
            SoundIdentifier.RespawnAnchorAmbient => "respawn_anchor.ambient",
            SoundIdentifier.SoulEscapeQuiet => "particle.soul_escape.quiet",
            SoundIdentifier.SoulEscapeLoud => "particle.soul_escape.loud",
            SoundIdentifier.RecordPigstep => "record.pigstep",
            SoundIdentifier.LinkCompassToLodestone => "lodestone_compass.link_compass_to_lodestone",
            SoundIdentifier.UseSmithingTable => "smithing_table.use",
            SoundIdentifier.EquipNetherite => "armor.equip_netherite",
            SoundIdentifier.AmbientLoopWarpedForest => "ambient.warped_forest.loop",
            SoundIdentifier.AmbientLoopSoulsandValley => "ambient.soulsand_valley.loop",
            SoundIdentifier.AmbientLoopNetherWastes => "ambient.nether_wastes.loop",
            SoundIdentifier.AmbientLoopBasaltDeltas => "ambient.basalt_deltas.loop",
            SoundIdentifier.AmbientLoopCrimsonForest => "ambient.crimson_forest.loop",
            SoundIdentifier.AmbientAdditionWarpedForest => "ambient.warped_forest.additions",
            SoundIdentifier.AmbientAdditionSoulsandValley => "ambient.soulsand_valley.additions",
            SoundIdentifier.AmbientAdditionNetherWastes => "ambient.nether_wastes.additions",
            SoundIdentifier.AmbientAdditionBasaltDeltas => "ambient.basalt_deltas.additions",
            SoundIdentifier.AmbientAdditionCrimsonForest => "ambient.crimson_forest.additions",
            SoundIdentifier.SculkSensorPowerOn => "power.on.sculk_sensor",
            SoundIdentifier.SculkSensorPowerOff => "power.off.sculk_sensor",
            SoundIdentifier.BucketFillPowderSnow => "bucket.fill.powder_snow",
            SoundIdentifier.BucketEmptyPowderSnow => "bucket.empty.powder_snow",
            SoundIdentifier.PointedDripstoneCauldronDripWater => "cauldron_drip.water.pointed_dripstone",
            SoundIdentifier.PointedDripstoneCauldronDripLava => "cauldron_drip.lava.pointed_dripstone",
            SoundIdentifier.PointedDripstoneDripWater => "drip.water.pointed_dripstone",
            SoundIdentifier.PointedDripstoneDripLava => "drip.lava.pointed_dripstone",
            SoundIdentifier.CaveVinesPickBerries => "pick_berries.cave_vines",
            SoundIdentifier.BigDripleafTiltDown => "tilt_down.big_dripleaf",
            SoundIdentifier.BigDripleafTiltUp => "tilt_up.big_dripleaf",
            SoundIdentifier.CopperWaxOn => "copper.wax.on",
            SoundIdentifier.CopperWaxOff => "copper.wax.off",
            SoundIdentifier.Scrape => "scrape",
            SoundIdentifier.PlayerHurtDrown => "mob.player.hurt_drown",
            SoundIdentifier.PlayerHurtOnFire => "mob.player.hurt_on_fire",
            SoundIdentifier.PlayerHurtFreeze => "mob.player.hurt_freeze",
            SoundIdentifier.UseSpyglass => "item.spyglass.use",
            SoundIdentifier.StopUsingSpyglass => "item.spyglass.stop_using",
            SoundIdentifier.AmethystBlockChime => "chime.amethyst_block",
            SoundIdentifier.AmbientScreamer => "ambient.screamer",
            SoundIdentifier.HurtScreamer => "hurt.screamer",
            SoundIdentifier.DeathScreamer => "death.screamer",
            SoundIdentifier.MilkScreamer => "milk.screamer",
            SoundIdentifier.JumpToBlock => "jump_to_block",
            SoundIdentifier.PreRam => "pre_ram",
            SoundIdentifier.PreRamScreamer => "pre_ram.screamer",
            SoundIdentifier.RamImpact => "ram_impact",
            SoundIdentifier.RamImpactScreamer => "ram_impact.screamer",
            SoundIdentifier.SquidInkSquirt => "squid.ink_squirt",
            SoundIdentifier.GlowSquidInkSquirt => "glow_squid.ink_squirt",
            SoundIdentifier.ConvertToStray => "convert_to_stray",
            SoundIdentifier.CakeAddCandle => "cake.add_candle",
            SoundIdentifier.ExtinguishCandle => "extinguish.candle",
            SoundIdentifier.AmbientCandle => "ambient.candle",
            SoundIdentifier.BlockClick => "block.click",
            SoundIdentifier.BlockClickFail => "block.click.fail",
            SoundIdentifier.SculkCatalystBloom => "block.sculk_catalyst.bloom",
            SoundIdentifier.SculkShriekerShriek => "block.sculk_shrieker.shriek",
            SoundIdentifier.WardenNearbyClose => "nearby_close",
            SoundIdentifier.WardenNearbyCloser => "nearby_closer",
            SoundIdentifier.WardenNearbyClosest => "nearby_closest",
            SoundIdentifier.WardenSlightlyAngry => "agitated",
            SoundIdentifier.RecordOtherside => "record.otherside",
            SoundIdentifier.Tongue => "tongue",
            SoundIdentifier.CrackIronGolem => "irongolem.crack",
            SoundIdentifier.RepairIronGolem => "irongolem.repair",
            SoundIdentifier.Listening => "listening",
            SoundIdentifier.Heartbeat => "heartbeat",
            SoundIdentifier.HornBreak => "horn_break",
            SoundIdentifier.SculkSpread => "block.sculk.spread",
            SoundIdentifier.SculkCharge => "charge.sculk",
            SoundIdentifier.SculkSensorPlace => "block.sculk_sensor.place",
            SoundIdentifier.SculkShriekerPlace => "block.sculk_shrieker.place",
            SoundIdentifier.GoatCall0 => "horn_call0",
            SoundIdentifier.GoatCall1 => "horn_call1",
            SoundIdentifier.GoatCall2 => "horn_call2",
            SoundIdentifier.GoatCall3 => "horn_call3",
            SoundIdentifier.GoatCall4 => "horn_call4",
            SoundIdentifier.GoatCall5 => "horn_call5",
            SoundIdentifier.GoatCall6 => "horn_call6",
            SoundIdentifier.GoatCall7 => "horn_call7",
            SoundIdentifier.ImitateWarden => "imitate.warden",
            SoundIdentifier.ListeningAngry => "listening_angry",
            SoundIdentifier.ItemGiven => "item_given",
            SoundIdentifier.ItemTaken => "item_taken",
            SoundIdentifier.Disappeared => "disappeared",
            SoundIdentifier.Reappeared => "reappeared",
            SoundIdentifier.DrinkMilk => "drink.milk",
            SoundIdentifier.FrogspawnHatched => "block.frog_spawn.hatch",
            SoundIdentifier.LaySpawn => "lay_spawn",
            SoundIdentifier.FrogspawnBreak => "block.frog_spawn.break",
            SoundIdentifier.SonicBoom => "sonic_boom",
            SoundIdentifier.SonicCharge => "sonic_charge",
            SoundIdentifier.ItemThrown => "item_thrown",
            SoundIdentifier.Record5 => "record.5",
            SoundIdentifier.ConvertToFrog => "convert_to_frog",
            SoundIdentifier.RecordPlaying => "record.playing",
            SoundIdentifier.EnchantingTableUse => "block.enchanting_table.use",
            SoundIdentifier.StepSand => "step_sand",
            SoundIdentifier.DashReady => "dash_ready",
            SoundIdentifier.BundleDropContents => "bundle.drop_contents",
            SoundIdentifier.BundleInsert => "bundle.insert",
            SoundIdentifier.BundleRemoveOne => "bundle.remove_one",
            SoundIdentifier.PressurePlateClickOff => "pressure_plate.click_off",
            SoundIdentifier.PressurePlateClickOn => "pressure_plate.click_on",
            SoundIdentifier.ButtonClickOff => "button.click_off",
            SoundIdentifier.ButtonClickOn => "button.click_on",
            SoundIdentifier.DoorOpen => "door.open",
            SoundIdentifier.DoorClose => "door.close",
            SoundIdentifier.TrapdoorOpen => "trapdoor.open",
            SoundIdentifier.TrapdoorClose => "trapdoor.close",
            SoundIdentifier.FenceGateOpen => "fence_gate.open",
            SoundIdentifier.FenceGateClose => "fence_gate.close",
            SoundIdentifier.Insert => "insert",
            SoundIdentifier.Pickup => "pickup",
            SoundIdentifier.InsertEnchanted => "insert_enchanted",
            SoundIdentifier.PickupEnchanted => "pickup_enchanted",
            SoundIdentifier.Brush => "brush",
            SoundIdentifier.BrushCompleted => "brush_completed",
            SoundIdentifier.ShatterDecoratedPot => "shatter_pot",
            SoundIdentifier.BreakDecoratedPot => "break_pot",
            SoundIdentifier.SnifferEggCrack => "block.sniffer_egg.crack",
            SoundIdentifier.SnifferEggHatched => "block.sniffer_egg.hatch",
            SoundIdentifier.WaxedSignInteractFail => "block.sign.waxed_interact_fail",
            SoundIdentifier.RecordRelic => "record.relic",
            SoundIdentifier.Bump => "note.bass",
            SoundIdentifier.PumpkinCarve => "pumpkin.carve",
            SoundIdentifier.ConvertHuskToZombie => "mob.husk.convert_to_zombie",
            SoundIdentifier.PigDeath => "mob.pig.death",
            SoundIdentifier.HoglinZombified => "mob.hoglin.converted_to_zombified",
            SoundIdentifier.AmbientUnderwaterEnter => "ambient.underwater.enter",
            SoundIdentifier.AmbientUnderwaterExit => "ambient.underwater.exit",
            SoundIdentifier.BottleFill => "bottle.fill",
            SoundIdentifier.BottleEmpty => "bottle.empty",
            SoundIdentifier.CrafterCraft => "crafter.craft",
            SoundIdentifier.CrafterFail => "crafter.fail",
            SoundIdentifier.DecoratedPotInsert => "block.decorated_pot.insert",
            SoundIdentifier.DecoratedPotInsertFail => "block.decorated_pot.insert_fail",
            SoundIdentifier.CrafterDisableSlot => "crafter.disable_slot",
            SoundIdentifier.TrialSpawnerOpenShutter => "trial_spawner.open_shutter",
            SoundIdentifier.TrialSpawnerEjectItem => "trial_spawner.eject_item",
            SoundIdentifier.TrialSpawnerDetectPlayer => "trial_spawner.detect_player",
            SoundIdentifier.TrialSpawnerSpawnMob => "trial_spawner.spawn_mob",
            SoundIdentifier.TrialSpawnerCloseShutter => "trial_spawner.close_shutter",
            SoundIdentifier.TrialSpawnerAmbient => "trial_spawner.ambient",
            SoundIdentifier.CopperBulbTurnOn => "block.copper_bulb.turn_on",
            SoundIdentifier.CopperBulbTurnOff => "block.copper_bulb.turn_off",
            SoundIdentifier.AmbientInAir => "ambient.in.air",
            SoundIdentifier.BreezeWindChargeBurst => "breeze_wind_charge.burst",
            SoundIdentifier.ImitateBreeze => "imitate.breeze",
            SoundIdentifier.ArmadilloBrush => "mob.armadillo.brush",
            SoundIdentifier.ArmadilloScuteDrop => "mob.armadillo.scute_drop",
            SoundIdentifier.EquipWolf => "armor.equip_wolf",
            SoundIdentifier.UnequipWolf => "armor.unequip_wolf",
            SoundIdentifier.Reflect => "reflect",
            SoundIdentifier.VaultOpenShutter => "vault.open_shutter",
            SoundIdentifier.VaultCloseShutter => "vault.close_shutter",
            SoundIdentifier.VaultEjectItem => "vault.eject_item",
            SoundIdentifier.VaultInsertItem => "vault.insert_item",
            SoundIdentifier.VaultInsertItemFail => "vault.insert_item_fail",
            SoundIdentifier.VaultAmbient => "vault.ambient",
            SoundIdentifier.VaultActivate => "vault.activate",
            SoundIdentifier.VaultDeactive => "vault.deactivate",
            SoundIdentifier.HurtReduced => "hurt.reduced",
            SoundIdentifier.WindChargeBurst => "wind_charge.burst",
            SoundIdentifier.ImitateBogged => "imitate.bogged",
            SoundIdentifier.WolfArmourCrack => "armor.crack_wolf",
            SoundIdentifier.WolfArmourBreak => "armor.break_wolf",
            SoundIdentifier.WolfArmourRepair => "armor.repair_wolf",
            SoundIdentifier.MaceSmashAir => "mace.smash_air",
            SoundIdentifier.MaceSmashGround => "mace.smash_ground",
            SoundIdentifier.TrialSpawnerChargeActivate => "trial_spawner.charge_activate",
            SoundIdentifier.TrialSpawnerAmbientOminous => "trial_spawner.ambient_ominous",
            SoundIdentifier.OminiousItemSpawnerSpawnItem => "ominous_item_spawner.spawn_item",
            SoundIdentifier.OminousBottleEndUse => "ominous_bottle.end_use",
            SoundIdentifier.MaceHeavySmashGround => "mace.heavy_smash_ground",
            SoundIdentifier.OminousItemSpawnerSpawnItemBegin => "ominous_item_spawner.spawn_item_begin",
            SoundIdentifier.ApplyEffectBadOmen => "apply_effect.bad_omen",
            SoundIdentifier.ApplyEffectRaidOmen => "apply_effect.raid_omen",
            SoundIdentifier.ApplyEffectTrialOmen => "apply_effect.trial_omen",
            SoundIdentifier.OminousItemSpawnerAboutToSpawnItem => "ominous_item_spawner.about_to_spawn_item",
            SoundIdentifier.RecordCreator => "record.creator",
            SoundIdentifier.RecordCreatorMusicBox => "record.creator_music_box",
            SoundIdentifier.RecordPrecipice => "record.precipice",
            SoundIdentifier.VaultRejectRewardedPlayer => "vault.reject_rewarded_player",
            SoundIdentifier.ImitateDrowned => "imitate.drowned",
            SoundIdentifier.ImitateCreaking => "imitate.creaking",
            SoundIdentifier.BundleInsertFailed => "bundle.insert_fail",
            SoundIdentifier.SpongeAbsorb => "sponge.absorb",
            SoundIdentifier.BlockCreakingHeartTrail => "block.creaking_heart.trail",
            SoundIdentifier.CreakingHeartSpawn => "creaking_heart_spawn",
            SoundIdentifier.Activate => "activate",
            SoundIdentifier.Deactivate => "deactivate",
            SoundIdentifier.Freeze => "freeze",
            SoundIdentifier.Unfreeze => "unfreeze",
            SoundIdentifier.Open => "open",
            SoundIdentifier.OpenLong => "open_long",
            SoundIdentifier.Close => "close",
            SoundIdentifier.CloseLong => "close_long",
            SoundIdentifier.ImitatePhantom => "imitate.phantom",
            SoundIdentifier.ImitateZoglin => "imitate.zoglin",
            SoundIdentifier.ImitateGuardian => "imitate.guardian",
            SoundIdentifier.ImitateRavager => "imitate.ravager",
            SoundIdentifier.ImitatePillager => "imitate.pillager",
            SoundIdentifier.PlaceInWater => "place_in_water",
            SoundIdentifier.StateChange => "state_change",
            SoundIdentifier.ImitateHappyGhast => "imitate.happy_ghast",
            SoundIdentifier.UniqueGeneric => "armor.unequip_generic",
            SoundIdentifier.RecordTears => "record.tears",
            SoundIdentifier.TheEndLightFlash => "ambient.weather.the_end_light_flash",
            SoundIdentifier.LeadLeash => "lead.leash",
            SoundIdentifier.LeadUnleash => "lead.unleash",
            SoundIdentifier.LeadBreak => "lead.break",
            SoundIdentifier.Unsaddle => "unsaddle",
            SoundIdentifier.EquipCopper => "armor.equip_copper",
            SoundIdentifier.RecordLavaChicken => "record.lava_chicken",
            SoundIdentifier.PlaceItem => "place_item",
            SoundIdentifier.SingleItemSwap => "single_swap",
            SoundIdentifier.MultiItemSwap => "multi_swap",
            SoundIdentifier.ItemEnchantLunge1 => "item.enchant.lunge1",
            SoundIdentifier.ItemEnchantLunge2 => "item.enchant.lunge2",
            SoundIdentifier.ItemEnchantLunge3 => "item.enchant.lunge3",
            SoundIdentifier.AttackCritical => "attack.critical",
            SoundIdentifier.ItemSpearAttackHit => "item.spear.attack_hit",
            SoundIdentifier.ItemSpearAttackMiss => "item.spear.attack_miss",
            SoundIdentifier.ItemWoodenSpearAttackHit => "item.wooden_spear.attack_hit",
            SoundIdentifier.ItemWoodenSpearAttackMiss => "item.wooden_spear.attack_miss",
            SoundIdentifier.ImitateParched => "imitate.parched",
            SoundIdentifier.ImitateCamelHusk => "imitate.camel_husk",
            SoundIdentifier.ItemSpearUse => "item.spear.use",
            SoundIdentifier.ItemWoodenSpearUse => "item.wooden_spear.use",
            SoundIdentifier.SaddleInWater => "saddle_in_water",
            SoundIdentifier.ItemStoneSpearAttackHit => "item.stone_spear.attack_hit",
            SoundIdentifier.ItemIronSpearAttackHit => "item.iron_spear.attack_hit",
            SoundIdentifier.ItemCopperSpearAttackHit => "item.copper_spear.attack_hit",
            SoundIdentifier.ItemGoldenSpearAttackHit => "item.golden_spear.attack_hit",
            SoundIdentifier.ItemDiamondSpearAttackHit => "item.diamond_spear.attack_hit",
            SoundIdentifier.ItemNetheriteSpearAttackHit => "item.netherite_spear.attack_hit",
            SoundIdentifier.ItemStoneSpearAttackMiss => "item.stone_spear.attack_miss",
            SoundIdentifier.ItemIronSpearAttackMiss => "item.iron_spear.attack_miss",
            SoundIdentifier.ItemCopperSpearAttackMiss => "item.copper_spear.attack_miss",
            SoundIdentifier.ItemGoldenSpearAttackMiss => "item.golden_spear.attack_miss",
            SoundIdentifier.ItemDiamondSpearAttackMiss => "item.diamond_spear.attack_miss",
            SoundIdentifier.ItemNetheriteSpearAttackMiss => "item.netherite_spear.attack_miss",
            SoundIdentifier.ItemStoneSpearUse => "item.stone_spear.use",
            SoundIdentifier.ItemIronSpearUse => "item.iron_spear.use",
            SoundIdentifier.ItemCopperSpearUse => "item.copper_spear.use",
            SoundIdentifier.ItemGoldenSpearUse => "item.golden_spear.use",
            SoundIdentifier.ItemDiamondSpearUse => "item.diamond_spear.use",
            SoundIdentifier.ItemNetheriteSpearUse => "item.netherite_spear.use",
            SoundIdentifier.PauseGrowth => "pause_growth",
            SoundIdentifier.ResetGrowth => "reset_growth",
            SoundIdentifier.PushedByPlayer => "pushed_by_player",
            SoundIdentifier.Bounce => "bounce",
            SoundIdentifier.SlimeLanding => "slime_landing",
            SoundIdentifier.AbsorbBlock => "absorb_block",
            SoundIdentifier.EjectBlock => "eject_block",
            SoundIdentifier.GeyserEruptionStart => "geyser_eruption_start",
            SoundIdentifier.GeyserEruptionActive => "geyser_eruption_active",
            SoundIdentifier.RecordBounce => "record.bounce",
            SoundIdentifier.BucketFillLandAnimal => "bucket.fill.land_animal",
            SoundIdentifier.BucketEmptyLandAnimal => "bucket.empty.land_animal",
            SoundIdentifier.GeyserContinuousEruptionStart => "geyser_continuous_eruption_start",
            SoundIdentifier.GeyserContinuousEruptionActive => "geyser_continuous_eruption_active",
            SoundIdentifier.Undefined => "undefined",
        _ => throw new ArgumentOutOfRangeException(nameof(sound), sound, null)
    };
}

