using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Types;

public sealed class LevelSettings {
    public ulong Seed;
    public SpawnSettings SpawnSettings = new();
    public GeneratorType GeneratorType;
    public GameType GameType;
    public bool IsHardcore;
    public Difficulty GameDifficulty;
    public BlockPos DefaultSpawnBlockPosition = new();
    public bool AchievementsDisabled;
    public EditorWorldType EditorWorldType;
    public bool IsCreatedInEditor;
    public bool IsExportedFromEditor;
    public int DayCycleStopTime;
    public EducationEditionOffer EducationEditionOffer;
    public bool EducationFeaturesEnabled;
    public string EducationProductID = string.Empty;
    public float RainLevel;
    public float LightningLevel;
    public bool HasConfirmedPlatformLockedContent;
    public bool MultiplayerGameIntent;
    public bool LANBroadcastIntent;
    public GamePublishSetting XboxLiveBroadcastSetting;
    public GamePublishSetting PlatformBroadcastSetting;
    public bool CommandsEnabled;
    public bool TexturePacksRequired;
    public GameRulesChangedPacketData RuleData = new();
    public Experiments Experiments = new();
    public bool HasBonusChestEnabled;
    public bool StartWithMapEnabled;
    public PlayerPermissionLevel PlayerPermissions;
    public int ServerChunkTickRange;
    public bool HasLockedBehaviorPack;
    public bool HasLockedResourcePack;
    public bool IsFromLockedTemplate;
    public bool UseMsaGamertagsOnly;
    public bool IsFromWorldTemplate;
    public bool IsWorldTemplateOptionLocked;
    public bool OnlySpawnV1Villagers;
    public bool PersonaDisabled;
    public bool CustomSkinsDisabled;
    public bool EmoteChatMuted;
    public string BaseGameVersion = string.Empty;
    public int LimitedWorldWidth;
    public int LimitedWorldDepth;
    public bool NetherType;
    public EduSharedUriResource EduSharedUriResource = new();
    public bool? OverrideForceExperimentalGameplay;
    public ChatRestrictionLevel ChatRestrictionLevel;
    public bool DisablePlayerInteractions;
    public ServerEditorConnectionPolicy ServerEditorConnectionPolicy;
    public bool AllowAnonymousBlockDropsInEditorWorlds;

    public void Read(BinaryReader reader) {
        Seed = reader.ReadUInt64(true);
        SpawnSettings.Read(reader);
        GeneratorType = (global::BedrockProtocol.Enums.GeneratorType)reader.ReadZigZag();
        GameType = (global::BedrockProtocol.Enums.GameType)reader.ReadZigZag();
        IsHardcore = reader.ReadBool();
        GameDifficulty = (global::BedrockProtocol.Enums.Difficulty)reader.ReadZigZag();
        DefaultSpawnBlockPosition.Read(reader);
        AchievementsDisabled = reader.ReadBool();
        EditorWorldType = (global::BedrockProtocol.Enums.EditorWorldType)reader.ReadZigZag();
        IsCreatedInEditor = reader.ReadBool();
        IsExportedFromEditor = reader.ReadBool();
        DayCycleStopTime = reader.ReadZigZag();
        EducationEditionOffer = (global::BedrockProtocol.Enums.EducationEditionOffer)reader.ReadVarUInt();
        EducationFeaturesEnabled = reader.ReadBool();
        EducationProductID = reader.ReadVarString();
        RainLevel = reader.ReadF32(true);
        LightningLevel = reader.ReadF32(true);
        HasConfirmedPlatformLockedContent = reader.ReadBool();
        MultiplayerGameIntent = reader.ReadBool();
        LANBroadcastIntent = reader.ReadBool();
        XboxLiveBroadcastSetting = (global::BedrockProtocol.Enums.GamePublishSetting)reader.ReadZigZag();
        PlatformBroadcastSetting = (global::BedrockProtocol.Enums.GamePublishSetting)reader.ReadZigZag();
        CommandsEnabled = reader.ReadBool();
        TexturePacksRequired = reader.ReadBool();
        RuleData.Read(reader);
        Experiments.Read(reader);
        HasBonusChestEnabled = reader.ReadBool();
        StartWithMapEnabled = reader.ReadBool();
        PlayerPermissions = (global::BedrockProtocol.Enums.PlayerPermissionLevel)reader.ReadInt8();
        ServerChunkTickRange = reader.ReadInt32(true);
        HasLockedBehaviorPack = reader.ReadBool();
        HasLockedResourcePack = reader.ReadBool();
        IsFromLockedTemplate = reader.ReadBool();
        UseMsaGamertagsOnly = reader.ReadBool();
        IsFromWorldTemplate = reader.ReadBool();
        IsWorldTemplateOptionLocked = reader.ReadBool();
        OnlySpawnV1Villagers = reader.ReadBool();
        PersonaDisabled = reader.ReadBool();
        CustomSkinsDisabled = reader.ReadBool();
        EmoteChatMuted = reader.ReadBool();
        BaseGameVersion = reader.ReadVarString();
        LimitedWorldWidth = reader.ReadInt32(true);
        LimitedWorldDepth = reader.ReadInt32(true);
        NetherType = reader.ReadBool();
        EduSharedUriResource.Read(reader);
        if (reader.ReadBool()) {
            OverrideForceExperimentalGameplay = reader.ReadBool();
        } else {
            OverrideForceExperimentalGameplay = default;
        }
        ChatRestrictionLevel = (global::BedrockProtocol.Enums.ChatRestrictionLevel)reader.ReadUInt8();
        DisablePlayerInteractions = reader.ReadBool();
        ServerEditorConnectionPolicy = (global::BedrockProtocol.Enums.ServerEditorConnectionPolicy)reader.ReadZigZag();
        AllowAnonymousBlockDropsInEditorWorlds = reader.ReadBool();
    }

    public void Write(BinaryWriter writer) {
        writer.WriteUInt64(Seed, true);
        SpawnSettings.Write(writer);
        writer.WriteZigZag((int)GeneratorType);
        writer.WriteZigZag((int)GameType);
        writer.WriteBool(IsHardcore);
        writer.WriteZigZag((int)GameDifficulty);
        DefaultSpawnBlockPosition.Write(writer);
        writer.WriteBool(AchievementsDisabled);
        writer.WriteZigZag((int)EditorWorldType);
        writer.WriteBool(IsCreatedInEditor);
        writer.WriteBool(IsExportedFromEditor);
        writer.WriteZigZag(DayCycleStopTime);
        writer.WriteVarUInt((uint)EducationEditionOffer);
        writer.WriteBool(EducationFeaturesEnabled);
        writer.WriteVarString(EducationProductID);
        writer.WriteF32(RainLevel, true);
        writer.WriteF32(LightningLevel, true);
        writer.WriteBool(HasConfirmedPlatformLockedContent);
        writer.WriteBool(MultiplayerGameIntent);
        writer.WriteBool(LANBroadcastIntent);
        writer.WriteZigZag((int)XboxLiveBroadcastSetting);
        writer.WriteZigZag((int)PlatformBroadcastSetting);
        writer.WriteBool(CommandsEnabled);
        writer.WriteBool(TexturePacksRequired);
        RuleData.Write(writer);
        Experiments.Write(writer);
        writer.WriteBool(HasBonusChestEnabled);
        writer.WriteBool(StartWithMapEnabled);
        writer.WriteInt8((sbyte)PlayerPermissions);
        writer.WriteInt32(ServerChunkTickRange, true);
        writer.WriteBool(HasLockedBehaviorPack);
        writer.WriteBool(HasLockedResourcePack);
        writer.WriteBool(IsFromLockedTemplate);
        writer.WriteBool(UseMsaGamertagsOnly);
        writer.WriteBool(IsFromWorldTemplate);
        writer.WriteBool(IsWorldTemplateOptionLocked);
        writer.WriteBool(OnlySpawnV1Villagers);
        writer.WriteBool(PersonaDisabled);
        writer.WriteBool(CustomSkinsDisabled);
        writer.WriteBool(EmoteChatMuted);
        writer.WriteVarString(BaseGameVersion);
        writer.WriteInt32(LimitedWorldWidth, true);
        writer.WriteInt32(LimitedWorldDepth, true);
        writer.WriteBool(NetherType);
        EduSharedUriResource.Write(writer);
        writer.WriteBool(OverrideForceExperimentalGameplay is not null);
        if (OverrideForceExperimentalGameplay is { } optionalValue91) {
            writer.WriteBool(optionalValue91);
        }
        writer.WriteUInt8((byte)ChatRestrictionLevel);
        writer.WriteBool(DisablePlayerInteractions);
        writer.WriteZigZag((int)ServerEditorConnectionPolicy);
        writer.WriteBool(AllowAnonymousBlockDropsInEditorWorlds);
    }
}
