// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// All kinds of actor state changes (see Actor::handleEntityEvent).
/// </summary>
public sealed class ActorEventPacket : Packet {
    public const int PacketId = 27;

    public ActorRuntimeID TargetRuntimeID = new();
    public ActorEvent EventID;
    public int Data;
    public Vec3? FireAtPosition;

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        EventID = (global::BedrockProtocol.Enums.ActorEvent)reader.ReadUInt8();
        Data = reader.ReadZigZag();
        if (reader.ReadBool()) {
            Vec3 readValue6 = new();
            readValue6.Read(reader);
            FireAtPosition = readValue6;
        } else {
            FireAtPosition = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        writer.WriteUInt8((byte)EventID);
        writer.WriteZigZag(Data);
        writer.WriteBool(FireAtPosition is not null);
        if (FireAtPosition is { } optionalValue7) {
            optionalValue7.Write(writer);
        }
    }
}
