// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Player clicks on an actor in the world, eg a chicken.
/// </summary>
public sealed class ActorPickRequestPacket : Packet {
    public const int PacketId = 35;

    public long ActorID;
    public byte MaxSlots;
    public bool WithData;

    public override void Deserialize(BinaryReader reader) {
        ActorID = reader.ReadInt64(true);
        MaxSlots = reader.ReadUInt8();
        WithData = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt64(ActorID, true);
        writer.WriteUInt8(MaxSlots);
        writer.WriteBool(WithData);
    }
}
