// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BedrockProtocol.Nbt;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Add Actor
/// </summary>
public sealed class AddActorPacket : Packet {
    public const int PacketId = 13;

    private static readonly TagOptions NetworkNbtOptions = new(Name: true, Type: true, VarInt: true);

    public ActorUniqueID TargetActorID = new();
    public ActorRuntimeID TargetRuntimeID = new();
    public string ActorType = string.Empty;
    public Vec3 Position = new();
    public Vec3 Velocity = new();
    public Vec2 Rotation = new();
    public float YHeadRotation;
    public float YBodyRotation;
    public List<SyncedAttribute> AttributesList = [];
    public SynchedActorDataList ActorData = new();
    public PropertySyncData SynchedProperties = new();
    public List<ActorLink> ActorLinks = [];

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
        TargetRuntimeID.Read(reader);
        ActorType = reader.ReadVarString();
        Position.Read(reader);
        Velocity.Read(reader);
        Rotation.Read(reader);
        YHeadRotation = reader.ReadF32(true);
        YBodyRotation = reader.ReadF32(true);
        int count16 = checked((int)reader.ReadVarUInt());
        AttributesList = new List<SyncedAttribute>(count16);
        for (int i16 = 0; i16 < count16; i16++) {
            SyncedAttribute item16 = default!;
            SyncedAttribute readValue1016 = new();
            readValue1016.Read(reader);
            item16 = readValue1016;
            AttributesList.Add(item16);
        }
        ActorData.Read(reader);
        SynchedProperties.Read(reader);
        int count22 = checked((int)reader.ReadVarUInt());
        ActorLinks = new List<ActorLink>(count22);
        for (int i22 = 0; i22 < count22; i22++) {
            ActorLink item22 = default!;
            ActorLink readValue1022 = new();
            readValue1022.Read(reader);
            item22 = readValue1022;
            ActorLinks.Add(item22);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
        TargetRuntimeID.Write(writer);
        writer.WriteVarString(ActorType);
        Position.Write(writer);
        Velocity.Write(writer);
        Rotation.Write(writer);
        writer.WriteF32(YHeadRotation, true);
        writer.WriteF32(YBodyRotation, true);
        writer.WriteVarUInt(checked((uint)AttributesList.Count));
        foreach (var item17 in AttributesList) {
            item17.Write(writer);
        }
        ActorData.Write(writer);
        SynchedProperties.Write(writer);
        writer.WriteVarUInt(checked((uint)ActorLinks.Count));
        foreach (var item23 in ActorLinks) {
            item23.Write(writer);
        }
    }
}
