// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Add Behavior Tree
/// </summary>
public sealed class AddBehaviorTreePacket : Packet {
    public const int PacketId = 89;

    public string BehaviorTreeStructureJSON = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        BehaviorTreeStructureJSON = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(BehaviorTreeStructureJSON);
    }
}
