// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BedrockProtocol.Nbt;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// When an item actor is added to the world (punch a tree-&gt;tree block, for example)
/// </summary>
public sealed class AddItemActorPacket : Packet {
    public const int PacketId = 15;

    private static readonly TagOptions NetworkNbtOptions = new(Name: true, Type: true, VarInt: true);

    public ActorUniqueID TargetActorID = new();
    public ActorRuntimeID TargetRuntimeID = new();
    public NetworkItemStackDescriptor Item = new();
    public Vec3 Position = new();
    public Vec3 Velocity = new();
    public SynchedActorDataList EntityData = new();
    public bool IsFromFishing;

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
        TargetRuntimeID.Read(reader);
        Item.Read(reader);
        Position.Read(reader);
        Velocity.Read(reader);
        EntityData.Read(reader);
        IsFromFishing = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
        TargetRuntimeID.Write(writer);
        Item.Write(writer);
        Position.Write(writer);
        Velocity.Write(writer);
        EntityData.Write(writer);
        writer.WriteBool(IsFromFishing);
    }
}
