// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends the information for a new painting actor from server to client.
/// </summary>
public sealed class AddPaintingPacket : Packet {
    public const int PacketId = 22;

    public ActorUniqueID TargetActorID = new();
    public ActorRuntimeID TargetRuntimeID = new();
    public Vec3 Position = new();
    public int Direction;
    public string Motif = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
        TargetRuntimeID.Read(reader);
        Position.Read(reader);
        Direction = reader.ReadZigZag();
        Motif = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
        TargetRuntimeID.Write(writer);
        Position.Write(writer);
        writer.WriteZigZag(Direction);
        writer.WriteVarString(Motif);
    }
}
