// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BedrockProtocol.Nbt;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Add Player
/// </summary>
public sealed class AddPlayerPacket : Packet {
    public const int PacketId = 12;

    private static readonly TagOptions NetworkNbtOptions = new(Name: true, Type: true, VarInt: true);

    public UUID UUID = new();
    public string PlayerName = string.Empty;
    public ActorRuntimeID TargetRuntimeID = new();
    public string PlatformChatId = string.Empty;
    public Vec3 Position = new();
    public Vec3 Velocity = new();
    public Vec2 Rotation = new();
    public float YHeadRotation;
    public NetworkItemStackDescriptor CarriedItem = new();
    public GameType PlayerGameType;
    public SynchedActorDataList EntityData = new();
    public PropertySyncData SynchedProperties = new();
    public SerializedAbilitiesData AbilitiesData = new();
    public List<ActorLink> ActorLinks = [];
    public string DeviceId = string.Empty;
    public BuildPlatform BuildPlatform;

    public override void Deserialize(BinaryReader reader) {
        UUID.Read(reader);
        PlayerName = reader.ReadVarString();
        TargetRuntimeID.Read(reader);
        PlatformChatId = reader.ReadVarString();
        Position.Read(reader);
        Velocity.Read(reader);
        Rotation.Read(reader);
        YHeadRotation = reader.ReadF32(true);
        CarriedItem.Read(reader);
        PlayerGameType = (global::BedrockProtocol.Enums.GameType)reader.ReadZigZag();
        EntityData.Read(reader);
        SynchedProperties.Read(reader);
        AbilitiesData.Read(reader);
        int count26 = checked((int)reader.ReadVarUInt());
        ActorLinks = new List<ActorLink>(count26);
        for (int i26 = 0; i26 < count26; i26++) {
            ActorLink item26 = default!;
            ActorLink readValue1026 = new();
            readValue1026.Read(reader);
            item26 = readValue1026;
            ActorLinks.Add(item26);
        }
        DeviceId = reader.ReadVarString();
        BuildPlatform = (global::BedrockProtocol.Enums.BuildPlatform)reader.ReadInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        UUID.Write(writer);
        writer.WriteVarString(PlayerName);
        TargetRuntimeID.Write(writer);
        writer.WriteVarString(PlatformChatId);
        Position.Write(writer);
        Velocity.Write(writer);
        Rotation.Write(writer);
        writer.WriteF32(YHeadRotation, true);
        CarriedItem.Write(writer);
        writer.WriteZigZag((int)PlayerGameType);
        EntityData.Write(writer);
        SynchedProperties.Write(writer);
        AbilitiesData.Write(writer);
        writer.WriteVarUInt(checked((uint)ActorLinks.Count));
        foreach (var item27 in ActorLinks) {
            item27.Write(writer);
        }
        writer.WriteVarString(DeviceId);
        writer.WriteInt32((int)BuildPlatform, true);
    }
}
