// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends a volume entity's definition and components from server to client.
/// </summary>
public sealed class AddVolumeEntityPacket : Packet {
    public const int PacketId = 166;

    public EntityNetId EntityNetworkId = new();
    public object Components = null!;
    public string JSONIdentifier = string.Empty;
    public string InstanceName = string.Empty;
    public BlockPos MinBounds = new();
    public BlockPos MaxBounds = new();
    public DimensionType DimensionType = new();
    public string EngineVersion = string.Empty;

    public delegate object ComponentsReader(BinaryReader reader);
    public delegate void ComponentsWriter(BinaryWriter writer, object value);
    public ComponentsReader? ReadComponents { get; set; }
    public ComponentsWriter? WriteComponents { get; set; }

    public override void Deserialize(BinaryReader reader) {
        EntityNetworkId.Read(reader);
        Components = (ReadComponents ?? throw new InvalidOperationException("AddVolumeEntityPacket.ReadComponents must be configured before deserialization."))(reader);
        JSONIdentifier = reader.ReadVarString();
        InstanceName = reader.ReadVarString();
        MinBounds.Read(reader);
        MaxBounds.Read(reader);
        DimensionType.Read(reader);
        EngineVersion = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        EntityNetworkId.Write(writer);
        (WriteComponents ?? throw new InvalidOperationException("AddVolumeEntityPacket.WriteComponents must be configured before serialization."))(writer, Components);
        writer.WriteVarString(JSONIdentifier);
        writer.WriteVarString(InstanceName);
        MinBounds.Write(writer);
        MaxBounds.Write(writer);
        DimensionType.Write(writer);
        writer.WriteVarString(EngineVersion);
    }
}
