// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// packet containing data of Agent Action Type
/// </summary>
public sealed class AgentActionEventPacket : Packet {
    public const int PacketId = 181;

    public string RequestId = string.Empty;
    public AgentActionType Action;
    public byte[] Response = [];

    public override void Deserialize(BinaryReader reader) {
        RequestId = reader.ReadVarString();
        Action = (global::BedrockProtocol.Enums.AgentActionType)reader.ReadInt32(true);
        int binaryLength4 = checked((int)reader.ReadVarUInt());
        Response = reader.ReadBytes(binaryLength4).ToArray();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(RequestId);
        writer.WriteInt32((int)Action, true);
        writer.WriteVarUInt(checked((uint)Response.Length));
        writer.WriteBytes(Response);
    }
}
