// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Broadcasted to other players when an Agent performs an animation so it gets properly replicated.
/// </summary>
public sealed class AgentAnimationPacket : Packet {
    public const int PacketId = 304;

    public AgentAnimation AgentAnimation;
    public ActorRuntimeID RuntimeId = new();

    public override void Deserialize(BinaryReader reader) {
        AgentAnimation = (global::BedrockProtocol.Enums.AgentAnimation)reader.ReadUInt8();
        RuntimeId.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)AgentAnimation);
        RuntimeId.Write(writer);
    }
}
