// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Animate Actor
/// </summary>
public sealed class AnimatePacket : Packet {
    public const int PacketId = 44;

    public AnimatePacketPayloadAction Action;
    public ActorRuntimeID TargetActorRuntimeID = new();
    public float Data;
    public global::BedrockProtocol.Enums.ActorSwingSource? SwingSource;

    public override void Deserialize(BinaryReader reader) {
        Action = (global::BedrockProtocol.Enums.AnimatePacketPayloadAction)reader.ReadUInt8();
        TargetActorRuntimeID.Read(reader);
        Data = reader.ReadF32(true);
        if (reader.ReadBool()) {
            string enumText6 = reader.ReadVarString();
            SwingSource = enumText6 switch {
                "none" => global::BedrockProtocol.Enums.ActorSwingSource.None,
                "build" => global::BedrockProtocol.Enums.ActorSwingSource.Build,
                "mine" => global::BedrockProtocol.Enums.ActorSwingSource.Mine,
                "interact" => global::BedrockProtocol.Enums.ActorSwingSource.Interact,
                "attack" => global::BedrockProtocol.Enums.ActorSwingSource.Attack,
                "useitem" => global::BedrockProtocol.Enums.ActorSwingSource.UseItem,
                "throwitem" => global::BedrockProtocol.Enums.ActorSwingSource.ThrowItem,
                "dropitem" => global::BedrockProtocol.Enums.ActorSwingSource.DropItem,
                "event" => global::BedrockProtocol.Enums.ActorSwingSource.Event,
                _ => throw new InvalidOperationException($"Unknown ActorSwingSource wire value: {enumText6}"),
            };
        } else {
            SwingSource = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Action);
        TargetActorRuntimeID.Write(writer);
        writer.WriteF32(Data, true);
        writer.WriteBool(SwingSource is not null);
        if (SwingSource is { } optionalValue7) {
            writer.WriteVarString(optionalValue7 switch {
                global::BedrockProtocol.Enums.ActorSwingSource.None => "none",
                global::BedrockProtocol.Enums.ActorSwingSource.Build => "build",
                global::BedrockProtocol.Enums.ActorSwingSource.Mine => "mine",
                global::BedrockProtocol.Enums.ActorSwingSource.Interact => "interact",
                global::BedrockProtocol.Enums.ActorSwingSource.Attack => "attack",
                global::BedrockProtocol.Enums.ActorSwingSource.UseItem => "useitem",
                global::BedrockProtocol.Enums.ActorSwingSource.ThrowItem => "throwitem",
                global::BedrockProtocol.Enums.ActorSwingSource.DropItem => "dropitem",
                global::BedrockProtocol.Enums.ActorSwingSource.Event => "event",
                _ => throw new InvalidOperationException($"Unknown ActorSwingSource value: {optionalValue7}"),
            });
        }
    }
}
