// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The AnimateEntityPacket is used to trigger a one - off animation on the client it is sent to.
/// </summary>
public sealed class AnimateEntityPacket : Packet {
    public const int PacketId = 158;

    public string MAnimation = string.Empty;
    public string MNextState = string.Empty;
    public string MStopExpression = string.Empty;
    public int MStopExpressionVersion;
    public string MController = string.Empty;
    public float MBlendOutTime;
    public List<ActorRuntimeID> MRuntimeIds = [];

    public override void Deserialize(BinaryReader reader) {
        MAnimation = reader.ReadVarString();
        MNextState = reader.ReadVarString();
        MStopExpression = reader.ReadVarString();
        MStopExpressionVersion = reader.ReadInt32(true);
        MController = reader.ReadVarString();
        MBlendOutTime = reader.ReadF32(true);
        int count12 = checked((int)reader.ReadVarUInt());
        MRuntimeIds = new List<ActorRuntimeID>(count12);
        for (int i12 = 0; i12 < count12; i12++) {
            ActorRuntimeID item12 = default!;
            ActorRuntimeID readValue1012 = new();
            readValue1012.Read(reader);
            item12 = readValue1012;
            MRuntimeIds.Add(item12);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(MAnimation);
        writer.WriteVarString(MNextState);
        writer.WriteVarString(MStopExpression);
        writer.WriteInt32((int)MStopExpressionVersion, true);
        writer.WriteVarString(MController);
        writer.WriteF32(MBlendOutTime, true);
        writer.WriteVarUInt(checked((uint)MRuntimeIds.Count));
        foreach (var item13 in MRuntimeIds) {
            item13.Write(writer);
        }
    }
}
