// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Animate Actor
/// </summary>
public sealed class AnimatePacket : Packet {
    public const int PacketId = 44;

    public AnimatePacketPayloadAction Action;
    public ActorRuntimeID TargetActorRuntimeID = new();
    public float Data;
    public ActorSwingSource? SwingSource;

    public override void Deserialize(BinaryReader reader) {
        Action = (global::BedrockProtocol.Enums.AnimatePacketPayloadAction)reader.ReadUInt8();
        TargetActorRuntimeID.Read(reader);
        Data = reader.ReadF32(true);
        if (reader.ReadBool()) {
            SwingSource = (global::BedrockProtocol.Enums.ActorSwingSource)reader.ReadUInt8();
        } else {
            SwingSource = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Action);
        TargetActorRuntimeID.Write(writer);
        writer.WriteF32(Data, true);
        writer.WriteBool(SwingSource is not null);
        if (SwingSource is { } optionalValue7) {
            writer.WriteUInt8((byte)optionalValue7);
        }
    }
}
