// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Requests an anvil to be damaged.
/// </summary>
public sealed class AnvilDamagePacket : Packet {
    public const int PacketId = 141;

    public BlockPos BlockPosition = new();

    public override void Deserialize(BinaryReader reader) {
        BlockPosition.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        BlockPosition.Write(writer);
    }
}
