// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Initiates websocket connection
/// </summary>
public sealed class AutomationClientConnectPacket : Packet {
    public const int PacketId = 95;

    public WebSocketPacketData WebSocketData = new();

    public override void Deserialize(BinaryReader reader) {
        WebSocketData.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        WebSocketData.Write(writer);
    }
}
