// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends the whole list of actor identifiers at game start from the server.
/// </summary>
public sealed class AvailableActorIdentifiersPacket : Packet {
    public const int PacketId = 119;

    public object IdentifierList = null!;

    public delegate object IdentifierListReader(BinaryReader reader);
    public delegate void IdentifierListWriter(BinaryWriter writer, object value);
    public IdentifierListReader? ReadIdentifierList { get; set; }
    public IdentifierListWriter? WriteIdentifierList { get; set; }

    public override void Deserialize(BinaryReader reader) {
        IdentifierList = (ReadIdentifierList ?? throw new InvalidOperationException("AvailableActorIdentifiersPacket.ReadIdentifierList must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        (WriteIdentifierList ?? throw new InvalidOperationException("AvailableActorIdentifiersPacket.WriteIdentifierList must be configured before serialization."))(writer, IdentifierList);
    }
}
