// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Contains all the available commands.
/// </summary>
public sealed class AvailableCommandsPacket : Packet {
    public const int PacketId = 76;

    public List<string> EnumValues = [];
    public List<string> ChainedSubcommandValues = [];
    public List<string> PostFixes = [];
    public List<AvailableCommandsPacketEnumData> EnumData = [];
    public List<AvailableCommandsPacketChainedSubcommandData> ChainedSubcommandData = [];
    public List<AvailableCommandsPacketCommandData> Commands = [];
    public List<AvailableCommandsPacketSoftEnumData> SoftEnums = [];
    public List<AvailableCommandsPacketConstrainedValueData> Constraints = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        EnumValues = new List<string>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            string item0 = default!;
            item0 = reader.ReadVarString();
            EnumValues.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        ChainedSubcommandValues = new List<string>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            string item2 = default!;
            item2 = reader.ReadVarString();
            ChainedSubcommandValues.Add(item2);
        }
        int count4 = checked((int)reader.ReadVarUInt());
        PostFixes = new List<string>(count4);
        for (int i4 = 0; i4 < count4; i4++) {
            string item4 = default!;
            item4 = reader.ReadVarString();
            PostFixes.Add(item4);
        }
        int count6 = checked((int)reader.ReadVarUInt());
        EnumData = new List<AvailableCommandsPacketEnumData>(count6);
        for (int i6 = 0; i6 < count6; i6++) {
            AvailableCommandsPacketEnumData item6 = default!;
            AvailableCommandsPacketEnumData readValue1006 = new();
            readValue1006.Read(reader);
            item6 = readValue1006;
            EnumData.Add(item6);
        }
        int count8 = checked((int)reader.ReadVarUInt());
        ChainedSubcommandData = new List<AvailableCommandsPacketChainedSubcommandData>(count8);
        for (int i8 = 0; i8 < count8; i8++) {
            AvailableCommandsPacketChainedSubcommandData item8 = default!;
            AvailableCommandsPacketChainedSubcommandData readValue1008 = new();
            readValue1008.Read(reader);
            item8 = readValue1008;
            ChainedSubcommandData.Add(item8);
        }
        int count10 = checked((int)reader.ReadVarUInt());
        Commands = new List<AvailableCommandsPacketCommandData>(count10);
        for (int i10 = 0; i10 < count10; i10++) {
            AvailableCommandsPacketCommandData item10 = default!;
            AvailableCommandsPacketCommandData readValue1010 = new();
            readValue1010.Read(reader);
            item10 = readValue1010;
            Commands.Add(item10);
        }
        int count12 = checked((int)reader.ReadVarUInt());
        SoftEnums = new List<AvailableCommandsPacketSoftEnumData>(count12);
        for (int i12 = 0; i12 < count12; i12++) {
            AvailableCommandsPacketSoftEnumData item12 = default!;
            AvailableCommandsPacketSoftEnumData readValue1012 = new();
            readValue1012.Read(reader);
            item12 = readValue1012;
            SoftEnums.Add(item12);
        }
        int count14 = checked((int)reader.ReadVarUInt());
        Constraints = new List<AvailableCommandsPacketConstrainedValueData>(count14);
        for (int i14 = 0; i14 < count14; i14++) {
            AvailableCommandsPacketConstrainedValueData item14 = default!;
            AvailableCommandsPacketConstrainedValueData readValue1014 = new();
            readValue1014.Read(reader);
            item14 = readValue1014;
            Constraints.Add(item14);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)EnumValues.Count));
        foreach (var item1 in EnumValues) {
            writer.WriteVarString(item1);
        }
        writer.WriteVarUInt(checked((uint)ChainedSubcommandValues.Count));
        foreach (var item3 in ChainedSubcommandValues) {
            writer.WriteVarString(item3);
        }
        writer.WriteVarUInt(checked((uint)PostFixes.Count));
        foreach (var item5 in PostFixes) {
            writer.WriteVarString(item5);
        }
        writer.WriteVarUInt(checked((uint)EnumData.Count));
        foreach (var item7 in EnumData) {
            item7.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)ChainedSubcommandData.Count));
        foreach (var item9 in ChainedSubcommandData) {
            item9.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)Commands.Count));
        foreach (var item11 in Commands) {
            item11.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)SoftEnums.Count));
        foreach (var item13 in SoftEnums) {
            item13.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)Constraints.Count));
        foreach (var item15 in Constraints) {
            item15.Write(writer);
        }
    }
}
