// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Contains the ID of the achievement to award
/// </summary>
public sealed class AwardAchievementPacket : Packet {
    public const int PacketId = 309;

    public int AchievementID;

    public override void Deserialize(BinaryReader reader) {
        AchievementID = reader.ReadInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt32(AchievementID, true);
    }
}
