// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// On world start, send clients the info for all available biomes.
/// </summary>
public sealed class BiomeDefinitionListPacket : Packet {
    public const int PacketId = 122;

    public Dictionary<ushort, BiomeDefinitionData> MapOfBiomeNamesToData = [];
    public BiomeStringList StringList = new();

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        MapOfBiomeNamesToData = new Dictionary<ushort, BiomeDefinitionData>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ushort key0 = default!;
            key0 = reader.ReadUInt16(true);
            BiomeDefinitionData value0 = default!;
            BiomeDefinitionData readValue2000 = new();
            readValue2000.Read(reader);
            value0 = readValue2000;
            MapOfBiomeNamesToData.Add(key0, value0);
        }
        StringList.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)MapOfBiomeNamesToData.Count));
        foreach (var pair1 in MapOfBiomeNamesToData) {
            writer.WriteUInt16(pair1.Key, true);
            pair1.Value.Write(writer);
        }
        StringList.Write(writer);
    }
}
