// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Whenever a block event happens it is sent from the server to sync client and server, with arbitrarily encoded information in b0 and b1.
/// </summary>
public sealed class BlockEventPacket : Packet {
    public const int PacketId = 26;

    public BlockPos BlockPosition = new();
    public int EventType;
    public int EventValue;

    public override void Deserialize(BinaryReader reader) {
        BlockPosition.Read(reader);
        EventType = reader.ReadZigZag();
        EventValue = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        BlockPosition.Write(writer);
        writer.WriteZigZag(EventType);
        writer.WriteZigZag(EventValue);
    }
}
