// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends the entire user data compound tag and the block position to the client.
/// </summary>
public sealed class BlockActorDataPacket : Packet {
    public const int PacketId = 56;

    public BlockPos BlockPosition = new();
    public object ActorDataTags = null!;

    public delegate object ActorDataTagsReader(BinaryReader reader);
    public delegate void ActorDataTagsWriter(BinaryWriter writer, object value);
    public ActorDataTagsReader? ReadActorDataTags { get; set; }
    public ActorDataTagsWriter? WriteActorDataTags { get; set; }

    public override void Deserialize(BinaryReader reader) {
        BlockPosition.Read(reader);
        ActorDataTags = (ReadActorDataTags ?? throw new InvalidOperationException("BlockActorDataPacket.ReadActorDataTags must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        BlockPosition.Write(writer);
        (WriteActorDataTags ?? throw new InvalidOperationException("BlockActorDataPacket.WriteActorDataTags must be configured before serialization."))(writer, ActorDataTags);
    }
}
