// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends the updated state of the Book and Quill item from client to server during use.
/// </summary>
public sealed class BookEditPacket : Packet {
    public const int PacketId = 97;

    public int BookSlot;
    public BookEditOperationVariant Operation = null!;

    public override void Deserialize(BinaryReader reader) {
        BookSlot = reader.ReadZigZag();
        uint variant2 = reader.ReadVarUInt();
        switch (variant2) {
            case 0:
                ReplacePage readValue3002 = new();
                readValue3002.Read(reader);
                Operation = readValue3002;
                break;
            case 1:
                AddPage readValue3003 = new();
                readValue3003.Read(reader);
                Operation = readValue3003;
                break;
            case 2:
                DeletePage readValue3004 = new();
                readValue3004.Read(reader);
                Operation = readValue3004;
                break;
            case 3:
                SwapPages readValue3005 = new();
                readValue3005.Read(reader);
                Operation = readValue3005;
                break;
            case 4:
                Finalize readValue3006 = new();
                readValue3006.Read(reader);
                Operation = readValue3006;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant2} for Operation.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(BookSlot);
        switch (Operation) {
            case ReplacePage variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case AddPage variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            case DeletePage variantValue2:
                writer.WriteVarUInt(2);
                variantValue2.Write(writer);
                break;
            case SwapPages variantValue3:
                writer.WriteVarUInt(3);
                variantValue3.Write(writer);
                break;
            case Finalize variantValue4:
                writer.WriteVarUInt(4);
                variantValue4.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Operation.");
        }
    }
}
