// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent when a boss gets updated
/// </summary>
public sealed class BossEventPacket : Packet {
    public const int PacketId = 74;

    public ActorUniqueID TargetActorID = new();
    public ActorUniqueID PlayerID = new();
    public BossEventUpdateType EventType;
    public string Name = string.Empty;
    public string FilteredName = string.Empty;
    public float HealthPercent;
    public BossBarColor Color;
    public BossBarOverlay Overlay;

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
        PlayerID.Read(reader);
        EventType = (global::BedrockProtocol.Enums.BossEventUpdateType)reader.ReadUInt8();
        Name = reader.ReadVarString();
        FilteredName = reader.ReadVarString();
        HealthPercent = reader.ReadF32(true);
        Color = (global::BedrockProtocol.Enums.BossBarColor)reader.ReadUInt8();
        Overlay = (global::BedrockProtocol.Enums.BossBarOverlay)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
        PlayerID.Write(writer);
        writer.WriteUInt8((byte)EventType);
        writer.WriteVarString(Name);
        writer.WriteVarString(FilteredName);
        writer.WriteF32(HealthPercent, true);
        writer.WriteUInt8((byte)Color);
        writer.WriteUInt8((byte)Overlay);
    }
}
