// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to sync CameraPresets data from server to clients.
/// </summary>
public sealed class CameraPresetsPacket : Packet {
    public const int PacketId = 198;

    public CameraPresets_2537458058 CameraPresets = new();

    public override void Deserialize(BinaryReader reader) {
        CameraPresets.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        CameraPresets.Write(writer);
    }
}
