// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Camera aim-assist registry presets/categories data sent from the server to clients.
/// </summary>
public sealed class CameraAimAssistPresetsPacket : Packet {
    public const int PacketId = 320;

    public List<CameraAimAssistCategoryDefinition> CameraAimAssistPresets = [];
    public List<CameraAimAssistPresetDefinition> CameraAimAssistCategories = [];
    public CameraAimAssistPresetsPacketOperation Operation;

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        CameraAimAssistPresets = new List<CameraAimAssistCategoryDefinition>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            CameraAimAssistCategoryDefinition item0 = default!;
            CameraAimAssistCategoryDefinition readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            CameraAimAssistPresets.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        CameraAimAssistCategories = new List<CameraAimAssistPresetDefinition>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            CameraAimAssistPresetDefinition item2 = default!;
            CameraAimAssistPresetDefinition readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            CameraAimAssistCategories.Add(item2);
        }
        Operation = (global::BedrockProtocol.Enums.CameraAimAssistPresetsPacketOperation)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)CameraAimAssistPresets.Count));
        foreach (var item1 in CameraAimAssistPresets) {
            item1.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)CameraAimAssistCategories.Count));
        foreach (var item3 in CameraAimAssistCategories) {
            item3.Write(writer);
        }
        writer.WriteUInt8((byte)Operation);
    }
}
