// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Camera custom spline data sent from server to client.
/// </summary>
public sealed class CameraSplinePacket : Packet {
    public const int PacketId = 338;

    public List<CameraSplineDefinition> CameraDataSplines = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        CameraDataSplines = new List<CameraSplineDefinition>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            CameraSplineDefinition item0 = default!;
            CameraSplineDefinition readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            CameraDataSplines.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)CameraDataSplines.Count));
        foreach (var item1 in CameraDataSplines) {
            item1.Write(writer);
        }
    }
}
