// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to control trigger camera shake movements on the client's player camera
/// </summary>
public sealed class CameraShakePacket : Packet {
    public const int PacketId = 159;

    public float Intensity;
    public float Seconds;
    public CameraShakeType ShakeType;
    public CameraShakeAction ShakeAction;

    public override void Deserialize(BinaryReader reader) {
        Intensity = reader.ReadF32(true);
        Seconds = reader.ReadF32(true);
        ShakeType = (global::BedrockProtocol.Enums.CameraShakeType)reader.ReadUInt8();
        ShakeAction = (global::BedrockProtocol.Enums.CameraShakeAction)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteF32(Intensity, true);
        writer.WriteF32(Seconds, true);
        writer.WriteUInt8((byte)ShakeType);
        writer.WriteUInt8((byte)ShakeAction);
    }
}
