// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// CameraAimAssist
/// </summary>
public sealed class CameraAimAssistPacket : Packet {
    public const int PacketId = 316;

    public string PresetId = string.Empty;
    public Vec2 ViewAngle = new();
    public float Distance;
    public CameraAimAssistPacketPayloadTargetMode TargetMode;
    public CameraAimAssistPacketPayloadAction Action;
    public bool ShowDebugRender;

    public override void Deserialize(BinaryReader reader) {
        PresetId = reader.ReadVarString();
        ViewAngle.Read(reader);
        Distance = reader.ReadF32(true);
        TargetMode = (global::BedrockProtocol.Enums.CameraAimAssistPacketPayloadTargetMode)reader.ReadUInt8();
        Action = (global::BedrockProtocol.Enums.CameraAimAssistPacketPayloadAction)reader.ReadUInt8();
        ShowDebugRender = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(PresetId);
        ViewAngle.Write(writer);
        writer.WriteF32(Distance, true);
        writer.WriteUInt8((byte)TargetMode);
        writer.WriteUInt8((byte)Action);
        writer.WriteBool(ShowDebugRender);
    }
}
