// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used only in EDU through the tripod camera item or the TakePictureCommand. Sends the camera actor id and the target player id from the server.
/// </summary>
public sealed class CameraPacket : Packet {
    public const int PacketId = 73;

    public ActorUniqueID CameraID = new();
    public ActorUniqueID TargetPlayerID = new();

    public override void Deserialize(BinaryReader reader) {
        CameraID.Read(reader);
        TargetPlayerID.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        CameraID.Write(writer);
        TargetPlayerID.Write(writer);
    }
}
