// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to send a CameraInstruction from the server to the specified clients.
/// </summary>
public sealed class CameraInstructionPacket : Packet {
    public const int PacketId = 300;

    public CameraInstruction CameraInstruction = new();

    public override void Deserialize(BinaryReader reader) {
        CameraInstruction.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        CameraInstruction.Write(writer);
    }
}
