// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Camera aim-assist actor priority data sent from the server to clients.
/// </summary>
public sealed class CameraAimAssistActorPriorityPacket : Packet {
    public const int PacketId = 339;

    public List<AimAssistActorPriorityData> CameraAimAssistActorPriorityList = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        CameraAimAssistActorPriorityList = new List<AimAssistActorPriorityData>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            AimAssistActorPriorityData item0 = default!;
            AimAssistActorPriorityData readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            CameraAimAssistActorPriorityList.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)CameraAimAssistActorPriorityList.Count));
        foreach (var item1 in CameraAimAssistActorPriorityList) {
            item1.Write(writer);
        }
    }
}
