// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The server sends this packet from the level to kick off dimension changing process.
/// </summary>
public sealed class ChangeDimensionPacket : Packet {
    public const int PacketId = 61;

    public DimensionType DimensionID = new();
    public Vec3 Position = new();
    public bool Respawn;
    public uint LoadingScreenId;

    public override void Deserialize(BinaryReader reader) {
        DimensionID.Read(reader);
        Position.Read(reader);
        Respawn = reader.ReadBool();
        LoadingScreenId = reader.ReadUInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        DimensionID.Write(writer);
        Position.Write(writer);
        writer.WriteBool(Respawn);
        writer.WriteUInt32(LoadingScreenId, true);
    }
}
