// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// packet containing data for changing mob property
/// </summary>
public sealed class ChangeMobPropertyPacket : Packet {
    public const int PacketId = 182;

    public ActorUniqueID ActorId = new();
    public string PropertyName = string.Empty;
    public bool BoolComponentValue;
    public string StringComponentValue = string.Empty;
    public int IntComponentValue;
    public float FloatComponentValue;

    public override void Deserialize(BinaryReader reader) {
        ActorId.Read(reader);
        PropertyName = reader.ReadVarString();
        BoolComponentValue = reader.ReadBool();
        StringComponentValue = reader.ReadVarString();
        IntComponentValue = reader.ReadZigZag();
        FloatComponentValue = reader.ReadF32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        ActorId.Write(writer);
        writer.WriteVarString(PropertyName);
        writer.WriteBool(BoolComponentValue);
        writer.WriteVarString(StringComponentValue);
        writer.WriteZigZag(IntComponentValue);
        writer.WriteF32(FloatComponentValue, true);
    }
}
