// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent when the world is loading. We don't know why it is sent four times. Defines the tick distance.
/// </summary>
public sealed class ChunkRadiusUpdatedPacket : Packet {
    public const int PacketId = 70;

    public int ChunkRadius;

    public override void Deserialize(BinaryReader reader) {
        ChunkRadius = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(ChunkRadius);
    }
}
