// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends client movement prediction information to the server
/// </summary>
public sealed class ClientMovementPredictionSyncPacket : Packet {
    public const int PacketId = 322;

    public ActorDataFlagComponent ActorDataFlag = new();
    public ActorDataBoundingBoxComponent ActorBoundingBox = new();
    public List<float> MovementAttributes = [];
    public ActorUniqueID ActorUniqueID = new();
    public bool ActorFlyingState;

    public override void Deserialize(BinaryReader reader) {
        ActorDataFlag.Read(reader);
        ActorBoundingBox.Read(reader);
        int count4 = 9;
        MovementAttributes = new List<float>(count4);
        for (int i4 = 0; i4 < count4; i4++) {
            float item4 = default!;
            item4 = reader.ReadF32(true);
            MovementAttributes.Add(item4);
        }
        ActorUniqueID.Read(reader);
        ActorFlyingState = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        ActorDataFlag.Write(writer);
        ActorBoundingBox.Write(writer);
        foreach (var item5 in MovementAttributes) {
            writer.WriteF32(item5, true);
        }
        ActorUniqueID.Write(writer);
        writer.WriteBool(ActorFlyingState);
    }
}
