// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to add/remove debug rendering objects.
/// </summary>
public sealed class ClientboundDebugRendererPacket : Packet {
    public const int PacketId = 164;

    public PayloadType Type;
    public DebugMarkerData? DebugMarkerData;

    public override void Deserialize(BinaryReader reader) {
        Type = (global::BedrockProtocol.Enums.PayloadType)reader.ReadUInt8();
        if (reader.ReadBool()) {
            DebugMarkerData readValue2 = new();
            readValue2.Read(reader);
            DebugMarkerData = readValue2;
        } else {
            DebugMarkerData = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Type);
        writer.WriteBool(DebugMarkerData is not null);
        if (DebugMarkerData is { } optionalValue3) {
            optionalValue3.Write(writer);
        }
    }
}
