// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set the control scheme that the player should use
/// </summary>
public sealed class ClientboundControlSchemeSetPacket : Packet {
    public const int PacketId = 327;

    public ControlScheme ControlScheme;

    public override void Deserialize(BinaryReader reader) {
        ControlScheme = (global::BedrockProtocol.Enums.ControlScheme)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)ControlScheme);
    }
}
