// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent to update sound data.
/// </summary>
public sealed class ClientboundUpdateSoundDataPacket : Packet {
    public const int PacketId = 348;

    public ServerSoundHandle ServerSoundHandle = new();
    public ClientboundUpdateSoundDataStopVariant? Stop;
    public ClientboundUpdateSoundDataSetVolumeVariant? SetVolume;
    public ClientboundUpdateSoundDataSetPitchVariant? SetPitch;
    public ClientboundUpdateSoundDataFadeVariant? Fade;
    public ClientboundUpdateSoundDataSeekToVariant? SeekTo;
    public ClientboundUpdateSoundDataPauseVariant? Pause;
    public ClientboundUpdateSoundDataResumeVariant? Resume;

    public override void Deserialize(BinaryReader reader) {
        ServerSoundHandle.Read(reader);
        if (reader.ReadBool()) {
            uint variant2 = reader.ReadVarUInt();
            switch (variant2) {
                case 0:
                    Stop readValue3002 = new();
                    readValue3002.Read(reader);
                    Stop = readValue3002;
                    break;
                case 1:
                    SetVolume readValue3003 = new();
                    readValue3003.Read(reader);
                    Stop = readValue3003;
                    break;
                case 2:
                    SetPitch readValue3004 = new();
                    readValue3004.Read(reader);
                    Stop = readValue3004;
                    break;
                case 3:
                    Fade readValue3005 = new();
                    readValue3005.Read(reader);
                    Stop = readValue3005;
                    break;
                case 4:
                    SeekTo readValue3006 = new();
                    readValue3006.Read(reader);
                    Stop = readValue3006;
                    break;
                case 5:
                    Pause readValue3007 = new();
                    readValue3007.Read(reader);
                    Stop = readValue3007;
                    break;
                case 6:
                    Resume readValue3008 = new();
                    readValue3008.Read(reader);
                    Stop = readValue3008;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant2} for Stop.");
            }
        } else {
            Stop = default;
        }
        if (reader.ReadBool()) {
            uint variant4 = reader.ReadVarUInt();
            switch (variant4) {
                case 0:
                    Stop readValue3004 = new();
                    readValue3004.Read(reader);
                    SetVolume = readValue3004;
                    break;
                case 1:
                    SetVolume readValue3005 = new();
                    readValue3005.Read(reader);
                    SetVolume = readValue3005;
                    break;
                case 2:
                    SetPitch readValue3006 = new();
                    readValue3006.Read(reader);
                    SetVolume = readValue3006;
                    break;
                case 3:
                    Fade readValue3007 = new();
                    readValue3007.Read(reader);
                    SetVolume = readValue3007;
                    break;
                case 4:
                    SeekTo readValue3008 = new();
                    readValue3008.Read(reader);
                    SetVolume = readValue3008;
                    break;
                case 5:
                    Pause readValue3009 = new();
                    readValue3009.Read(reader);
                    SetVolume = readValue3009;
                    break;
                case 6:
                    Resume readValue3010 = new();
                    readValue3010.Read(reader);
                    SetVolume = readValue3010;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant4} for SetVolume.");
            }
        } else {
            SetVolume = default;
        }
        if (reader.ReadBool()) {
            uint variant6 = reader.ReadVarUInt();
            switch (variant6) {
                case 0:
                    Stop readValue3006 = new();
                    readValue3006.Read(reader);
                    SetPitch = readValue3006;
                    break;
                case 1:
                    SetVolume readValue3007 = new();
                    readValue3007.Read(reader);
                    SetPitch = readValue3007;
                    break;
                case 2:
                    SetPitch readValue3008 = new();
                    readValue3008.Read(reader);
                    SetPitch = readValue3008;
                    break;
                case 3:
                    Fade readValue3009 = new();
                    readValue3009.Read(reader);
                    SetPitch = readValue3009;
                    break;
                case 4:
                    SeekTo readValue3010 = new();
                    readValue3010.Read(reader);
                    SetPitch = readValue3010;
                    break;
                case 5:
                    Pause readValue3011 = new();
                    readValue3011.Read(reader);
                    SetPitch = readValue3011;
                    break;
                case 6:
                    Resume readValue3012 = new();
                    readValue3012.Read(reader);
                    SetPitch = readValue3012;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant6} for SetPitch.");
            }
        } else {
            SetPitch = default;
        }
        if (reader.ReadBool()) {
            uint variant8 = reader.ReadVarUInt();
            switch (variant8) {
                case 0:
                    Stop readValue3008 = new();
                    readValue3008.Read(reader);
                    Fade = readValue3008;
                    break;
                case 1:
                    SetVolume readValue3009 = new();
                    readValue3009.Read(reader);
                    Fade = readValue3009;
                    break;
                case 2:
                    SetPitch readValue3010 = new();
                    readValue3010.Read(reader);
                    Fade = readValue3010;
                    break;
                case 3:
                    Fade readValue3011 = new();
                    readValue3011.Read(reader);
                    Fade = readValue3011;
                    break;
                case 4:
                    SeekTo readValue3012 = new();
                    readValue3012.Read(reader);
                    Fade = readValue3012;
                    break;
                case 5:
                    Pause readValue3013 = new();
                    readValue3013.Read(reader);
                    Fade = readValue3013;
                    break;
                case 6:
                    Resume readValue3014 = new();
                    readValue3014.Read(reader);
                    Fade = readValue3014;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant8} for Fade.");
            }
        } else {
            Fade = default;
        }
        if (reader.ReadBool()) {
            uint variant10 = reader.ReadVarUInt();
            switch (variant10) {
                case 0:
                    Stop readValue3010 = new();
                    readValue3010.Read(reader);
                    SeekTo = readValue3010;
                    break;
                case 1:
                    SetVolume readValue3011 = new();
                    readValue3011.Read(reader);
                    SeekTo = readValue3011;
                    break;
                case 2:
                    SetPitch readValue3012 = new();
                    readValue3012.Read(reader);
                    SeekTo = readValue3012;
                    break;
                case 3:
                    Fade readValue3013 = new();
                    readValue3013.Read(reader);
                    SeekTo = readValue3013;
                    break;
                case 4:
                    SeekTo readValue3014 = new();
                    readValue3014.Read(reader);
                    SeekTo = readValue3014;
                    break;
                case 5:
                    Pause readValue3015 = new();
                    readValue3015.Read(reader);
                    SeekTo = readValue3015;
                    break;
                case 6:
                    Resume readValue3016 = new();
                    readValue3016.Read(reader);
                    SeekTo = readValue3016;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant10} for SeekTo.");
            }
        } else {
            SeekTo = default;
        }
        if (reader.ReadBool()) {
            uint variant12 = reader.ReadVarUInt();
            switch (variant12) {
                case 0:
                    Stop readValue3012 = new();
                    readValue3012.Read(reader);
                    Pause = readValue3012;
                    break;
                case 1:
                    SetVolume readValue3013 = new();
                    readValue3013.Read(reader);
                    Pause = readValue3013;
                    break;
                case 2:
                    SetPitch readValue3014 = new();
                    readValue3014.Read(reader);
                    Pause = readValue3014;
                    break;
                case 3:
                    Fade readValue3015 = new();
                    readValue3015.Read(reader);
                    Pause = readValue3015;
                    break;
                case 4:
                    SeekTo readValue3016 = new();
                    readValue3016.Read(reader);
                    Pause = readValue3016;
                    break;
                case 5:
                    Pause readValue3017 = new();
                    readValue3017.Read(reader);
                    Pause = readValue3017;
                    break;
                case 6:
                    Resume readValue3018 = new();
                    readValue3018.Read(reader);
                    Pause = readValue3018;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant12} for Pause.");
            }
        } else {
            Pause = default;
        }
        if (reader.ReadBool()) {
            uint variant14 = reader.ReadVarUInt();
            switch (variant14) {
                case 0:
                    Stop readValue3014 = new();
                    readValue3014.Read(reader);
                    Resume = readValue3014;
                    break;
                case 1:
                    SetVolume readValue3015 = new();
                    readValue3015.Read(reader);
                    Resume = readValue3015;
                    break;
                case 2:
                    SetPitch readValue3016 = new();
                    readValue3016.Read(reader);
                    Resume = readValue3016;
                    break;
                case 3:
                    Fade readValue3017 = new();
                    readValue3017.Read(reader);
                    Resume = readValue3017;
                    break;
                case 4:
                    SeekTo readValue3018 = new();
                    readValue3018.Read(reader);
                    Resume = readValue3018;
                    break;
                case 5:
                    Pause readValue3019 = new();
                    readValue3019.Read(reader);
                    Resume = readValue3019;
                    break;
                case 6:
                    Resume readValue3020 = new();
                    readValue3020.Read(reader);
                    Resume = readValue3020;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant14} for Resume.");
            }
        } else {
            Resume = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        ServerSoundHandle.Write(writer);
        writer.WriteBool(Stop is not null);
        if (Stop is { } optionalValue3) {
            switch (optionalValue3) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue3.");
            }
        }
        writer.WriteBool(SetVolume is not null);
        if (SetVolume is { } optionalValue5) {
            switch (optionalValue5) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue5.");
            }
        }
        writer.WriteBool(SetPitch is not null);
        if (SetPitch is { } optionalValue7) {
            switch (optionalValue7) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue7.");
            }
        }
        writer.WriteBool(Fade is not null);
        if (Fade is { } optionalValue9) {
            switch (optionalValue9) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue9.");
            }
        }
        writer.WriteBool(SeekTo is not null);
        if (SeekTo is { } optionalValue11) {
            switch (optionalValue11) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue11.");
            }
        }
        writer.WriteBool(Pause is not null);
        if (Pause is { } optionalValue13) {
            switch (optionalValue13) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue13.");
            }
        }
        writer.WriteBool(Resume is not null);
        if (Resume is { } optionalValue15) {
            switch (optionalValue15) {
                case Stop variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case SetVolume variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                case SetPitch variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                case Fade variantValue3:
                    writer.WriteVarUInt(3);
                    variantValue3.Write(writer);
                    break;
                case SeekTo variantValue4:
                    writer.WriteVarUInt(4);
                    variantValue4.Write(writer);
                    break;
                case Pause variantValue5:
                    writer.WriteVarUInt(5);
                    variantValue5.Write(writer);
                    break;
                case Resume variantValue6:
                    writer.WriteVarUInt(6);
                    variantValue6.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue15.");
            }
        }
    }
}
