// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Client Cache Blob Status Packet
/// </summary>
public sealed class ClientCacheBlobStatusPacket : Packet {
    public const int PacketId = 135;

    public List<ulong> MissingIds = [];
    public List<ulong> FoundIds = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        MissingIds = new List<ulong>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ulong item0 = default!;
            item0 = reader.ReadUInt64(true);
            MissingIds.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        FoundIds = new List<ulong>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            ulong item2 = default!;
            item2 = reader.ReadUInt64(true);
            FoundIds.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)MissingIds.Count));
        foreach (var item1 in MissingIds) {
            writer.WriteUInt64(item1, true);
        }
        writer.WriteVarUInt(checked((uint)FoundIds.Count));
        foreach (var item3 in FoundIds) {
            writer.WriteUInt64(item3, true);
        }
    }
}
