// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// It is sent by the Client once, at login, to communicate if it supports the cache or not.
/// </summary>
public sealed class ClientCacheStatusPacket : Packet {
    public const int PacketId = 129;

    public bool IsCacheSupported;

    public override void Deserialize(BinaryReader reader) {
        IsCacheSupported = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(IsCacheSupported);
    }
}
