// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends a set of update properties for the texture shift system from the server to the client.
/// </summary>
public sealed class ClientboundTextureShiftPacket : Packet {
    public const int PacketId = 336;

    public ClientboundTextureShiftPacketPayloadAction ActionID = new();
    public string CollectionName = string.Empty;
    public string FromStep = string.Empty;
    public string ToStep = string.Empty;
    public List<string> AllSteps = [];
    public ulong CurrentLengthInTicks;
    public ulong TotalLengthInTicks;
    public bool Enabled;

    public override void Deserialize(BinaryReader reader) {
        ActionID = (ClientboundTextureShiftPacketPayloadAction)reader.ReadUInt8();
        CollectionName = reader.ReadVarString();
        FromStep = reader.ReadVarString();
        ToStep = reader.ReadVarString();
        int count8 = checked((int)reader.ReadVarUInt());
        AllSteps = new List<string>(count8);
        for (int i8 = 0; i8 < count8; i8++) {
            string item8 = default!;
            item8 = reader.ReadVarString();
            AllSteps.Add(item8);
        }
        CurrentLengthInTicks = reader.ReadVarULong();
        TotalLengthInTicks = reader.ReadVarULong();
        Enabled = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)ActionID);
        writer.WriteVarString(CollectionName);
        writer.WriteVarString(FromStep);
        writer.WriteVarString(ToStep);
        writer.WriteVarUInt(checked((uint)AllSteps.Count));
        foreach (var item9 in AllSteps) {
            writer.WriteVarString(item9);
        }
        writer.WriteVarULong(CurrentLengthInTicks);
        writer.WriteVarULong(TotalLengthInTicks);
        writer.WriteBool(Enabled);
    }
}
