// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Map item data including pixels, decorations, and creation info
/// </summary>
public sealed class ClientboundMapItemDataPacket : Packet {
    public const int PacketId = 67;

    public ActorUniqueID MapID = new();
    public byte Dimension;
    public bool IsLocked;
    public BlockPos MapOrigin = new();
    public List<ActorUniqueID>? CreationMapIDs;
    public sbyte? Scale;
    public List<MapItemTrackedActorUniqueId>? TrackedActorIDs;
    public List<MapDecoration>? Decorations;
    public int? Width;
    public int? Height;
    public int? StartX;
    public int? StartY;
    public List<uint>? Pixels;

    public override void Deserialize(BinaryReader reader) {
        MapID.Read(reader);
        Dimension = reader.ReadUInt8();
        IsLocked = reader.ReadBool();
        MapOrigin.Read(reader);
        if (reader.ReadBool()) {
            int count8 = checked((int)reader.ReadVarUInt());
            CreationMapIDs = new List<ActorUniqueID>(count8);
            for (int i8 = 0; i8 < count8; i8++) {
                ActorUniqueID item8 = default!;
                ActorUniqueID readValue1008 = new();
                readValue1008.Read(reader);
                item8 = readValue1008;
                CreationMapIDs.Add(item8);
            }
        } else {
            CreationMapIDs = default;
        }
        if (reader.ReadBool()) {
            Scale = reader.ReadInt8();
        } else {
            Scale = default;
        }
        if (reader.ReadBool()) {
            int count12 = checked((int)reader.ReadVarUInt());
            TrackedActorIDs = new List<MapItemTrackedActorUniqueId>(count12);
            for (int i12 = 0; i12 < count12; i12++) {
                MapItemTrackedActorUniqueId item12 = default!;
                MapItemTrackedActorUniqueId readValue1012 = new();
                readValue1012.Read(reader);
                item12 = readValue1012;
                TrackedActorIDs.Add(item12);
            }
        } else {
            TrackedActorIDs = default;
        }
        if (reader.ReadBool()) {
            int count14 = checked((int)reader.ReadVarUInt());
            Decorations = new List<MapDecoration>(count14);
            for (int i14 = 0; i14 < count14; i14++) {
                MapDecoration item14 = default!;
                MapDecoration readValue1014 = new();
                readValue1014.Read(reader);
                item14 = readValue1014;
                Decorations.Add(item14);
            }
        } else {
            Decorations = default;
        }
        if (reader.ReadBool()) {
            Width = reader.ReadZigZag();
        } else {
            Width = default;
        }
        if (reader.ReadBool()) {
            Height = reader.ReadZigZag();
        } else {
            Height = default;
        }
        if (reader.ReadBool()) {
            StartX = reader.ReadZigZag();
        } else {
            StartX = default;
        }
        if (reader.ReadBool()) {
            StartY = reader.ReadZigZag();
        } else {
            StartY = default;
        }
        if (reader.ReadBool()) {
            int count24 = checked((int)reader.ReadVarUInt());
            Pixels = new List<uint>(count24);
            for (int i24 = 0; i24 < count24; i24++) {
                uint item24 = default!;
                item24 = reader.ReadUInt32(true);
                Pixels.Add(item24);
            }
        } else {
            Pixels = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        MapID.Write(writer);
        writer.WriteUInt8(Dimension);
        writer.WriteBool(IsLocked);
        MapOrigin.Write(writer);
        writer.WriteBool(CreationMapIDs is not null);
        if (CreationMapIDs is { } optionalValue9) {
            writer.WriteVarUInt(checked((uint)optionalValue9.Count));
            foreach (var item9 in optionalValue9) {
                item9.Write(writer);
            }
        }
        writer.WriteBool(Scale is not null);
        if (Scale is { } optionalValue11) {
            writer.WriteInt8(optionalValue11);
        }
        writer.WriteBool(TrackedActorIDs is not null);
        if (TrackedActorIDs is { } optionalValue13) {
            writer.WriteVarUInt(checked((uint)optionalValue13.Count));
            foreach (var item13 in optionalValue13) {
                item13.Write(writer);
            }
        }
        writer.WriteBool(Decorations is not null);
        if (Decorations is { } optionalValue15) {
            writer.WriteVarUInt(checked((uint)optionalValue15.Count));
            foreach (var item15 in optionalValue15) {
                item15.Write(writer);
            }
        }
        writer.WriteBool(Width is not null);
        if (Width is { } optionalValue17) {
            writer.WriteZigZag(optionalValue17);
        }
        writer.WriteBool(Height is not null);
        if (Height is { } optionalValue19) {
            writer.WriteZigZag(optionalValue19);
        }
        writer.WriteBool(StartX is not null);
        if (StartX is { } optionalValue21) {
            writer.WriteZigZag(optionalValue21);
        }
        writer.WriteBool(StartY is not null);
        if (StartY is { } optionalValue23) {
            writer.WriteZigZag(optionalValue23);
        }
        writer.WriteBool(Pixels is not null);
        if (Pixels is { } optionalValue25) {
            writer.WriteVarUInt(checked((uint)optionalValue25.Count));
            foreach (var item25 in optionalValue25) {
                writer.WriteUInt32(item25, true);
            }
        }
    }
}
