// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Allows the server to tell the client to show a Data Driven UI screen.
/// </summary>
public sealed class ClientboundDataDrivenUIShowScreenPacket : Packet {
    public const int PacketId = 333;

    public string ScreenId = string.Empty;
    public uint FormId;
    public uint? DataInstanceId;

    public override void Deserialize(BinaryReader reader) {
        ScreenId = reader.ReadVarString();
        FormId = reader.ReadUInt32(true);
        if (reader.ReadBool()) {
            DataInstanceId = reader.ReadUInt32(true);
        } else {
            DataInstanceId = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ScreenId);
        writer.WriteUInt32(FormId, true);
        writer.WriteBool(DataInstanceId is not null);
        if (DataInstanceId is { } optionalValue5) {
            writer.WriteUInt32(optionalValue5, true);
        }
    }
}
