// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends a list of data store properties from the server to the client.
/// </summary>
public sealed class ClientboundDataStorePacket : Packet {
    public const int PacketId = 330;

    public List<ClientboundDataStorePayloadUpdateVariant> Updates = [];

    public DataStoreChange.TheNewPropertyValueReader? ReadTheNewPropertyValue { get; set; }
    public DataStoreChange.TheNewPropertyValueWriter? WriteTheNewPropertyValue { get; set; }

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Updates = new List<ClientboundDataStorePayloadUpdateVariant>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ClientboundDataStorePayloadUpdateVariant item0 = default!;
            uint variant1000 = reader.ReadVarUInt();
            switch (variant1000) {
                case 0:
                    DataStoreUpdate readValue4000 = new();
                    readValue4000.Read(reader);
                    item0 = readValue4000;
                    break;
                case 1:
                    DataStoreChange readValue4001 = new();
                    readValue4001.Read(reader, (ReadTheNewPropertyValue ?? throw new InvalidOperationException("ClientboundDataStorePacket.ReadTheNewPropertyValue must be configured before deserialization.")));
                    item0 = readValue4001;
                    break;
                case 2:
                    DataStoreRemoval readValue4002 = new();
                    readValue4002.Read(reader);
                    item0 = readValue4002;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant1000} for item0.");
            }
            Updates.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Updates.Count));
        foreach (var item1 in Updates) {
            switch (item1) {
                case DataStoreUpdate variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case DataStoreChange variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer, (WriteTheNewPropertyValue ?? throw new InvalidOperationException("ClientboundDataStorePacket.WriteTheNewPropertyValue must be configured before serialization.")));
                    break;
                case DataStoreRemoval variantValue2:
                    writer.WriteVarUInt(2);
                    variantValue2.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for item1.");
            }
        }
    }
}
