// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Client-side activation of aim-assist
/// </summary>
public sealed class ClientCameraAimAssistPacket : Packet {
    public const int PacketId = 321;

    public string CameraPresetId = string.Empty;
    public ClientCameraAimAssistPacketAction Action;
    public bool? AllowAimAssist;

    public override void Deserialize(BinaryReader reader) {
        CameraPresetId = reader.ReadVarString();
        Action = (global::BedrockProtocol.Enums.ClientCameraAimAssistPacketAction)reader.ReadUInt8();
        if (reader.ReadBool()) {
            AllowAimAssist = reader.ReadBool();
        } else {
            AllowAimAssist = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(CameraPresetId);
        writer.WriteUInt8((byte)Action);
        writer.WriteBool(AllowAimAssist is not null);
        if (AllowAimAssist is { } optionalValue5) {
            writer.WriteBool(optionalValue5);
        }
    }
}
