// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Allows the server to tell the client to close Data Driven UI screens.
/// </summary>
public sealed class ClientboundDataDrivenUICloseScreenPacket : Packet {
    public const int PacketId = 334;

    public uint FormId;

    public override void Deserialize(BinaryReader reader) {
        FormId = reader.ReadUInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt32(FormId, true);
    }
}
