// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Syncs Attribute Layers to the Client (Currently disabled)
/// </summary>
public sealed class ClientboundAttributeLayerSyncPacket : Packet {
    public const int PacketId = 345;

    public ClientboundAttributeLayerSyncDataVariant Data = null!;

    public override void Deserialize(BinaryReader reader) {
        uint variant0 = reader.ReadVarUInt();
        switch (variant0) {
            case 0:
                UpdateAttributeLayersData readValue3000 = new();
                readValue3000.Read(reader);
                Data = readValue3000;
                break;
            case 1:
                UpdateAttributeLayerSettingsData readValue3001 = new();
                readValue3001.Read(reader);
                Data = readValue3001;
                break;
            case 2:
                UpdateEnvironmentAttributesData readValue3002 = new();
                readValue3002.Read(reader);
                Data = readValue3002;
                break;
            case 3:
                RemoveEnvironmentAttributesData readValue3003 = new();
                readValue3003.Read(reader);
                Data = readValue3003;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant0} for Data.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        switch (Data) {
            case UpdateAttributeLayersData variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case UpdateAttributeLayerSettingsData variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            case UpdateEnvironmentAttributesData variantValue2:
                writer.WriteVarUInt(2);
                variantValue2.Write(writer);
                break;
            case RemoveEnvironmentAttributesData variantValue3:
                writer.WriteVarUInt(3);
                variantValue3.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Data.");
        }
    }
}
