// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Allows the server to tell the client to reload the Data Driven UI.
/// </summary>
public sealed class ClientboundDataDrivenUIReloadPacket : Packet {
    public const int PacketId = 335;


    public override void Deserialize(BinaryReader reader) {
    }

    public override void Serialize(BinaryWriter writer) {
    }
}
