// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Only active in a real client-server scenario. This packet is just a list of &lt;blobId, blob&gt; pairs sent from server to client.
/// </summary>
public sealed class ClientCacheMissResponsePacket : Packet {
    public const int PacketId = 136;

    public List<MissingBlobData> MissingBlobs = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        MissingBlobs = new List<MissingBlobData>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            MissingBlobData item0 = default!;
            MissingBlobData readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            MissingBlobs.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)MissingBlobs.Count));
        foreach (var item1 in MissingBlobs) {
            item1.Write(writer);
        }
    }
}
