// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to client to force close all server forms on the stack and return to the HUD screen.
/// </summary>
public sealed class ClientboundCloseFormPacket : Packet {
    public const int PacketId = 310;


    public override void Deserialize(BinaryReader reader) {
    }

    public override void Serialize(BinaryWriter writer) {
    }
}
