// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Code Builder Packet
/// </summary>
public sealed class CodeBuilderPacket : Packet {
    public const int PacketId = 150;

    public string URL = string.Empty;
    public bool ShouldOpenCodeBuilder;

    public override void Deserialize(BinaryReader reader) {
        URL = reader.ReadVarString();
        ShouldOpenCodeBuilder = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(URL);
        writer.WriteBool(ShouldOpenCodeBuilder);
    }
}
