// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is EDU exclusive, used in getInterface() of WebviewSystem
/// </summary>
public sealed class CodeBuilderSourcePacket : Packet {
    public const int PacketId = 178;

    public CodeBuilderStorageQueryOptionsOperation Operation;
    public CodeBuilderStorageQueryOptionsCategory Category;
    public CodeBuilderExecutionStateCodeStatus CodeStatus;

    public override void Deserialize(BinaryReader reader) {
        Operation = (global::BedrockProtocol.Enums.CodeBuilderStorageQueryOptionsOperation)reader.ReadUInt8();
        Category = (global::BedrockProtocol.Enums.CodeBuilderStorageQueryOptionsCategory)reader.ReadUInt8();
        CodeStatus = (global::BedrockProtocol.Enums.CodeBuilderExecutionStateCodeStatus)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Operation);
        writer.WriteUInt8((byte)Category);
        writer.WriteUInt8((byte)CodeStatus);
    }
}
