// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// "slash" command execution, client to server.
/// </summary>
public sealed class CommandRequestPacket : Packet {
    public const int PacketId = 77;

    public string Command = string.Empty;
    public CommandOriginData Origin = new();
    public bool IsInternal;
    public CurrentCmdVersion Version;

    public override void Deserialize(BinaryReader reader) {
        Command = reader.ReadVarString();
        Origin.Read(reader);
        IsInternal = reader.ReadBool();
        Version = (global::BedrockProtocol.Enums.CurrentCmdVersion)reader.ReadInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(Command);
        Origin.Write(writer);
        writer.WriteBool(IsInternal);
        writer.WriteInt32((int)Version, true);
    }
}
