// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// "slash" command execution output, server to client.
/// </summary>
public sealed class CommandOutputPacket : Packet {
    public const int PacketId = 79;

    public CommandOriginData OriginData = new();
    public CommandOutput Output = new();

    public override void Deserialize(BinaryReader reader) {
        OriginData.Read(reader);
        Output.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        OriginData.Write(writer);
        Output.Write(writer);
    }
}
