// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Command Block Update
/// </summary>
public sealed class CommandBlockUpdatePacket : Packet {
    public const int PacketId = 78;

    public CommandBlockUpdateTargetVariant Target = null!;
    public string Command = string.Empty;
    public string LastOutput = string.Empty;
    public string Name = string.Empty;
    public string FilteredName = string.Empty;
    public bool TrackOutput;
    public int TickDelay;
    public bool ExecuteOnFirstTick;

    public override void Deserialize(BinaryReader reader) {
        uint variant0 = reader.ReadVarUInt();
        switch (variant0) {
            case 0:
                EntityCommandTarget readValue3000 = new();
                readValue3000.Read(reader);
                Target = readValue3000;
                break;
            case 1:
                BlockCommandData readValue3001 = new();
                readValue3001.Read(reader);
                Target = readValue3001;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant0} for Target.");
        }
        Command = reader.ReadVarString();
        LastOutput = reader.ReadVarString();
        Name = reader.ReadVarString();
        FilteredName = reader.ReadVarString();
        TrackOutput = reader.ReadBool();
        TickDelay = reader.ReadInt32(true);
        ExecuteOnFirstTick = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        switch (Target) {
            case EntityCommandTarget variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case BlockCommandData variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Target.");
        }
        writer.WriteVarString(Command);
        writer.WriteVarString(LastOutput);
        writer.WriteVarString(Name);
        writer.WriteVarString(FilteredName);
        writer.WriteBool(TrackOutput);
        writer.WriteInt32(TickDelay, true);
        writer.WriteBool(ExecuteOnFirstTick);
    }
}
