// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Send server to client to complete the using item process. An example is when you finish drinking or eating.
/// </summary>
public sealed class CompletedUsingItemPacket : Packet {
    public const int PacketId = 142;

    public short ItemId;
    public int ItemUseMethod;

    public override void Deserialize(BinaryReader reader) {
        ItemId = reader.ReadInt16(true);
        ItemUseMethod = reader.ReadInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt16(ItemId, true);
        writer.WriteInt32(ItemUseMethod, true);
    }
}
