// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is sent from the server basically any time that the "cooking" state of the brewing stand or the furnace changes (i.e. the loading bar)
/// </summary>
public sealed class ContainerSetDataPacket : Packet {
    public const int PacketId = 51;

    public byte ContainerID;
    public int ID;
    public int Value;

    public override void Deserialize(BinaryReader reader) {
        ContainerID = reader.ReadUInt8();
        ID = reader.ReadZigZag();
        Value = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(ContainerID);
        writer.WriteZigZag(ID);
        writer.WriteZigZag(Value);
    }
}
