// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server so that the client knows to open the container screen and do the chest opening animation.
/// </summary>
public sealed class ContainerOpenPacket : Packet {
    public const int PacketId = 46;

    public byte ContainerId;
    public byte ContainerType;
    public BlockPos Position = new();
    public ActorUniqueID TargetActorID = new();

    public override void Deserialize(BinaryReader reader) {
        ContainerId = reader.ReadUInt8();
        ContainerType = reader.ReadUInt8();
        Position.Read(reader);
        TargetActorID.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(ContainerId);
        writer.WriteUInt8(ContainerType);
        Position.Write(writer);
        TargetActorID.Write(writer);
    }
}
