// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used to trigger a clientside cleanup of the dynamic container registry.
/// </summary>
public sealed class ContainerRegistryCleanupPacket : Packet {
    public const int PacketId = 317;

    public List<FullContainerName> RemovedContainers = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        RemovedContainers = new List<FullContainerName>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            FullContainerName item0 = default!;
            FullContainerName readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            RemovedContainers.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)RemovedContainers.Count));
        foreach (var item1 in RemovedContainers) {
            item1.Write(writer);
        }
    }
}
