// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// After the game deletes the container manager on the client, the client sends this packet.
/// Then the server deletes its container manager, and sends a packet back to the client that closes the container screen.
/// </summary>
public sealed class ContainerClosePacket : Packet {
    public const int PacketId = 47;

    public byte ContainerId;
    public byte ContainerType;
    public bool ServerInitiatedClose;

    public override void Deserialize(BinaryReader reader) {
        ContainerId = reader.ReadUInt8();
        ContainerType = reader.ReadUInt8();
        ServerInitiatedClose = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)ContainerId);
        writer.WriteUInt8((byte)ContainerType);
        writer.WriteBool(ServerInitiatedClose);
    }
}
