// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent to a player when their simulation of movement mismatches enough from the server that it wants to correct the client.
/// </summary>
public sealed class CorrectPlayerMovePredictionPacket : Packet {
    public const int PacketId = 161;

    public RewindType PredictionType;
    public Vec3 Pos = new();
    public Vec3 PosDelta = new();
    public Vec2 Rotation = new();
    public float? VehicleAngularVelocity;
    public bool OnGround;
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        PredictionType = (global::BedrockProtocol.Enums.RewindType)reader.ReadUInt8();
        Pos.Read(reader);
        PosDelta.Read(reader);
        Rotation.Read(reader);
        if (reader.ReadBool()) {
            VehicleAngularVelocity = reader.ReadF32(true);
        } else {
            VehicleAngularVelocity = default;
        }
        OnGround = reader.ReadBool();
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)PredictionType);
        Pos.Write(writer);
        PosDelta.Write(writer);
        Rotation.Write(writer);
        writer.WriteBool(VehicleAngularVelocity is not null);
        if (VehicleAngularVelocity is { } optionalValue9) {
            writer.WriteF32(optionalValue9, true);
        }
        writer.WriteBool(OnGround);
        Tick.Write(writer);
    }
}
