// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Crafting Data
/// </summary>
public sealed class CraftingDataPacket : Packet {
    public const int PacketId = 52;

    public List<ShapedRecipePayload> ShapedRecipes = [];
    public List<ShapelessRecipePayload> ShapelessRecipes = [];
    public List<MultiRecipePayload> MultiRecipes = [];
    public List<ShapelessRecipePayload> UserDataShapelessRecipes = [];
    public List<ShapelessRecipePayload> ShapelessChemistryRecipes = [];
    public List<ShapedRecipePayload> ShapedChemistryRecipes = [];
    public List<SmithingTransformRecipePayload> SmithingTransformRecipes = [];
    public List<SmithingTrimRecipePayload> SmithingTrimRecipes = [];
    public List<PotionMixDataEntry> PotionMixes = [];
    public List<ContainerMixDataEntry> ContainerMixes = [];
    public List<MaterialReducerDataEntry> MaterialReducers = [];
    public bool ClearRecipes;

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ShapedRecipes = new List<ShapedRecipePayload>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ShapedRecipePayload item0 = default!;
            ShapedRecipePayload readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            ShapedRecipes.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        ShapelessRecipes = new List<ShapelessRecipePayload>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            ShapelessRecipePayload item2 = default!;
            ShapelessRecipePayload readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            ShapelessRecipes.Add(item2);
        }
        int count4 = checked((int)reader.ReadVarUInt());
        MultiRecipes = new List<MultiRecipePayload>(count4);
        for (int i4 = 0; i4 < count4; i4++) {
            MultiRecipePayload item4 = default!;
            MultiRecipePayload readValue1004 = new();
            readValue1004.Read(reader);
            item4 = readValue1004;
            MultiRecipes.Add(item4);
        }
        int count6 = checked((int)reader.ReadVarUInt());
        UserDataShapelessRecipes = new List<ShapelessRecipePayload>(count6);
        for (int i6 = 0; i6 < count6; i6++) {
            ShapelessRecipePayload item6 = default!;
            ShapelessRecipePayload readValue1006 = new();
            readValue1006.Read(reader);
            item6 = readValue1006;
            UserDataShapelessRecipes.Add(item6);
        }
        int count8 = checked((int)reader.ReadVarUInt());
        ShapelessChemistryRecipes = new List<ShapelessRecipePayload>(count8);
        for (int i8 = 0; i8 < count8; i8++) {
            ShapelessRecipePayload item8 = default!;
            ShapelessRecipePayload readValue1008 = new();
            readValue1008.Read(reader);
            item8 = readValue1008;
            ShapelessChemistryRecipes.Add(item8);
        }
        int count10 = checked((int)reader.ReadVarUInt());
        ShapedChemistryRecipes = new List<ShapedRecipePayload>(count10);
        for (int i10 = 0; i10 < count10; i10++) {
            ShapedRecipePayload item10 = default!;
            ShapedRecipePayload readValue1010 = new();
            readValue1010.Read(reader);
            item10 = readValue1010;
            ShapedChemistryRecipes.Add(item10);
        }
        int count12 = checked((int)reader.ReadVarUInt());
        SmithingTransformRecipes = new List<SmithingTransformRecipePayload>(count12);
        for (int i12 = 0; i12 < count12; i12++) {
            SmithingTransformRecipePayload item12 = default!;
            SmithingTransformRecipePayload readValue1012 = new();
            readValue1012.Read(reader);
            item12 = readValue1012;
            SmithingTransformRecipes.Add(item12);
        }
        int count14 = checked((int)reader.ReadVarUInt());
        SmithingTrimRecipes = new List<SmithingTrimRecipePayload>(count14);
        for (int i14 = 0; i14 < count14; i14++) {
            SmithingTrimRecipePayload item14 = default!;
            SmithingTrimRecipePayload readValue1014 = new();
            readValue1014.Read(reader);
            item14 = readValue1014;
            SmithingTrimRecipes.Add(item14);
        }
        int count16 = checked((int)reader.ReadVarUInt());
        PotionMixes = new List<PotionMixDataEntry>(count16);
        for (int i16 = 0; i16 < count16; i16++) {
            PotionMixDataEntry item16 = default!;
            PotionMixDataEntry readValue1016 = new();
            readValue1016.Read(reader);
            item16 = readValue1016;
            PotionMixes.Add(item16);
        }
        int count18 = checked((int)reader.ReadVarUInt());
        ContainerMixes = new List<ContainerMixDataEntry>(count18);
        for (int i18 = 0; i18 < count18; i18++) {
            ContainerMixDataEntry item18 = default!;
            ContainerMixDataEntry readValue1018 = new();
            readValue1018.Read(reader);
            item18 = readValue1018;
            ContainerMixes.Add(item18);
        }
        int count20 = checked((int)reader.ReadVarUInt());
        MaterialReducers = new List<MaterialReducerDataEntry>(count20);
        for (int i20 = 0; i20 < count20; i20++) {
            MaterialReducerDataEntry item20 = default!;
            MaterialReducerDataEntry readValue1020 = new();
            readValue1020.Read(reader);
            item20 = readValue1020;
            MaterialReducers.Add(item20);
        }
        ClearRecipes = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ShapedRecipes.Count));
        foreach (var item1 in ShapedRecipes) {
            item1.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)ShapelessRecipes.Count));
        foreach (var item3 in ShapelessRecipes) {
            item3.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)MultiRecipes.Count));
        foreach (var item5 in MultiRecipes) {
            item5.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)UserDataShapelessRecipes.Count));
        foreach (var item7 in UserDataShapelessRecipes) {
            item7.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)ShapelessChemistryRecipes.Count));
        foreach (var item9 in ShapelessChemistryRecipes) {
            item9.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)ShapedChemistryRecipes.Count));
        foreach (var item11 in ShapedChemistryRecipes) {
            item11.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)SmithingTransformRecipes.Count));
        foreach (var item13 in SmithingTransformRecipes) {
            item13.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)SmithingTrimRecipes.Count));
        foreach (var item15 in SmithingTrimRecipes) {
            item15.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)PotionMixes.Count));
        foreach (var item17 in PotionMixes) {
            item17.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)ContainerMixes.Count));
        foreach (var item19 in ContainerMixes) {
            item19.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)MaterialReducers.Count));
        foreach (var item21 in MaterialReducers) {
            item21.Write(writer);
        }
        writer.WriteBool(ClearRecipes);
    }
}
