// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Creative Content
/// </summary>
public sealed class CreativeContentPacket : Packet {
    public const int PacketId = 145;

    public List<CreativeGroupInfoPayload> Groups = [];
    public List<CreativeItemEntryPayload> Entries = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Groups = new List<CreativeGroupInfoPayload>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            CreativeGroupInfoPayload item0 = default!;
            CreativeGroupInfoPayload readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            Groups.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        Entries = new List<CreativeItemEntryPayload>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            CreativeItemEntryPayload item2 = default!;
            CreativeItemEntryPayload readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            Entries.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Groups.Count));
        foreach (var item1 in Groups) {
            item1.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)Entries.Count));
        foreach (var item3 in Entries) {
            item3.Write(writer);
        }
    }
}
