// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Players now have the possibility to export photos from their portfolios into photo items in their inventory. EDU.
/// </summary>
public sealed class CreatePhotoPacket : Packet {
    public const int PacketId = 171;

    public ulong RawID;
    public string PhotoName = string.Empty;
    public string PhotoItemName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        RawID = reader.ReadUInt64(true);
        PhotoName = reader.ReadVarString();
        PhotoItemName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt64(RawID, true);
        writer.WriteVarString(PhotoName);
        writer.WriteVarString(PhotoItemName);
    }
}
