// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Informs the client of which Structure Feature they are currently occupying.
/// </summary>
public sealed class CurrentStructureFeaturePacket : Packet {
    public const int PacketId = 314;

    public string CurrentStructureFeature = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        CurrentStructureFeature = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(CurrentStructureFeature);
    }
}
