// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to client when player dies (Level::onPlayerDeath).
/// </summary>
public sealed class DeathInfoPacket : Packet {
    public const int PacketId = 189;

    public DeathCauseMessageType DeathCauseMessage = new();

    public override void Deserialize(BinaryReader reader) {
        DeathCauseMessage.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        DeathCauseMessage.Write(writer);
    }
}
