// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The system sends debug information via a generic network packet. This enables rendering of any server information on the client in for instance ImGui.
/// </summary>
public sealed class DebugInfoPacket : Packet {
    public const int PacketId = 155;

    public ActorUniqueID ActorId = new();
    public string Data = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        ActorId.Read(reader);
        Data = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        ActorId.Write(writer);
        writer.WriteVarString(Data);
    }
}
