// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Brief packet containing data-driven dimension properties
/// </summary>
public sealed class DimensionDataPacket : Packet {
    public const int PacketId = 180;

    public Dictionary<string, DimensionDefinition> Definitions = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Definitions = new Dictionary<string, DimensionDefinition>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            string key0 = default!;
            key0 = reader.ReadVarString();
            DimensionDefinition value0 = default!;
            DimensionDefinition readValue2000 = new();
            readValue2000.Read(reader);
            value0 = readValue2000;
            Definitions.Add(key0, value0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Definitions.Count));
        foreach (var pair1 in Definitions) {
            writer.WriteVarString(pair1.Key);
            pair1.Value.Write(writer);
        }
    }
}
