// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to a client to trigger a disconnection.
/// </summary>
public sealed class DisconnectPacket : Packet {
    public const int PacketId = 5;

    public DisconnectFailReason Reason;
    public DisconnectPacketMessages? Messages;

    public override void Deserialize(BinaryReader reader) {
        Reason = (global::BedrockProtocol.Enums.DisconnectFailReason)reader.ReadZigZag();
        if (!reader.ReadBool()) {
            DisconnectPacketMessages readValue2 = new();
            readValue2.Read(reader);
            Messages = readValue2;
        } else {
            Messages = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)Reason);
        writer.WriteBool(Messages is null);
        if (Messages is { } optionalValue3) {
            optionalValue3.Write(writer);
        }
    }
}
