// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to a client to trigger a disconnection.
/// </summary>
public sealed class DisconnectPacket : Packet {
    public const int PacketId = 5;

    public DisconnectFailReason Reason;
    public DisconnectPacketMessages? Messages;

    public override void Deserialize(BinaryReader reader) {
        Reason = (global::BedrockProtocol.Enums.DisconnectFailReason)reader.ReadZigZag();
        if (reader.ReadBool()) {
            uint variant2 = reader.ReadVarUInt();
            switch (variant2) {
                case 0:
                    DisconnectPacketMessages readValue3002 = new();
                    readValue3002.Read(reader);
                    Messages = readValue3002;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant2} for Messages.");
            }
        } else {
            Messages = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)Reason);
        writer.WriteBool(Messages is not null);
        if (Messages is { } optionalValue3) {
            switch (optionalValue3) {
                case DisconnectPacketMessages variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for optionalValue3.");
            }
        }
    }
}
