// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// General use Editor specific packet - carries a payload of whatever serialized data that the individual IEditorNetworkPayload generates.
/// </summary>
public sealed class EditorNetworkPacket : Packet {
    public const int PacketId = 190;

    public bool RouteToManager;
    public string RawVariantName = string.Empty;
    public string RawVariantData = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        RouteToManager = reader.ReadBool();
        RawVariantName = reader.ReadVarString();
        RawVariantData = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(RouteToManager);
        writer.WriteVarString(RawVariantName);
        writer.WriteVarString(RawVariantData);
    }
}
