// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Transmits EducationLevelSettings to all clients.
/// </summary>
public sealed class EducationSettingsPacket : Packet {
    public const int PacketId = 137;

    public EducationLevelSettings EducationLevelSettings = new();

    public override void Deserialize(BinaryReader reader) {
        EducationLevelSettings.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        EducationLevelSettings.Write(writer);
    }
}
