// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Transmits Edu Shared Uri Resource settings to all clients.
/// </summary>
public sealed class EduUriResourcePacket : Packet {
    public const int PacketId = 170;

    public EduSharedUriResource EduSharedURIResource = new();

    public override void Deserialize(BinaryReader reader) {
        EduSharedURIResource.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        EduSharedURIResource.Write(writer);
    }
}
