// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Allows clients to download emotes that other clients have equipped.
/// </summary>
public sealed class EmoteListPacket : Packet {
    public const int PacketId = 152;

    public ActorRuntimeID RuntimeId = new();
    public List<UUID> EmotePieceIds = [];

    public override void Deserialize(BinaryReader reader) {
        RuntimeId.Read(reader);
        int count2 = checked((int)reader.ReadVarUInt());
        EmotePieceIds = new List<UUID>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            UUID item2 = default!;
            UUID readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            EmotePieceIds.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        RuntimeId.Write(writer);
        writer.WriteVarUInt(checked((uint)EmotePieceIds.Count));
        foreach (var item3 in EmotePieceIds) {
            item3.Write(writer);
        }
    }
}
