// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// A client sends this to the server to notify other clients about the emote.
/// </summary>
public sealed class EmotePacket : Packet {
    public const int PacketId = 138;

    public ActorRuntimeID ActorRuntimeId = new();
    public string EmoteId = string.Empty;
    public uint EmoteLengthTicks;
    public string Xuid = string.Empty;
    public string PlatformId = string.Empty;
    public byte Flags;

    public override void Deserialize(BinaryReader reader) {
        ActorRuntimeId.Read(reader);
        EmoteId = reader.ReadVarString();
        EmoteLengthTicks = reader.ReadVarUInt();
        Xuid = reader.ReadVarString();
        PlatformId = reader.ReadVarString();
        Flags = reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        ActorRuntimeId.Write(writer);
        writer.WriteVarString(EmoteId);
        writer.WriteVarUInt(EmoteLengthTicks);
        writer.WriteVarString(Xuid);
        writer.WriteVarString(PlatformId);
        writer.WriteUInt8(Flags);
    }
}
