// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is the packet that tracks the active feature registry data from the server so that client can place the features themselves.
/// </summary>
public sealed class FeatureRegistryPacket : Packet {
    public const int PacketId = 191;

    public List<FeatureBinaryJsonFormat> FeaturesDataList = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        FeaturesDataList = new List<FeatureBinaryJsonFormat>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            FeatureBinaryJsonFormat item0 = default!;
            FeatureBinaryJsonFormat readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            FeaturesDataList.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)FeaturesDataList.Count));
        foreach (var item1 in FeaturesDataList) {
            item1.Write(writer);
        }
    }
}
