// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Game Test Results Packet
/// </summary>
public sealed class GameTestResultsPacket : Packet {
    public const int PacketId = 195;

    public bool Succeeded;
    public string Error = string.Empty;
    public string TestName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        Succeeded = reader.ReadBool();
        Error = reader.ReadVarString();
        TestName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(Succeeded);
        writer.WriteVarString(Error);
        writer.WriteVarString(TestName);
    }
}
