// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Internal Text Packet
/// </summary>
public sealed class GameTestRequestPacket : Packet {
    public const int PacketId = 194;

    public int MaxTestsPerBatch;
    public int RepeatCount;
    public Rotation Rotation;
    public bool StopOnFailure;
    public BlockPos TestPos = new();
    public int TestsPerRow;
    public string TestName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        MaxTestsPerBatch = reader.ReadZigZag();
        RepeatCount = reader.ReadZigZag();
        Rotation = (global::BedrockProtocol.Enums.Rotation)reader.ReadUInt8();
        StopOnFailure = reader.ReadBool();
        TestPos.Read(reader);
        TestsPerRow = reader.ReadZigZag();
        TestName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(MaxTestsPerBatch);
        writer.WriteZigZag(RepeatCount);
        writer.WriteUInt8((byte)Rotation);
        writer.WriteBool(StopOnFailure);
        TestPos.Write(writer);
        writer.WriteZigZag(TestsPerRow);
        writer.WriteVarString(TestName);
    }
}
