// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to the client when a server script changes the rendering settings
/// </summary>
public sealed class GraphicsOverrideParameterPacket : Packet {
    public const int PacketId = 331;

    public Dictionary<float, Vec3> ParameterKeyframeValues = [];
    public float FloatValue;
    public Vec3 Vec3Value = new();
    public string BiomeIdentifier = string.Empty;
    public string? PlayerIdentifier;
    public GraphicsOverrideParameterType IdentifierForParameter;
    public bool ResetParameter;

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ParameterKeyframeValues = new Dictionary<float, Vec3>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            float key0 = default!;
            key0 = reader.ReadF32(true);
            Vec3 value0 = default!;
            Vec3 readValue2000 = new();
            readValue2000.Read(reader);
            value0 = readValue2000;
            ParameterKeyframeValues.Add(key0, value0);
        }
        FloatValue = reader.ReadF32(true);
        Vec3Value.Read(reader);
        BiomeIdentifier = reader.ReadVarString();
        if (reader.ReadBool()) {
            PlayerIdentifier = reader.ReadVarString();
        } else {
            PlayerIdentifier = default;
        }
        IdentifierForParameter = (global::BedrockProtocol.Enums.GraphicsOverrideParameterType)reader.ReadUInt8();
        ResetParameter = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ParameterKeyframeValues.Count));
        foreach (var pair1 in ParameterKeyframeValues) {
            writer.WriteF32(pair1.Key, true);
            pair1.Value.Write(writer);
        }
        writer.WriteF32(FloatValue, true);
        Vec3Value.Write(writer);
        writer.WriteVarString(BiomeIdentifier);
        writer.WriteBool(PlayerIdentifier is not null);
        if (PlayerIdentifier is { } optionalValue9) {
            writer.WriteVarString(optionalValue9);
        }
        writer.WriteUInt8((byte)IdentifierForParameter);
        writer.WriteBool(ResetParameter);
    }
}
