// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The server telling the client what item slot to hover over in the hotbar.
/// </summary>
public sealed class GuiDataPickItemPacket : Packet {
    public const int PacketId = 54;

    public string ItemName = string.Empty;
    public string ItemEffectName = string.Empty;
    public int Slot;

    public override void Deserialize(BinaryReader reader) {
        ItemName = reader.ReadVarString();
        ItemEffectName = reader.ReadVarString();
        Slot = reader.ReadInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ItemName);
        writer.WriteVarString(ItemEffectName);
        writer.WriteInt32(Slot, true);
    }
}
