// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Hurt Armor
/// </summary>
public sealed class HurtArmorPacket : Packet {
    public const int PacketId = 38;

    public int Cause;
    public int Damage;
    public ulong ArmorSlots;

    public override void Deserialize(BinaryReader reader) {
        Cause = reader.ReadZigZag();
        Damage = reader.ReadZigZag();
        ArmorSlots = reader.ReadVarULong();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(Cause);
        writer.WriteZigZag(Damage);
        writer.WriteVarULong(ArmorSlots);
    }
}
