// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Interact
/// </summary>
public sealed class InteractPacket : Packet {
    public const int PacketId = 33;

    public InteractPacketPayloadAction Action;
    public ActorRuntimeID TargetRuntimeID = new();
    public Vec3? Position;

    public override void Deserialize(BinaryReader reader) {
        Action = (global::BedrockProtocol.Enums.InteractPacketPayloadAction)reader.ReadUInt8();
        TargetRuntimeID.Read(reader);
        if (reader.ReadBool()) {
            Vec3 readValue4 = new();
            readValue4.Read(reader);
            Position = readValue4;
        } else {
            Position = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Action);
        TargetRuntimeID.Write(writer);
        writer.WriteBool(Position is not null);
        if (Position is { } optionalValue5) {
            optionalValue5.Write(writer);
        }
    }
}
