// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Inventory Transaction. Sent for item interaction UI depending on if ItemStackNetManager is enabled as well as when the player uses items in gameplay. See ComplexInventoryTransaction::Type for more details.
/// </summary>
public sealed class InventoryTransactionPacket : Packet {
    public const int PacketId = 30;

    public ItemStackLegacyRequestId LegacyRequestID = new();
    public List<LegacySetSlot>? LegacySetItemSlots;
    public InventoryTransactionVariant Transaction = null!;
    public InventoryTransaction Actions = new();

    public override void Deserialize(BinaryReader reader) {
        LegacyRequestID.Read(reader);
        if (reader.ReadBool()) {
            int count2 = checked((int)reader.ReadVarUInt());
            LegacySetItemSlots = new List<LegacySetSlot>(count2);
            for (int i2 = 0; i2 < count2; i2++) {
                LegacySetSlot item2 = default!;
                LegacySetSlot readValue1002 = new();
                readValue1002.Read(reader);
                item2 = readValue1002;
                LegacySetItemSlots.Add(item2);
            }
        } else {
            LegacySetItemSlots = default;
        }
        if (!reader.ReadBool()) throw new FormatException("Transaction is missing.");
        uint variant4 = reader.ReadVarUInt();
        if (!reader.ReadBool()) throw new FormatException("Actions is missing.");
        Actions.Read(reader);
        switch (variant4) {
            case 0:
                NormalTransactionData variantValue0 = new();
                variantValue0.Read(reader);
                variantValue0.Actions = Actions;
                Transaction = variantValue0;
                break;
            case 1:
                InventoryMismatchData variantValue1 = new();
                variantValue1.Read(reader);
                variantValue1.Actions = Actions;
                Transaction = variantValue1;
                break;
            case 2:
                ItemUseInventoryTransaction variantValue2 = new();
                variantValue2.Read(reader);
                variantValue2.Actions = Actions;
                Transaction = variantValue2;
                break;
            case 3:
                ItemUseOnActorInventoryTransaction variantValue3 = new();
                variantValue3.Read(reader);
                variantValue3.Actions = Actions;
                Transaction = variantValue3;
                break;
            case 4:
                ItemReleaseInventoryTransaction variantValue4 = new();
                variantValue4.Read(reader);
                variantValue4.Actions = Actions;
                Transaction = variantValue4;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant4} for Transaction.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        LegacyRequestID.Write(writer);
        writer.WriteBool(LegacySetItemSlots is not null);
        if (LegacySetItemSlots is { } optionalValue3) {
            writer.WriteVarUInt(checked((uint)optionalValue3.Count));
            foreach (var item3 in optionalValue3) {
                item3.Write(writer);
            }
        }
        writer.WriteBool(true);
        switch (Transaction) {
            case NormalTransactionData variantValue0:
                writer.WriteVarUInt(0);
                writer.WriteBool(true);
                variantValue0.Actions.Write(writer);
                variantValue0.Write(writer);
                break;
            case InventoryMismatchData variantValue1:
                writer.WriteVarUInt(1);
                writer.WriteBool(true);
                variantValue1.Actions.Write(writer);
                variantValue1.Write(writer);
                break;
            case ItemUseInventoryTransaction variantValue2:
                writer.WriteVarUInt(2);
                writer.WriteBool(true);
                variantValue2.Actions.Write(writer);
                variantValue2.Write(writer);
                break;
            case ItemUseOnActorInventoryTransaction variantValue3:
                writer.WriteVarUInt(3);
                writer.WriteBool(true);
                variantValue3.Actions.Write(writer);
                variantValue3.Write(writer);
                break;
            case ItemReleaseInventoryTransaction variantValue4:
                writer.WriteVarUInt(4);
                writer.WriteBool(true);
                variantValue4.Actions.Write(writer);
                variantValue4.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Transaction.");
        }
    }
}
