// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Updates one slot in an inventory rather than the whole thing. So like animal inventory (horses, donkeys, etc) and chests. Hotbar, offhand, and some player inventory changes.
/// </summary>
public sealed class InventorySlotPacket : Packet {
    public const int PacketId = 50;

    public byte ContainerId;
    public uint Slot;
    public FullContainerName? FullContainerName;
    public NetworkItemStackDescriptor? StorageItem;
    public NetworkItemStackDescriptor Item = new();

    public override void Deserialize(BinaryReader reader) {
        ContainerId = reader.ReadUInt8();
        Slot = reader.ReadVarUInt();
        if (reader.ReadBool()) {
            FullContainerName readValue4 = new();
            readValue4.Read(reader);
            FullContainerName = readValue4;
        } else {
            FullContainerName = default;
        }
        if (reader.ReadBool()) {
            NetworkItemStackDescriptor readValue6 = new();
            readValue6.Read(reader);
            StorageItem = readValue6;
        } else {
            StorageItem = default;
        }
        Item.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(ContainerId);
        writer.WriteVarUInt(Slot);
        writer.WriteBool(FullContainerName is not null);
        if (FullContainerName is { } optionalValue5) {
            optionalValue5.Write(writer);
        }
        writer.WriteBool(StorageItem is not null);
        if (StorageItem is { } optionalValue7) {
            optionalValue7.Write(writer);
        }
        Item.Write(writer);
    }
}
