// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used for updating an entire container. Example uses include: player respawned, replace items command, 3rd party content calls sendInventory(), block picking.
/// </summary>
public sealed class InventoryContentPacket : Packet {
    public const int PacketId = 49;

    public uint ContainerId;
    public List<NetworkItemStackDescriptor> Slots = [];
    public FullContainerName FullContainerName = new();
    public NetworkItemStackDescriptor StorageItem = new();

    public override void Deserialize(BinaryReader reader) {
        ContainerId = reader.ReadVarUInt();
        int count2 = checked((int)reader.ReadVarUInt());
        Slots = new List<NetworkItemStackDescriptor>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            NetworkItemStackDescriptor item2 = default!;
            NetworkItemStackDescriptor readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            Slots.Add(item2);
        }
        FullContainerName.Read(reader);
        StorageItem.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(ContainerId);
        writer.WriteVarUInt(checked((uint)Slots.Count));
        foreach (var item3 in Slots) {
            item3.Write(writer);
        }
        FullContainerName.Write(writer);
        StorageItem.Write(writer);
    }
}
