// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Server auth inventory item transaction response, sent from the server.
/// </summary>
public sealed class ItemStackResponsePacket : Packet {
    public const int PacketId = 148;

    public List<ItemStackResponseInfo> Responses = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Responses = new List<ItemStackResponseInfo>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ItemStackResponseInfo item0 = default!;
            ItemStackResponseInfo readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            Responses.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Responses.Count));
        foreach (var item1 in Responses) {
            item1.Write(writer);
        }
    }
}
