// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The new server auth inventory item transaction request. This is done in batches of items.
/// </summary>
public sealed class ItemStackRequestPacket : Packet {
    public const int PacketId = 147;

    public List<ItemStackRequest> Requests = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Requests = new List<ItemStackRequest>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ItemStackRequest item0 = default!;
            ItemStackRequest readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            Requests.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Requests.Count));
        foreach (var item1 in Requests) {
            item1.Write(writer);
        }
    }
}
