// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Item data from the server. Contains component information.
/// </summary>
public sealed class ItemRegistryPacket : Packet {
    public const int PacketId = 162;

    public List<ItemData> ItemData = [];

    public ItemData.ItemComponentDataReader? ReadItemComponentData { get; set; }
    public ItemData.ItemComponentDataWriter? WriteItemComponentData { get; set; }

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ItemData = new List<ItemData>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ItemData item0 = default!;
            ItemData readValue1000 = new();
            readValue1000.Read(reader, (ReadItemComponentData ?? throw new InvalidOperationException("ItemRegistryPacket.ReadItemComponentData must be configured before deserialization.")));
            item0 = readValue1000;
            ItemData.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ItemData.Count));
        foreach (var item1 in ItemData) {
            item1.Write(writer, (WriteItemComponentData ?? throw new InvalidOperationException("ItemRegistryPacket.WriteItemComponentData must be configured before serialization.")));
        }
    }
}
