// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Jigsaw Structure data used by client jigsaw structure worldgen. This packet contains a copy of the behavior pack jigsaw structure rules.
/// </summary>
public sealed class JigsawStructureDataPacket : Packet {
    public const int PacketId = 313;

    public object JigsawStructureDataTag = null!;

    public delegate object JigsawStructureDataTagReader(BinaryReader reader);
    public delegate void JigsawStructureDataTagWriter(BinaryWriter writer, object value);
    public JigsawStructureDataTagReader? ReadJigsawStructureDataTag { get; set; }
    public JigsawStructureDataTagWriter? WriteJigsawStructureDataTag { get; set; }

    public override void Deserialize(BinaryReader reader) {
        JigsawStructureDataTag = (ReadJigsawStructureDataTag ?? throw new InvalidOperationException("JigsawStructureDataPacket.ReadJigsawStructureDataTag must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        (WriteJigsawStructureDataTag ?? throw new InvalidOperationException("JigsawStructureDataPacket.WriteJigsawStructureDataTag must be configured before serialization."))(writer, JigsawStructureDataTag);
    }
}
