// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// For the EDU Chemistry Lab Table block actor.
/// </summary>
public sealed class LabTablePacket : Packet {
    public const int PacketId = 109;

    public LabTablePacketPayloadType Type = new();
    public BlockPos Position = new();
    public LabTableReactionType Reaction;

    public override void Deserialize(BinaryReader reader) {
        Type = (LabTablePacketPayloadType)reader.ReadUInt8();
        Position.Read(reader);
        Reaction = (global::BedrockProtocol.Enums.LabTableReactionType)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Type);
        Position.Write(writer);
        writer.WriteUInt8((byte)Reaction);
    }
}
