// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used for the Lectern Block Actor.
/// </summary>
public sealed class LecternUpdatePacket : Packet {
    public const int PacketId = 125;

    public byte NewPageToShow;
    public byte TotalPages;
    public BlockPos PositionOfLecternToUpdate = new();

    public override void Deserialize(BinaryReader reader) {
        NewPageToShow = reader.ReadUInt8();
        TotalPages = reader.ReadUInt8();
        PositionOfLecternToUpdate.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(NewPageToShow);
        writer.WriteUInt8(TotalPages);
        PositionOfLecternToUpdate.Write(writer);
    }
}
