// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends telemetry events to the client so the client can then send that on to the eventing system
/// </summary>
public sealed class LegacyTelemetryEventPacket : Packet {
    public const int PacketId = 65;

    public ActorUniqueID TargetActorID = new();
    public LegacyTelemetryEventPacketPayloadType EventType = new();
    public bool UsePlayerID;
    public LegacyTelemetryEventEventDataVariant EventData = null!;

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
        EventType = (LegacyTelemetryEventPacketPayloadType)reader.ReadZigZag();
        UsePlayerID = reader.ReadBool();
        uint variant6 = reader.ReadVarUInt();
        switch (variant6) {
            case 0:
                Achievement readValue3006 = new();
                readValue3006.Read(reader);
                EventData = readValue3006;
                break;
            case 1:
                Interaction readValue3007 = new();
                readValue3007.Read(reader);
                EventData = readValue3007;
                break;
            case 2:
                PortalCreated readValue3008 = new();
                readValue3008.Read(reader);
                EventData = readValue3008;
                break;
            case 3:
                PortalUsed readValue3009 = new();
                readValue3009.Read(reader);
                EventData = readValue3009;
                break;
            case 4:
                MobKilled readValue3010 = new();
                readValue3010.Read(reader);
                EventData = readValue3010;
                break;
            case 5:
                CauldronUsed readValue3011 = new();
                readValue3011.Read(reader);
                EventData = readValue3011;
                break;
            case 6:
                PlayerDied readValue3012 = new();
                readValue3012.Read(reader);
                EventData = readValue3012;
                break;
            case 7:
                BossKilled readValue3013 = new();
                readValue3013.Read(reader);
                EventData = readValue3013;
                break;
            case 8:
                SlashCommand readValue3014 = new();
                readValue3014.Read(reader);
                EventData = readValue3014;
                break;
            case 9:
                MobBorn readValue3015 = new();
                readValue3015.Read(reader);
                EventData = readValue3015;
                break;
            case 10:
                POICauldronUsed readValue3016 = new();
                readValue3016.Read(reader);
                EventData = readValue3016;
                break;
            case 11:
                ComposterUsed readValue3017 = new();
                readValue3017.Read(reader);
                EventData = readValue3017;
                break;
            case 12:
                BellUsed readValue3018 = new();
                readValue3018.Read(reader);
                EventData = readValue3018;
                break;
            case 13:
                ActorDefinition readValue3019 = new();
                readValue3019.Read(reader);
                EventData = readValue3019;
                break;
            case 14:
                RaidUpdate readValue3020 = new();
                readValue3020.Read(reader);
                EventData = readValue3020;
                break;
            case 15:
                TargetBlockHit readValue3021 = new();
                readValue3021.Read(reader);
                EventData = readValue3021;
                break;
            case 16:
                PiglinBarter readValue3022 = new();
                readValue3022.Read(reader);
                EventData = readValue3022;
                break;
            case 17:
                PlayerWaxedOrUnwaxedCopper readValue3023 = new();
                readValue3023.Read(reader);
                EventData = readValue3023;
                break;
            case 18:
                CodeBuilderRuntimeAction readValue3024 = new();
                readValue3024.Read(reader);
                EventData = readValue3024;
                break;
            case 19:
                CodeBuilderScoreboard readValue3025 = new();
                readValue3025.Read(reader);
                EventData = readValue3025;
                break;
            case 20:
                ItemUsed readValue3026 = new();
                readValue3026.Read(reader);
                EventData = readValue3026;
                break;
            case 21:
                Empty readValue3027 = new();
                readValue3027.Read(reader);
                EventData = readValue3027;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant6} for EventData.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
        writer.WriteZigZag((int)EventType);
        writer.WriteBool(UsePlayerID);
        switch (EventData) {
            case Achievement variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case Interaction variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            case PortalCreated variantValue2:
                writer.WriteVarUInt(2);
                variantValue2.Write(writer);
                break;
            case PortalUsed variantValue3:
                writer.WriteVarUInt(3);
                variantValue3.Write(writer);
                break;
            case MobKilled variantValue4:
                writer.WriteVarUInt(4);
                variantValue4.Write(writer);
                break;
            case CauldronUsed variantValue5:
                writer.WriteVarUInt(5);
                variantValue5.Write(writer);
                break;
            case PlayerDied variantValue6:
                writer.WriteVarUInt(6);
                variantValue6.Write(writer);
                break;
            case BossKilled variantValue7:
                writer.WriteVarUInt(7);
                variantValue7.Write(writer);
                break;
            case SlashCommand variantValue8:
                writer.WriteVarUInt(8);
                variantValue8.Write(writer);
                break;
            case MobBorn variantValue9:
                writer.WriteVarUInt(9);
                variantValue9.Write(writer);
                break;
            case POICauldronUsed variantValue10:
                writer.WriteVarUInt(10);
                variantValue10.Write(writer);
                break;
            case ComposterUsed variantValue11:
                writer.WriteVarUInt(11);
                variantValue11.Write(writer);
                break;
            case BellUsed variantValue12:
                writer.WriteVarUInt(12);
                variantValue12.Write(writer);
                break;
            case ActorDefinition variantValue13:
                writer.WriteVarUInt(13);
                variantValue13.Write(writer);
                break;
            case RaidUpdate variantValue14:
                writer.WriteVarUInt(14);
                variantValue14.Write(writer);
                break;
            case TargetBlockHit variantValue15:
                writer.WriteVarUInt(15);
                variantValue15.Write(writer);
                break;
            case PiglinBarter variantValue16:
                writer.WriteVarUInt(16);
                variantValue16.Write(writer);
                break;
            case PlayerWaxedOrUnwaxedCopper variantValue17:
                writer.WriteVarUInt(17);
                variantValue17.Write(writer);
                break;
            case CodeBuilderRuntimeAction variantValue18:
                writer.WriteVarUInt(18);
                variantValue18.Write(writer);
                break;
            case CodeBuilderScoreboard variantValue19:
                writer.WriteVarUInt(19);
                variantValue19.Write(writer);
                break;
            case ItemUsed variantValue20:
                writer.WriteVarUInt(20);
                variantValue20.Write(writer);
                break;
            case Empty variantValue21:
                writer.WriteVarUInt(21);
                variantValue21.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for EventData.");
        }
    }
}
