// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Lesson Progress
/// </summary>
public sealed class LessonProgressPacket : Packet {
    public const int PacketId = 183;

    public int LessonAction;
    public int Score;
    public string ActivityId = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        LessonAction = reader.ReadZigZag();
        Score = reader.ReadZigZag();
        ActivityId = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(LessonAction);
        writer.WriteZigZag(Score);
        writer.WriteVarString(ActivityId);
    }
}
