// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Splash Potions, weather events, global pause, simlock commands, oh my!
/// </summary>
public sealed class LevelEventPacket : Packet {
    public const int PacketId = 25;

    public int EventId;
    public Vec3 Position = new();
    public int Data;

    public override void Deserialize(BinaryReader reader) {
        EventId = reader.ReadZigZag();
        Position.Read(reader);
        Data = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(EventId);
        Position.Write(writer);
        writer.WriteZigZag(Data);
    }
}
