// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Level Sound Event
/// </summary>
public sealed class LevelSoundEventPacket : Packet {
    public const int PacketId = 123;

    public string SoundEvent = string.Empty;
    public Vec3 Position = new();
    public int Data;
    public string ActorIdentifier = string.Empty;
    public bool IsBaby;
    public bool IsGlobal;
    public long ActorUniqueId;
    public Vec3? FireAtPosition;

    public override void Deserialize(BinaryReader reader) {
        SoundEvent = reader.ReadVarString();
        Position.Read(reader);
        Data = reader.ReadZigZag();
        ActorIdentifier = reader.ReadVarString();
        IsBaby = reader.ReadBool();
        IsGlobal = reader.ReadBool();
        ActorUniqueId = reader.ReadInt64(true);
        if (reader.ReadBool()) {
            Vec3 readValue14 = new();
            readValue14.Read(reader);
            FireAtPosition = readValue14;
        } else {
            FireAtPosition = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(SoundEvent);
        Position.Write(writer);
        writer.WriteZigZag(Data);
        writer.WriteVarString(ActorIdentifier);
        writer.WriteBool(IsBaby);
        writer.WriteBool(IsGlobal);
        writer.WriteInt64(ActorUniqueId, true);
        writer.WriteBool(FireAtPosition is not null);
        if (FireAtPosition is { } optionalValue15) {
            optionalValue15.Write(writer);
        }
    }
}
