// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Level Chunk Packet
/// </summary>
public sealed class LevelChunkPacket : Packet {
    public const int PacketId = 58;

    public ChunkPos ChunkPosition = new();
    public DimensionType DimensionId = new();
    public uint SubChunksCount;
    public int? ClientRequestSubChunkLimit;
    public bool CacheEnabled;
    public List<LevelChunkPacketPayloadSubChunkMetadata> CacheMetadata = [];
    public byte[] SerializedChunkData = [];

    public override void Deserialize(BinaryReader reader) {
        ChunkPosition.Read(reader);
        DimensionId.Read(reader);
        SubChunksCount = reader.ReadVarUInt();
        if (reader.ReadBool()) {
            ClientRequestSubChunkLimit = reader.ReadZigZag();
        } else {
            ClientRequestSubChunkLimit = default;
        }
        CacheEnabled = reader.ReadBool();
        int count10 = checked((int)reader.ReadVarUInt());
        CacheMetadata = new List<LevelChunkPacketPayloadSubChunkMetadata>(count10);
        for (int i10 = 0; i10 < count10; i10++) {
            LevelChunkPacketPayloadSubChunkMetadata item10 = default!;
            LevelChunkPacketPayloadSubChunkMetadata readValue1010 = new();
            readValue1010.Read(reader);
            item10 = readValue1010;
            CacheMetadata.Add(item10);
        }
        int binaryLength12 = checked((int)reader.ReadVarUInt());
        SerializedChunkData = reader.ReadBytes(binaryLength12).ToArray();
    }

    public override void Serialize(BinaryWriter writer) {
        ChunkPosition.Write(writer);
        DimensionId.Write(writer);
        writer.WriteVarUInt(SubChunksCount);
        writer.WriteBool(ClientRequestSubChunkLimit is not null);
        if (ClientRequestSubChunkLimit is { } optionalValue7) {
            writer.WriteZigZag(optionalValue7);
        }
        writer.WriteBool(CacheEnabled);
        writer.WriteVarUInt(checked((uint)CacheMetadata.Count));
        foreach (var item11 in CacheMetadata) {
            item11.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)SerializedChunkData.Length));
        writer.WriteBytes(SerializedChunkData);
    }
}
