// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// LevelEventGenericPacket
/// </summary>
public sealed class LevelEventGenericPacket : Packet {
    public const int PacketId = 124;

    public int EventId;
    public object CTD = null!;

    public delegate object CTDReader(BinaryReader reader);
    public delegate void CTDWriter(BinaryWriter writer, object value);
    public CTDReader? ReadCTD { get; set; }
    public CTDWriter? WriteCTD { get; set; }

    public override void Deserialize(BinaryReader reader) {
        EventId = reader.ReadZigZag();
        CTD = (ReadCTD ?? throw new InvalidOperationException("LevelEventGenericPacket.ReadCTD must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(EventId);
        (WriteCTD ?? throw new InvalidOperationException("LevelEventGenericPacket.WriteCTD must be configured before serialization."))(writer, CTD);
    }
}
