// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Syncs LocatorBar changes on the server with the client.
/// </summary>
public sealed class LocatorBarPacket : Packet {
    public const int PacketId = 341;

    public List<LocatorBarWaypointPayload> Waypoints = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Waypoints = new List<LocatorBarWaypointPayload>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            LocatorBarWaypointPayload item0 = default!;
            LocatorBarWaypointPayload readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            Waypoints.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Waypoints.Count));
        foreach (var item1 in Waypoints) {
            item1.Write(writer);
        }
    }
}
