// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent once from client to server at login. About 100k.
/// </summary>
public sealed class LoginPacket : Packet {
    public const int PacketId = 1;

    public int ClientNetworkVersion;
    public string ConnectionRequest = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        ClientNetworkVersion = reader.ReadInt32(false);
        ConnectionRequest = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt32(ClientNetworkVersion, false);
        writer.WriteVarString(ConnectionRequest);
    }
}
