// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is fired when the user locks a map item utilizing the Cartography Table in game.
/// </summary>
public sealed class MapCreateLockedCopyPacket : Packet {
    public const int PacketId = 131;

    public ActorUniqueID OriginalMapId = new();
    public ActorUniqueID NewMapId = new();

    public override void Deserialize(BinaryReader reader) {
        OriginalMapId.Read(reader);
        NewMapId.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        OriginalMapId.Write(writer);
        NewMapId.Write(writer);
    }
}
