// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// In the case of the client being unable to find map data for a map item it sends a uuid for a map to the server.
/// </summary>
public sealed class MapInfoRequestPacket : Packet {
    public const int PacketId = 68;

    public ActorUniqueID MapUniqueID = new();
    public List<ClientPixelsProxy> ClientPixelsList = [];

    public override void Deserialize(BinaryReader reader) {
        MapUniqueID.Read(reader);
        int count2 = checked((int)reader.ReadUInt32(true));
        ClientPixelsList = new List<ClientPixelsProxy>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            ClientPixelsProxy item2 = default!;
            ClientPixelsProxy readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            ClientPixelsList.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        MapUniqueID.Write(writer);
        writer.WriteUInt32(checked((uint)ClientPixelsList.Count), true);
        foreach (var item3 in ClientPixelsList) {
            item3.Write(writer);
        }
    }
}
