// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Mob Armor Equipment
/// </summary>
public sealed class MobArmorEquipmentPacket : Packet {
    public const int PacketId = 32;

    public ActorRuntimeID TargetRuntimeID = new();
    public NetworkItemStackDescriptor Head = new();
    public NetworkItemStackDescriptor Torso = new();
    public NetworkItemStackDescriptor Legs = new();
    public NetworkItemStackDescriptor Feet = new();
    public NetworkItemStackDescriptor Body = new();

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        Head.Read(reader);
        Torso.Read(reader);
        Legs.Read(reader);
        Feet.Read(reader);
        Body.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        Head.Write(writer);
        Torso.Write(writer);
        Legs.Write(writer);
        Feet.Write(writer);
        Body.Write(writer);
    }
}
