// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Mob Equipment. Changes to any mob's held/offhand item are fired from server to client with this packet. Clients also send this to the server when their held slot or its contents change.
/// </summary>
public sealed class MobEquipmentPacket : Packet {
    public const int PacketId = 31;

    public ActorRuntimeID TargetRuntimeID = new();
    public NetworkItemStackDescriptor Item = new();
    public byte Slot;
    public byte SelectedSlot;
    public byte ContainerID;

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        Item.Read(reader);
        Slot = reader.ReadUInt8();
        SelectedSlot = reader.ReadUInt8();
        ContainerID = reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        Item.Write(writer);
        writer.WriteUInt8(Slot);
        writer.WriteUInt8(SelectedSlot);
        writer.WriteUInt8(ContainerID);
    }
}
