// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Mob Effect
/// </summary>
public sealed class MobEffectPacket : Packet {
    public const int PacketId = 28;

    public ActorRuntimeID TargetRuntimeID = new();
    public Event EventID;
    public int EffectID;
    public int EffectAmplifier;
    public bool ShowParticles;
    public int EffectDurationTicks;
    public PlayerInputTick Tick = new();
    public bool Ambient;

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        EventID = (global::BedrockProtocol.Enums.Event)reader.ReadUInt8();
        EffectID = reader.ReadZigZag();
        EffectAmplifier = reader.ReadZigZag();
        ShowParticles = reader.ReadBool();
        EffectDurationTicks = reader.ReadZigZag();
        Tick.Read(reader);
        Ambient = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        writer.WriteUInt8((byte)EventID);
        writer.WriteZigZag(EffectID);
        writer.WriteZigZag(EffectAmplifier);
        writer.WriteBool(ShowParticles);
        writer.WriteZigZag(EffectDurationTicks);
        Tick.Write(writer);
        writer.WriteBool(Ambient);
    }
}
