// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Modal Form Request
/// </summary>
public sealed class ModalFormRequestPacket : Packet {
    public const int PacketId = 100;

    public uint FormID;
    public string FormUIJSON = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        FormID = reader.ReadVarUInt();
        FormUIJSON = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(FormID);
        writer.WriteVarString(FormUIJSON);
    }
}
