// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Modal Form Request
/// </summary>
public sealed class ModalFormRequestPacket : Packet {
    public const int PacketId = 100;

    public uint FormID;
    public byte[] FormUIJSON = [];

    public override void Deserialize(BinaryReader reader) {
        FormID = reader.ReadVarUInt();
        int binaryLength2 = checked((int)reader.ReadVarUInt());
        FormUIJSON = reader.ReadBytes(binaryLength2).ToArray();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(FormID);
        writer.WriteVarUInt(checked((uint)FormUIJSON.Length));
        writer.WriteBytes(FormUIJSON);
    }
}
