// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Fired in response to third party server request to show the custom UI screen.
/// </summary>
public sealed class ModalFormResponsePacket : Packet {
    public const int PacketId = 101;

    public uint FormID;
    public string JSONResponse = string.Empty;
    public ModalFormCancelReason FormCancelReason;

    public override void Deserialize(BinaryReader reader) {
        FormID = reader.ReadVarUInt();
        JSONResponse = reader.ReadVarString();
        FormCancelReason = (global::BedrockProtocol.Enums.ModalFormCancelReason)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(FormID);
        writer.WriteVarString(JSONResponse);
        writer.WriteUInt8((byte)FormCancelReason);
    }
}
