// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Fired in response to third party server request to show the custom UI screen.
/// </summary>
public sealed class ModalFormResponsePacket : Packet {
    public const int PacketId = 101;

    public uint FormID;
    public byte[]? JSONResponse;
    public ModalFormCancelReason? FormCancelReason;

    public override void Deserialize(BinaryReader reader) {
        FormID = reader.ReadVarUInt();
        if (reader.ReadBool()) {
            int binaryLength2 = checked((int)reader.ReadVarUInt());
            JSONResponse = reader.ReadBytes(binaryLength2).ToArray();
        } else {
            JSONResponse = default;
        }
        if (reader.ReadBool()) {
            FormCancelReason = (global::BedrockProtocol.Enums.ModalFormCancelReason)reader.ReadUInt8();
        } else {
            FormCancelReason = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(FormID);
        writer.WriteBool(JSONResponse is not null);
        if (JSONResponse is { } optionalValue3) {
            writer.WriteVarUInt(checked((uint)optionalValue3.Length));
            writer.WriteBytes(optionalValue3);
        }
        writer.WriteBool(FormCancelReason is not null);
        if (FormCancelReason is { } optionalValue5) {
            writer.WriteUInt8((byte)optionalValue5);
        }
    }
}
