// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// It is essentially a SetActionMotionPacket with a bool indicating if the actor was on the ground at the time the packet is sent or not.
/// </summary>
public sealed class MotionPredictionHintsPacket : Packet {
    public const int PacketId = 157;

    public ActorRuntimeID MRuntimeId = new();
    public Vec3 MMotion = new();
    public bool MOnGround;

    public override void Deserialize(BinaryReader reader) {
        MRuntimeId.Read(reader);
        MMotion.Read(reader);
        MOnGround = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        MRuntimeId.Write(writer);
        MMotion.Write(writer);
        writer.WriteBool(MOnGround);
    }
}
