// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// For client authoritative and server authoritative movement modes, it is only intended as a client-bound packet. It forces the player to a specified position with slightly different behavior depending on the position mode.
/// </summary>
public sealed class MovePlayerPacket : Packet {
    public const int PacketId = 19;

    public ActorRuntimeID PlayerRuntimeID = new();
    public Vec3 Position = new();
    public Vec2 Rotation = new();
    public float YHeadRotation;
    public PositionMode PositionMode;
    public bool OnGround;
    public ActorRuntimeID RidingRuntimeID = new();
    public MovePlayerTeleportData? TeleportData;
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        PlayerRuntimeID.Read(reader);
        Position.Read(reader);
        Rotation.Read(reader);
        YHeadRotation = reader.ReadF32(true);
        PositionMode = (global::BedrockProtocol.Enums.PositionMode)reader.ReadUInt8();
        OnGround = reader.ReadBool();
        RidingRuntimeID.Read(reader);
        if (reader.ReadBool()) {
            MovePlayerTeleportData readValue14 = new();
            readValue14.Read(reader);
            TeleportData = readValue14;
        } else {
            TeleportData = default;
        }
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        PlayerRuntimeID.Write(writer);
        Position.Write(writer);
        Rotation.Write(writer);
        writer.WriteF32(YHeadRotation, true);
        writer.WriteUInt8((byte)PositionMode);
        writer.WriteBool(OnGround);
        RidingRuntimeID.Write(writer);
        writer.WriteBool(TeleportData is not null);
        if (TeleportData is { } optionalValue15) {
            optionalValue15.Write(writer);
        }
        Tick.Write(writer);
    }
}
