// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used primarily for motion updates of all actors from server to client.
/// </summary>
public sealed class MoveActorAbsolutePacket : Packet {
    public const int PacketId = 18;

    public MoveActorAbsoluteData MoveData = new();

    public override void Deserialize(BinaryReader reader) {
        MoveData.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        MoveData.Write(writer);
    }
}
