// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This packet is all the deltas of actors position, rotation, and head rotation. This is used for all actors.
/// </summary>
public sealed class MoveActorDeltaPacket : Packet {
    public const int PacketId = 111;

    public MoveActorDeltaData MoveData = new();

    public override void Deserialize(BinaryReader reader) {
        MoveData.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        MoveData.Write(writer);
    }
}
