// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// These packets are sent to the client to update specific MovementEffects
/// </summary>
public sealed class MovementEffectPacket : Packet {
    public const int PacketId = 318;

    public ActorRuntimeID TargetRuntimeID = new();
    public MovementEffectType EffectID;
    public int EffectDuration;
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        EffectID = (global::BedrockProtocol.Enums.MovementEffectType)reader.ReadZigZag();
        EffectDuration = reader.ReadZigZag();
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        writer.WriteZigZag((int)EffectID);
        writer.WriteZigZag(EffectDuration);
        Tick.Write(writer);
    }
}
