// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Syncs multiplayer settings
/// </summary>
public sealed class MultiplayerSettingsPacket : Packet {
    public const int PacketId = 139;

    public MultiplayerSettingsPacketType PacketType;

    public override void Deserialize(BinaryReader reader) {
        PacketType = (global::BedrockProtocol.Enums.MultiplayerSettingsPacketType)reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)PacketType);
    }
}
