// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Ping Packet
/// </summary>
public sealed class NetworkStackLatencyPacket : Packet {
    public const int PacketId = 115;

    public ulong CreationTime;
    public bool IsFromServer;

    public override void Deserialize(BinaryReader reader) {
        CreationTime = reader.ReadUInt64(true);
        IsFromServer = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt64(CreationTime, true);
        writer.WriteBool(IsFromServer);
    }
}
