// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Tells clients to update the chunk view for the local player.
/// </summary>
public sealed class NetworkChunkPublisherUpdatePacket : Packet {
    public const int PacketId = 121;

    public BlockPos NewPositionForView = new();
    public uint NewRadiusForView;
    public List<ChunkPos> ServerBuiltChunksList = [];

    public override void Deserialize(BinaryReader reader) {
        NewPositionForView.Read(reader);
        NewRadiusForView = reader.ReadVarUInt();
        int count4 = checked((int)reader.ReadUInt32(true));
        ServerBuiltChunksList = new List<ChunkPos>(count4);
        for (int i4 = 0; i4 < count4; i4++) {
            ChunkPos item4 = default!;
            ChunkPos readValue1004 = new();
            readValue1004.Read(reader);
            item4 = readValue1004;
            ServerBuiltChunksList.Add(item4);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        NewPositionForView.Write(writer);
        writer.WriteVarUInt(NewRadiusForView);
        writer.WriteUInt32(checked((uint)ServerBuiltChunksList.Count), true);
        foreach (var item5 in ServerBuiltChunksList) {
            item5.Write(writer);
        }
    }
}
