// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends tunable options from host to client (compression threshold and algorithm)
/// </summary>
public sealed class NetworkSettingsPacket : Packet {
    public const int PacketId = 143;

    public ushort CompressionThreshold;
    public PacketCompressionAlgorithm CompressionAlgorithm;
    public bool ClientThrottleEnabled;
    public byte ClientThrottleThreshold;
    public float ClientThrottleScalar;

    public override void Deserialize(BinaryReader reader) {
        CompressionThreshold = reader.ReadUInt16(true);
        CompressionAlgorithm = (global::BedrockProtocol.Enums.PacketCompressionAlgorithm)reader.ReadUInt16(true);
        ClientThrottleEnabled = reader.ReadBool();
        ClientThrottleThreshold = reader.ReadUInt8();
        ClientThrottleScalar = reader.ReadF32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt16(CompressionThreshold, true);
        writer.WriteUInt16((ushort)CompressionAlgorithm, true);
        writer.WriteBool(ClientThrottleEnabled);
        writer.WriteUInt8(ClientThrottleThreshold);
        writer.WriteF32(ClientThrottleScalar, true);
    }
}
