// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to client when remote firing an NPC dialogue window for a client
/// </summary>
public sealed class NpcDialoguePacket : Packet {
    public const int PacketId = 169;

    public ulong NpcIdRawId;
    public NpcDialogueActionType NpcDialogueActionType;
    public string Dialogue = string.Empty;
    public string SceneName = string.Empty;
    public string NpcName = string.Empty;
    public string ActionJSON = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        NpcIdRawId = reader.ReadUInt64(true);
        NpcDialogueActionType = (global::BedrockProtocol.Enums.NpcDialogueActionType)reader.ReadZigZag();
        Dialogue = reader.ReadVarString();
        SceneName = reader.ReadVarString();
        NpcName = reader.ReadVarString();
        ActionJSON = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt64(NpcIdRawId, true);
        writer.WriteZigZag((int)NpcDialogueActionType);
        writer.WriteVarString(Dialogue);
        writer.WriteVarString(SceneName);
        writer.WriteVarString(NpcName);
        writer.WriteVarString(ActionJSON);
    }
}
