// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used for a number of interactions with the NPC Component
/// </summary>
public sealed class NpcRequestPacket : Packet {
    public const int PacketId = 98;

    public ActorRuntimeID NPCRuntimeID = new();
    public NpcRequestPacketPayloadRequestType RequestType;
    public string Actions = string.Empty;
    public byte ActionIndex;
    public string SceneName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        NPCRuntimeID.Read(reader);
        RequestType = (global::BedrockProtocol.Enums.NpcRequestPacketPayloadRequestType)reader.ReadUInt8();
        Actions = reader.ReadVarString();
        ActionIndex = reader.ReadUInt8();
        SceneName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        NPCRuntimeID.Write(writer);
        writer.WriteUInt8((byte)RequestType);
        writer.WriteVarString(Actions);
        writer.WriteUInt8(ActionIndex);
        writer.WriteVarString(SceneName);
    }
}
