// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// On-Screen Texture Animation
/// </summary>
public sealed class OnScreenTextureAnimationPacket : Packet {
    public const int PacketId = 130;

    public uint EffectId;

    public override void Deserialize(BinaryReader reader) {
        EffectId = reader.ReadUInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt32(EffectId, true);
    }
}
