// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is sent when the client detects a malformed packet
/// </summary>
public sealed class PacketViolationWarningPacket : Packet {
    public const int PacketId = 156;

    public PacketViolationType ViolationType;
    public PacketViolationSeverity ViolationSeverity;
    public int ViolationPacketId;
    public string ViolationContext = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        ViolationType = (global::BedrockProtocol.Enums.PacketViolationType)reader.ReadZigZag();
        ViolationSeverity = (global::BedrockProtocol.Enums.PacketViolationSeverity)reader.ReadZigZag();
        ViolationPacketId = reader.ReadZigZag();
        ViolationContext = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)ViolationType);
        writer.WriteZigZag((int)ViolationSeverity);
        writer.WriteZigZag(ViolationPacketId);
        writer.WriteVarString(ViolationContext);
    }
}
