// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent by the client to the server with a party destination cookie response.
/// </summary>
public sealed class PartyDestinationCookieResponsePacket : Packet {
    public const int PacketId = 350;

    public string Cookie = string.Empty;
    public bool Accepted;

    public override void Deserialize(BinaryReader reader) {
        Cookie = reader.ReadVarString();
        Accepted = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(Cookie);
        writer.WriteBool(Accepted);
    }
}
