// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// There is a camera item in EDU and they can use it to take screenshots and add them to a scrapbook.
/// </summary>
public sealed class PhotoTransferPacket : Packet {
    public const int PacketId = 99;

    public string PhotoName = string.Empty;
    public string PhotoData = string.Empty;
    public string BookID = string.Empty;
    public PhotoType Type;
    public PhotoType SourceType;
    public long OwnerID;
    public string NewPhotoName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        PhotoName = reader.ReadVarString();
        PhotoData = reader.ReadVarString();
        BookID = reader.ReadVarString();
        Type = (global::BedrockProtocol.Enums.PhotoType)reader.ReadUInt8();
        SourceType = (global::BedrockProtocol.Enums.PhotoType)reader.ReadUInt8();
        OwnerID = reader.ReadInt64(true);
        NewPhotoName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(PhotoName);
        writer.WriteVarString(PhotoData);
        writer.WriteVarString(BookID);
        writer.WriteUInt8((byte)Type);
        writer.WriteUInt8((byte)SourceType);
        writer.WriteInt64(OwnerID, true);
        writer.WriteVarString(NewPhotoName);
    }
}
