// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends the of new Enchanting options  from the server when a player right clicks the enchantment table.
/// </summary>
public sealed class PlayerEnchantOptionsPacket : Packet {
    public const int PacketId = 146;

    public List<ItemEnchantOption> Options = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Options = new List<ItemEnchantOption>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ItemEnchantOption item0 = default!;
            ItemEnchantOption readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            Options.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Options.Count));
        foreach (var item1 in Options) {
            item1.Write(writer);
        }
    }
}
