// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// PlayerToggleCrafterSlotRequestPacket
/// </summary>
public sealed class PlayerToggleCrafterSlotRequestPacket : Packet {
    public const int PacketId = 306;

    public int PosX;
    public int PosY;
    public int PosZ;
    public byte SlotIndex;
    public bool IsDisabled;

    public override void Deserialize(BinaryReader reader) {
        PosX = reader.ReadInt32(true);
        PosY = reader.ReadInt32(true);
        PosZ = reader.ReadInt32(true);
        SlotIndex = reader.ReadUInt8();
        IsDisabled = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt32(PosX, true);
        writer.WriteInt32(PosY, true);
        writer.WriteInt32(PosZ, true);
        writer.WriteUInt8(SlotIndex);
        writer.WriteBool(IsDisabled);
    }
}
