// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Player List
/// </summary>
public sealed class PlayerListPacket : Packet {
    public const int PacketId = 63;

    public List<PlayerListEntryVariant> Entries = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Entries = new List<PlayerListEntryVariant>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            PlayerListEntryVariant item0 = default!;
            uint variant1000 = reader.ReadVarUInt();
            switch (variant1000) {
                case 0:
                    PlayerListRemoveEntry readValue4000 = new();
                    readValue4000.Read(reader);
                    item0 = readValue4000;
                    break;
                case 1:
                    PlayerListAddEntry readValue4001 = new();
                    readValue4001.Read(reader);
                    item0 = readValue4001;
                    break;
                default:
                    throw new FormatException($"Unknown union variant {variant1000} for item0.");
            }
            Entries.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Entries.Count));
        foreach (var item1 in Entries) {
            switch (item1) {
                case PlayerListRemoveEntry variantValue0:
                    writer.WriteVarUInt(0);
                    variantValue0.Write(writer);
                    break;
                case PlayerListAddEntry variantValue1:
                    writer.WriteVarUInt(1);
                    variantValue1.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for item1.");
            }
        }
    }
}
