// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Updates the client with the position of a player outside simulation distance, or hides a player.
/// </summary>
public sealed class PlayerLocationPacket : Packet {
    public const int PacketId = 326;

    public ActorUniqueID TargetActorID = new();
    public PlayerLocationVariant Location = null!;

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
        uint variant2 = reader.ReadVarUInt();
        switch (variant2) {
            case 0:
                CoordinatesLocation readValue3002 = new();
                readValue3002.Read(reader);
                Location = readValue3002;
                break;
            case 1:
                HiddenLocation readValue3003 = new();
                readValue3003.Read(reader);
                Location = readValue3003;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant2} for Location.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
        switch (Location) {
            case CoordinatesLocation variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case HiddenLocation variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Location.");
        }
    }
}
