// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Player Auth Input
/// </summary>
public sealed class PlayerAuthInputPacket : Packet {
    public const int PacketId = 144;

    public Vec2 PlayerRotation = new();
    public Vec3 Position = new();
    public Vec2 MoveVector = new();
    public float PlayerHeadRotation;
    public List<PlayerAuthInputData>? InputData;
    public InputMode InputMode;
    public ClientPlayMode PlayMode;
    public NewInteractionModel NewInteractionModel;
    public Vec2 InteractRotation = new();
    public PlayerInputTick ClientTick = new();
    public Vec3 PosDelta = new();
    public PackedItemUseLegacyInventoryTransaction? ItemUseTransaction;
    public ItemStackRequest? ItemStackRequest;
    public List<PlayerBlockActionData>? PlayerBlockActions;
    public Vec2? VehicleRotation;
    public ActorUniqueID? ClientPredictedVehicle;
    public Vec2 AnalogMoveVector = new();
    public Vec3 CameraOrientation = new();
    public Vec2 RawMoveVector = new();

    public override void Deserialize(BinaryReader reader) {
        PlayerRotation.Read(reader);
        Position.Read(reader);
        MoveVector.Read(reader);
        PlayerHeadRotation = reader.ReadF32(true);
        if (reader.ReadBool()) {
            int count8 = checked((int)reader.ReadVarUInt());
            InputData = new List<PlayerAuthInputData>(count8);
            for (int i8 = 0; i8 < count8; i8++) {
                PlayerAuthInputData item8 = default!;
                item8 = (global::BedrockProtocol.Enums.PlayerAuthInputData)reader.ReadZigZag();
                InputData.Add(item8);
            }
        } else {
            InputData = default;
        }
        InputMode = (global::BedrockProtocol.Enums.InputMode)reader.ReadVarUInt();
        PlayMode = (global::BedrockProtocol.Enums.ClientPlayMode)reader.ReadVarUInt();
        NewInteractionModel = (global::BedrockProtocol.Enums.NewInteractionModel)reader.ReadZigZag();
        InteractRotation.Read(reader);
        ClientTick.Read(reader);
        PosDelta.Read(reader);
        if (reader.ReadBool()) {
            if (reader.ReadBool()) {
                PackedItemUseLegacyInventoryTransaction readValue22 = new();
                readValue22.Read(reader);
                ItemUseTransaction = readValue22;
            } else {
                ItemUseTransaction = default;
            }
        } else {
            ItemUseTransaction = default;
        }
        if (reader.ReadBool()) {
            if (reader.ReadBool()) {
                ItemStackRequest readValue24 = new();
                readValue24.Read(reader);
                ItemStackRequest = readValue24;
            } else {
                ItemStackRequest = default;
            }
        } else {
            ItemStackRequest = default;
        }
        if (reader.ReadBool()) {
            if (reader.ReadBool()) {
                int count26 = checked((int)reader.ReadVarUInt());
                PlayerBlockActions = new List<PlayerBlockActionData>(count26);
                for (int i26 = 0; i26 < count26; i26++) {
                    PlayerBlockActionData item26 = default!;
                    PlayerBlockActionData readValue1026 = new();
                    readValue1026.Read(reader);
                    item26 = readValue1026;
                    PlayerBlockActions.Add(item26);
                }
            } else {
                PlayerBlockActions = default;
            }
        } else {
            PlayerBlockActions = default;
        }
        if (reader.ReadBool()) {
            if (reader.ReadBool()) {
                Vec2 readValue28 = new();
                readValue28.Read(reader);
                VehicleRotation = readValue28;
            } else {
                VehicleRotation = default;
            }
        } else {
            VehicleRotation = default;
        }
        if (reader.ReadBool()) {
            if (reader.ReadBool()) {
                ActorUniqueID readValue30 = new();
                readValue30.Read(reader);
                ClientPredictedVehicle = readValue30;
            } else {
                ClientPredictedVehicle = default;
            }
        } else {
            ClientPredictedVehicle = default;
        }
        AnalogMoveVector.Read(reader);
        CameraOrientation.Read(reader);
        RawMoveVector.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        PlayerRotation.Write(writer);
        Position.Write(writer);
        MoveVector.Write(writer);
        writer.WriteF32(PlayerHeadRotation, true);
        writer.WriteBool(InputData is not null);
        if (InputData is { } optionalValue9) {
            writer.WriteVarUInt(checked((uint)optionalValue9.Count));
            foreach (var item9 in optionalValue9) {
                writer.WriteZigZag((int)item9);
            }
        }
        writer.WriteVarUInt((uint)InputMode);
        writer.WriteVarUInt((uint)PlayMode);
        writer.WriteZigZag((int)NewInteractionModel);
        InteractRotation.Write(writer);
        ClientTick.Write(writer);
        PosDelta.Write(writer);
        writer.WriteBool(ItemUseTransaction is not null);
        if (ItemUseTransaction is not null) {
            writer.WriteBool(ItemUseTransaction is not null);
            if (ItemUseTransaction is { } optionalValue23) {
                optionalValue23.Write(writer);
            }
        }
        writer.WriteBool(ItemStackRequest is not null);
        if (ItemStackRequest is not null) {
            writer.WriteBool(ItemStackRequest is not null);
            if (ItemStackRequest is { } optionalValue25) {
                optionalValue25.Write(writer);
            }
        }
        writer.WriteBool(PlayerBlockActions is not null);
        if (PlayerBlockActions is not null) {
            writer.WriteBool(PlayerBlockActions is not null);
            if (PlayerBlockActions is { } optionalValue27) {
                writer.WriteVarUInt(checked((uint)optionalValue27.Count));
                foreach (var item27 in optionalValue27) {
                    item27.Write(writer);
                }
            }
        }
        writer.WriteBool(VehicleRotation is not null);
        if (VehicleRotation is not null) {
            writer.WriteBool(VehicleRotation is not null);
            if (VehicleRotation is { } optionalValue29) {
                optionalValue29.Write(writer);
            }
        }
        writer.WriteBool(ClientPredictedVehicle is not null);
        if (ClientPredictedVehicle is not null) {
            writer.WriteBool(ClientPredictedVehicle is not null);
            if (ClientPredictedVehicle is { } optionalValue31) {
                optionalValue31.Write(writer);
            }
        }
        AnalogMoveVector.Write(writer);
        CameraOrientation.Write(writer);
        RawMoveVector.Write(writer);
    }
}
