// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Player Update Entity Overrides
/// </summary>
public sealed class PlayerUpdateEntityOverridesPacket : Packet {
    public const int PacketId = 325;

    public ActorUniqueID TargetID = new();
    public uint PropertyIndex;
    public PlayerUpdateEntityOverridesUpdateVariant Update = null!;

    public override void Deserialize(BinaryReader reader) {
        TargetID.Read(reader);
        PropertyIndex = reader.ReadVarUInt();
        UpdateType variant4 = (global::BedrockProtocol.Enums.UpdateType)reader.ReadUInt8();
        switch (variant4) {
            case global::BedrockProtocol.Enums.UpdateType.ClearOverrides: {
                ClearOverride variantValue4_0 = new();
                Update = variantValue4_0;
                break;
            }
            case global::BedrockProtocol.Enums.UpdateType.RemoveOverride: {
                RemoveOverride variantValue4_1 = new();
                Update = variantValue4_1;
                break;
            }
            case global::BedrockProtocol.Enums.UpdateType.SetIntOverride: {
                IntOverride variantValue4_2 = new();
                variantValue4_2.Value = reader.ReadInt32(true);
                Update = variantValue4_2;
                break;
            }
            case global::BedrockProtocol.Enums.UpdateType.SetFloatOverride: {
                FloatOverride variantValue4_3 = new();
                variantValue4_3.Value = reader.ReadF32(true);
                Update = variantValue4_3;
                break;
            }
            default:
                throw new FormatException($"Unknown union variant {variant4} for Update.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        TargetID.Write(writer);
        writer.WriteVarUInt(PropertyIndex);
        switch (Update) {
            case ClearOverride variantValue0:
                variantValue0.Write(writer);
                break;
            case RemoveOverride variantValue1:
                variantValue1.Write(writer);
                break;
            case IntOverride variantValue2:
                variantValue2.Write(writer);
                break;
            case FloatOverride variantValue3:
                variantValue3.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Update.");
        }
    }
}
