// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server when the player uses pick block on actors or blocks, in addition to the player uses the clear, give, or replace item command or if the serverplayer uses _sendAdditionalLevelData().
/// </summary>
public sealed class PlayerHotbarPacket : Packet {
    public const int PacketId = 48;

    public uint SelectedSlot;
    public byte ContainerID;
    public bool ShouldSelectSlot;

    public override void Deserialize(BinaryReader reader) {
        SelectedSlot = reader.ReadVarUInt();
        ContainerID = reader.ReadUInt8();
        ShouldSelectSlot = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(SelectedSlot);
        writer.WriteUInt8((byte)ContainerID);
        writer.WriteBool(ShouldSelectSlot);
    }
}
