// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This packet is only used via command or script event. This is for 3rd party content.
/// </summary>
public sealed class PlaySoundPacket : Packet {
    public const int PacketId = 86;

    public string Name = string.Empty;
    public BlockPos Position = new();
    public float Volume;
    public float Pitch;
    public int LoopCount;
    public ServerSoundHandle? ServerSoundHandle;

    public override void Deserialize(BinaryReader reader) {
        Name = reader.ReadVarString();
        Position.Read(reader);
        Volume = reader.ReadF32(true);
        Pitch = reader.ReadF32(true);
        LoopCount = reader.ReadZigZag();
        if (reader.ReadBool()) {
            ServerSoundHandle readValue10 = new();
            readValue10.Read(reader);
            ServerSoundHandle = readValue10;
        } else {
            ServerSoundHandle = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(Name);
        Position.Write(writer);
        writer.WriteF32(Volume, true);
        writer.WriteF32(Pitch, true);
        writer.WriteZigZag(LoopCount);
        writer.WriteBool(ServerSoundHandle is not null);
        if (ServerSoundHandle is { } optionalValue11) {
            optionalValue11.Write(writer);
        }
    }
}
