// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Player Fog Packet
/// </summary>
public sealed class PlayerFogPacket : Packet {
    public const int PacketId = 160;

    public List<string> FogStack = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        FogStack = new List<string>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            string item0 = default!;
            item0 = reader.ReadVarString();
            FogStack.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)FogStack.Count));
        foreach (var item1 in FogStack) {
            writer.WriteVarString(item1);
        }
    }
}
