// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from server whenever the player's armor takes damage.
/// </summary>
public sealed class PlayerArmorDamagePacket : Packet {
    public const int PacketId = 149;

    public List<ArmorSlotAndDamagePair> ArmorSlotAndDamagePairs = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ArmorSlotAndDamagePairs = new List<ArmorSlotAndDamagePair>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            ArmorSlotAndDamagePair item0 = default!;
            ArmorSlotAndDamagePair readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            ArmorSlotAndDamagePairs.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ArmorSlotAndDamagePairs.Count));
        foreach (var item1 in ArmorSlotAndDamagePairs) {
            item1.Write(writer);
        }
    }
}
