// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Player Start Item Cooldown
/// </summary>
public sealed class PlayerStartItemCooldownPacket : Packet {
    public const int PacketId = 176;

    public string ItemCategory = string.Empty;
    public int DurationTicks;

    public override void Deserialize(BinaryReader reader) {
        ItemCategory = reader.ReadVarString();
        DurationTicks = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ItemCategory);
        writer.WriteZigZag(DurationTicks);
    }
}
