// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Describes the login status of the player
/// </summary>
public sealed class PlayStatusPacket : Packet {
    public const int PacketId = 2;

    public PlayStatus Status;

    public override void Deserialize(BinaryReader reader) {
        Status = (global::BedrockProtocol.Enums.PlayStatus)reader.ReadInt32(false);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt32((int)Status, false);
    }
}
