// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used by a test command to start/stop video capture
/// </summary>
public sealed class PlayerVideoCapturePacket : Packet {
    public const int PacketId = 324;

    public PlayerVideoCaptureStartVideoCaptureVariant StartVideoCapture = null!;
    public PlayerVideoCaptureStopVideoCaptureVariant StopVideoCapture = null!;

    public override void Deserialize(BinaryReader reader) {
        uint variant0 = reader.ReadVarUInt();
        switch (variant0) {
            case 0:
                StartVideoCapture readValue3000 = new();
                readValue3000.Read(reader);
                StartVideoCapture = readValue3000;
                break;
            case 1:
                StopVideoCapture readValue3001 = new();
                readValue3001.Read(reader);
                StartVideoCapture = readValue3001;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant0} for StartVideoCapture.");
        }
        uint variant2 = reader.ReadVarUInt();
        switch (variant2) {
            case 0:
                StartVideoCapture readValue3002 = new();
                readValue3002.Read(reader);
                StopVideoCapture = readValue3002;
                break;
            case 1:
                StopVideoCapture readValue3003 = new();
                readValue3003.Read(reader);
                StopVideoCapture = readValue3003;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant2} for StopVideoCapture.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        switch (StartVideoCapture) {
            case StartVideoCapture variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case StopVideoCapture variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for StartVideoCapture.");
        }
        switch (StopVideoCapture) {
            case StartVideoCapture variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case StopVideoCapture variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for StopVideoCapture.");
        }
    }
}
