// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the client whenever the player performs an action (dashing, un-dashing, use an item, mine/hit, use a block, etc).
/// </summary>
public sealed class PlayerActionPacket : Packet {
    public const int PacketId = 36;

    public ActorRuntimeID PlayerRuntimeID = new();
    public PlayerActionType Action;
    public BlockPos BlockPosition = new();
    public BlockPos ResultPos = new();
    public int Face;

    public override void Deserialize(BinaryReader reader) {
        PlayerRuntimeID.Read(reader);
        Action = (global::BedrockProtocol.Enums.PlayerActionType)reader.ReadZigZag();
        BlockPosition.Read(reader);
        ResultPos.Read(reader);
        Face = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        PlayerRuntimeID.Write(writer);
        writer.WriteZigZag((int)Action);
        BlockPosition.Write(writer);
        ResultPos.Write(writer);
        writer.WriteZigZag(Face);
    }
}
