// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Server to client packet for server authoratative runtime database (with persistent LevelStorage backup) designed primarily to track lodestone stuff. See Position Tracking DB Notes.md in bedrock-docs.
/// </summary>
public sealed class PositionTrackingDBServerBroadcastPacket : Packet {
    public const int PacketId = 153;

    public PositionTrackingDBServerBroadcastPacketPayloadAction Action;
    public PositionTrackingId Id = new();
    public object PositionTrackingData = null!;

    public delegate object PositionTrackingDataReader(BinaryReader reader);
    public delegate void PositionTrackingDataWriter(BinaryWriter writer, object value);
    public PositionTrackingDataReader? ReadPositionTrackingData { get; set; }
    public PositionTrackingDataWriter? WritePositionTrackingData { get; set; }

    public override void Deserialize(BinaryReader reader) {
        Action = (PositionTrackingDBServerBroadcastPacketPayloadAction)reader.ReadUInt8();
        Id.Read(reader);
        PositionTrackingData = (ReadPositionTrackingData ?? throw new InvalidOperationException("PositionTrackingDBServerBroadcastPacket.ReadPositionTrackingData must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Action);
        Id.Write(writer);
        (WritePositionTrackingData ?? throw new InvalidOperationException("PositionTrackingDBServerBroadcastPacket.WritePositionTrackingData must be configured before serialization."))(writer, PositionTrackingData);
    }
}
