// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Position Tracking DB Client Request
/// </summary>
public sealed class PositionTrackingDBClientRequestPacket : Packet {
    public const int PacketId = 154;

    public PositionTrackingDBClientRequestPacketPayloadAction Action = new();
    public PositionTrackingId Id = new();

    public override void Deserialize(BinaryReader reader) {
        Action = (PositionTrackingDBClientRequestPacketPayloadAction)reader.ReadUInt8();
        Id.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)Action);
        Id.Write(writer);
    }
}
