// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Send primitive drawing shape info (from scripting) to the client for rendering
/// </summary>
public sealed class PrimitiveShapesPacket : Packet {
    public const int PacketId = 328;

    public List<PrimitiveShapeDataPayload> ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved = new List<PrimitiveShapeDataPayload>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            PrimitiveShapeDataPayload item0 = default!;
            PrimitiveShapeDataPayload readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved.Count));
        foreach (var item1 in ArrayOfPrimitiveShapesCanBeAMixOfNewUpdatedOrRemoved) {
            item1.Write(writer);
        }
    }
}
