// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sends a volume entity to be removed from server to client.
/// </summary>
public sealed class RemoveVolumeEntityPacket : Packet {
    public const int PacketId = 167;

    public EntityNetId EntityNetworkId = new();
    public DimensionType DimensionType = new();

    public override void Deserialize(BinaryReader reader) {
        EntityNetworkId.Read(reader);
        DimensionType.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        EntityNetworkId.Write(writer);
        DimensionType.Write(writer);
    }
}
