// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Occasionally, during the server player tick some time is taken to remove nearby actors from the world.
/// </summary>
public sealed class RemoveActorPacket : Packet {
    public const int PacketId = 14;

    public ActorUniqueID TargetActorID = new();

    public override void Deserialize(BinaryReader reader) {
        TargetActorID.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        TargetActorID.Write(writer);
    }
}
