// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Using the scoreboard command, users can remove objectives that are tracked on the scoreboard.
/// </summary>
public sealed class RemoveObjectivePacket : Packet {
    public const int PacketId = 106;

    public string ObjectiveName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        ObjectiveName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ObjectiveName);
    }
}
