// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from client to server. Used to request a new Permissions Levels.
/// </summary>
public sealed class RequestPermissionsPacket : Packet {
    public const int PacketId = 185;

    public long TargetPlayerIdSRawID;
    public int PlayerPermissionLevel;
    public ushort CustomPermissionFlags;

    public override void Deserialize(BinaryReader reader) {
        TargetPlayerIdSRawID = reader.ReadInt64(true);
        PlayerPermissionLevel = reader.ReadZigZag();
        CustomPermissionFlags = reader.ReadUInt16(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteInt64(TargetPlayerIdSRawID, true);
        writer.WriteZigZag((int)PlayerPermissionLevel);
        writer.WriteUInt16(CustomPermissionFlags, true);
    }
}
