// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from client to server. Used to request an ability change.
/// </summary>
public sealed class RequestAbilityPacket : Packet {
    public const int PacketId = 184;

    public int Ability;
    public RequestAbilityPacketPayloadType ValueType;
    public bool Bool;
    public float Float;

    public override void Deserialize(BinaryReader reader) {
        Ability = reader.ReadZigZag();
        ValueType = (RequestAbilityPacketPayloadType)reader.ReadUInt8();
        Bool = reader.ReadBool();
        Float = reader.ReadF32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(Ability);
        writer.WriteUInt8((byte)ValueType);
        writer.WriteBool(Bool);
        writer.WriteF32(Float, true);
    }
}
