// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The client can't just change the view radius without the server's approval, otherwise there could be holes on unrendered area.
/// </summary>
public sealed class RequestChunkRadiusPacket : Packet {
    public const int PacketId = 69;

    public int ChunkRadius;
    public byte MaxChunkRadius;

    public override void Deserialize(BinaryReader reader) {
        ChunkRadius = reader.ReadZigZag();
        MaxChunkRadius = reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(ChunkRadius);
        writer.WriteUInt8(MaxChunkRadius);
    }
}
