// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Resource Pack Client Response
/// </summary>
public sealed class ResourcePackClientResponsePacket : Packet {
    public const int PacketId = 8;

    public ResourcePackClientResponseVariant Response = null!;

    public override void Deserialize(BinaryReader reader) {
        ResourcePackResponse variant0 = (global::BedrockProtocol.Enums.ResourcePackResponse)reader.ReadInt8();
        Console.WriteLine($"ResourcePackClientResponse raw status: {(int)variant0}");
        switch (variant0) {
            case global::BedrockProtocol.Enums.ResourcePackResponse.Cancel: {
                ResourcePackClientResponseCancel variantValue0_0 = new();
                Response = variantValue0_0;
                break;
            }
            case global::BedrockProtocol.Enums.ResourcePackResponse.Downloading: {
                ResourcePackClientResponseDownloading variantValue0_1 = new();
                string responseTag0_1 = reader.ReadVarString();
                if (responseTag0_1 != "downloading") {
                    throw new FormatException($"Expected downloading, got {responseTag0_1}.");
                }
                int count4001 = checked((int)reader.ReadVarUInt());
                variantValue0_1.DownloadingPacks = new List<string>(count4001);
                for (int i4001 = 0; i4001 < count4001; i4001++) {
                    string item4001 = default!;
                    item4001 = reader.ReadVarString();
                    variantValue0_1.DownloadingPacks.Add(item4001);
                }
                if (variantValue0_1.DownloadingPacks.Count == 1 && variantValue0_1.DownloadingPacks[0] == "downloadingfinished") {
                    Response = new ResourcePackClientResponseDownloadingFinished();
                    break;
                }
                Response = variantValue0_1;
                break;
            }
            case global::BedrockProtocol.Enums.ResourcePackResponse.DownloadingFinished: {
                ResourcePackClientResponseDownloadingFinished variantValue0_2 = new();
                string responseTag0_2 = reader.ReadVarString();
                if (responseTag0_2 != "downloadingfinished") {
                    throw new FormatException($"Expected downloadingfinished, got {responseTag0_2}.");
                }
                Response = variantValue0_2;
                break;
            }
            case global::BedrockProtocol.Enums.ResourcePackResponse.ResourcePackStackFinished: {
                ResourcePackClientResponseResourcePackStackFinished variantValue0_3 = new();
                string responseTag0_3 = reader.ReadVarString();
                if (responseTag0_3 != "resourcepackstackfinished") {
                    throw new FormatException($"Expected resourcepackstackfinished, got {responseTag0_3}.");
                }
                Response = variantValue0_3;
                break;
            }
            default:
                throw new FormatException($"Unknown union variant {variant0} for Response.");
        }
    }

    public override void Serialize(BinaryWriter writer) {
        switch (Response) {
            case ResourcePackClientResponseCancel variantValue0:
                variantValue0.Write(writer);
                break;
            case ResourcePackClientResponseDownloading variantValue1:
                variantValue1.Write(writer);
                break;
            case ResourcePackClientResponseDownloadingFinished variantValue2:
                writer.WriteInt8((sbyte)global::BedrockProtocol.Enums.ResourcePackResponse.Downloading);
                writer.WriteVarString("downloadingfinished");
                break;
            case ResourcePackClientResponseResourcePackStackFinished variantValue3:
                writer.WriteInt8((sbyte)global::BedrockProtocol.Enums.ResourcePackResponse.DownloadingFinished);
                writer.WriteVarString("resourcepackstackfinished");
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Response.");
        }
    }
}
