// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Resource Pack Chunk Request
/// </summary>
public sealed class ResourcePackChunkRequestPacket : Packet {
    public const int PacketId = 84;

    public string ResourceName = string.Empty;
    public int Chunk;

    public override void Deserialize(BinaryReader reader) {
        ResourceName = reader.ReadVarString();
        Chunk = reader.ReadInt32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ResourceName);
        writer.WriteInt32(Chunk, true);
    }
}
