// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Resource Packs Info
/// </summary>
public sealed class ResourcePacksInfoPacket : Packet {
    public const int PacketId = 6;

    public bool ResourcePackRequired;
    public bool HasAddonPacks;
    public bool HasScripts;
    public bool ForceDisableVibrantVisuals;
    public PackIdVersion WorldTemplateIdAndVersion = new();
    public List<PackInfoData> ResourcePacks = [];

    public override void Deserialize(BinaryReader reader) {
        ResourcePackRequired = reader.ReadBool();
        HasAddonPacks = reader.ReadBool();
        HasScripts = reader.ReadBool();
        ForceDisableVibrantVisuals = reader.ReadBool();
        WorldTemplateIdAndVersion.Read(reader);
        int count10 = checked((int)reader.ReadVarUInt());
        ResourcePacks = new List<PackInfoData>(count10);
        for (int i10 = 0; i10 < count10; i10++) {
            PackInfoData item10 = default!;
            PackInfoData readValue1010 = new();
            readValue1010.Read(reader);
            item10 = readValue1010;
            ResourcePacks.Add(item10);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(ResourcePackRequired);
        writer.WriteBool(HasAddonPacks);
        writer.WriteBool(HasScripts);
        writer.WriteBool(ForceDisableVibrantVisuals);
        WorldTemplateIdAndVersion.Write(writer);
        writer.WriteVarUInt(checked((uint)ResourcePacks.Count));
        foreach (var item11 in ResourcePacks) {
            item11.Write(writer);
        }
    }
}
