// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Resource Pack Data Info
/// </summary>
public sealed class ResourcePackDataInfoPacket : Packet {
    public const int PacketId = 82;

    public string ResourceName = string.Empty;
    public uint ChunkSize;
    public uint NumberOfChunks;
    public ulong FileSize;
    public string FileHash = string.Empty;
    public bool IsPremiumPack;
    public byte PackType;

    public override void Deserialize(BinaryReader reader) {
        ResourceName = reader.ReadVarString();
        ChunkSize = reader.ReadUInt32(true);
        NumberOfChunks = reader.ReadUInt32(true);
        FileSize = reader.ReadUInt64(true);
        FileHash = reader.ReadVarString();
        IsPremiumPack = reader.ReadBool();
        PackType = reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ResourceName);
        writer.WriteUInt32(ChunkSize, true);
        writer.WriteUInt32(NumberOfChunks, true);
        writer.WriteUInt64(FileSize, true);
        writer.WriteVarString(FileHash);
        writer.WriteBool(IsPremiumPack);
        writer.WriteUInt8(PackType);
    }
}
