// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Resource Pack Chunk Data
/// </summary>
public sealed class ResourcePackChunkDataPacket : Packet {
    public const int PacketId = 83;

    public string ResourceName = string.Empty;
    public uint ChunkID;
    public ulong ByteOffset;
    public byte[] ChunkData = [];

    public override void Deserialize(BinaryReader reader) {
        ResourceName = reader.ReadVarString();
        ChunkID = reader.ReadUInt32(true);
        ByteOffset = reader.ReadUInt64(true);
        int binaryLength6 = checked((int)reader.ReadVarUInt());
        ChunkData = reader.ReadBytes(binaryLength6).ToArray();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ResourceName);
        writer.WriteUInt32(ChunkID, true);
        writer.WriteUInt64(ByteOffset, true);
        writer.WriteVarUInt(checked((uint)ChunkData.Length));
        writer.WriteBytes(ChunkData);
    }
}
