// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent as a handshake between the client and server to respawn the player.
/// </summary>
public sealed class RespawnPacket : Packet {
    public const int PacketId = 45;

    public Vec3 Position = new();
    public PlayerRespawnState State;
    public ActorRuntimeID PlayerRuntimeId = new();

    public override void Deserialize(BinaryReader reader) {
        Position.Read(reader);
        State = (global::BedrockProtocol.Enums.PlayerRespawnState)reader.ReadUInt8();
        PlayerRuntimeId.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        Position.Write(writer);
        writer.WriteUInt8((byte)State);
        PlayerRuntimeId.Write(writer);
    }
}
