// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to send custom messages between client and server.
/// </summary>
public sealed class ScriptMessagePacket : Packet {
    public const int PacketId = 177;

    public string MessageId = string.Empty;
    public string MessageValue = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        MessageId = reader.ReadVarString();
        MessageValue = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(MessageId);
        writer.WriteVarString(MessageValue);
    }
}
