// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent by the server to a client with a party destination cookie.
/// </summary>
public sealed class SendPartyDestinationCookiePacket : Packet {
    public const int PacketId = 349;

    public string Cookie = string.Empty;
    public PartyDestinationCookieIntent Intent;
    public string DestinationName = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        Cookie = reader.ReadVarString();
        Intent = (global::BedrockProtocol.Enums.PartyDestinationCookieIntent)reader.ReadInt8();
        DestinationName = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(Cookie);
        writer.WriteInt8((sbyte)Intent);
        writer.WriteVarString(DestinationName);
    }
}
