// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the client to the server IF ProfilerLite is enabled AND the creator toggle for additional client telemetry is enabled AND new telemetry data is ready (every 500 ms).
/// </summary>
public sealed class ServerboundDiagnosticsPacket : Packet {
    public const int PacketId = 315;

    public float AvgFps;
    public float AvgServerSimTickTimeMS;
    public float AvgClientSimTickTimeMS;
    public float AvgBeginFrameTimeMS;
    public float AvgInputTimeMS;
    public float AvgRenderTimeMS;
    public float AvgEndFrameTimeMS;
    public float AvgRemainderTimePercent;
    public float AvgUnaccountedTimePercent;
    public List<MemoryCategoryCounter> MemoryCategoryValues = [];
    public List<EntityDiagnosticTimingInfo> EntityDiagnostics = [];
    public List<SystemDiagnosticTimingInfo> SystemDiagnostics = [];
    public List<SystemCategory> SystemCategories = [];
    public List<WhiskerScopeDataSummary> WhiskerScopes = [];

    public override void Deserialize(BinaryReader reader) {
        AvgFps = reader.ReadF32(true);
        AvgServerSimTickTimeMS = reader.ReadF32(true);
        AvgClientSimTickTimeMS = reader.ReadF32(true);
        AvgBeginFrameTimeMS = reader.ReadF32(true);
        AvgInputTimeMS = reader.ReadF32(true);
        AvgRenderTimeMS = reader.ReadF32(true);
        AvgEndFrameTimeMS = reader.ReadF32(true);
        AvgRemainderTimePercent = reader.ReadF32(true);
        AvgUnaccountedTimePercent = reader.ReadF32(true);
        int count18 = checked((int)reader.ReadVarUInt());
        MemoryCategoryValues = new List<MemoryCategoryCounter>(count18);
        for (int i18 = 0; i18 < count18; i18++) {
            MemoryCategoryCounter item18 = default!;
            MemoryCategoryCounter readValue1018 = new();
            readValue1018.Read(reader);
            item18 = readValue1018;
            MemoryCategoryValues.Add(item18);
        }
        int count20 = checked((int)reader.ReadVarUInt());
        EntityDiagnostics = new List<EntityDiagnosticTimingInfo>(count20);
        for (int i20 = 0; i20 < count20; i20++) {
            EntityDiagnosticTimingInfo item20 = default!;
            EntityDiagnosticTimingInfo readValue1020 = new();
            readValue1020.Read(reader);
            item20 = readValue1020;
            EntityDiagnostics.Add(item20);
        }
        int count22 = checked((int)reader.ReadVarUInt());
        SystemDiagnostics = new List<SystemDiagnosticTimingInfo>(count22);
        for (int i22 = 0; i22 < count22; i22++) {
            SystemDiagnosticTimingInfo item22 = default!;
            SystemDiagnosticTimingInfo readValue1022 = new();
            readValue1022.Read(reader);
            item22 = readValue1022;
            SystemDiagnostics.Add(item22);
        }
        int count24 = checked((int)reader.ReadVarUInt());
        SystemCategories = new List<SystemCategory>(count24);
        for (int i24 = 0; i24 < count24; i24++) {
            SystemCategory item24 = default!;
            SystemCategory readValue1024 = new();
            readValue1024.Read(reader);
            item24 = readValue1024;
            SystemCategories.Add(item24);
        }
        int count26 = checked((int)reader.ReadVarUInt());
        WhiskerScopes = new List<WhiskerScopeDataSummary>(count26);
        for (int i26 = 0; i26 < count26; i26++) {
            WhiskerScopeDataSummary item26 = default!;
            WhiskerScopeDataSummary readValue1026 = new();
            readValue1026.Read(reader);
            item26 = readValue1026;
            WhiskerScopes.Add(item26);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteF32(AvgFps, true);
        writer.WriteF32(AvgServerSimTickTimeMS, true);
        writer.WriteF32(AvgClientSimTickTimeMS, true);
        writer.WriteF32(AvgBeginFrameTimeMS, true);
        writer.WriteF32(AvgInputTimeMS, true);
        writer.WriteF32(AvgRenderTimeMS, true);
        writer.WriteF32(AvgEndFrameTimeMS, true);
        writer.WriteF32(AvgRemainderTimePercent, true);
        writer.WriteF32(AvgUnaccountedTimePercent, true);
        writer.WriteVarUInt(checked((uint)MemoryCategoryValues.Count));
        foreach (var item19 in MemoryCategoryValues) {
            item19.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)EntityDiagnostics.Count));
        foreach (var item21 in EntityDiagnostics) {
            item21.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)SystemDiagnostics.Count));
        foreach (var item23 in SystemDiagnostics) {
            item23.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)SystemCategories.Count));
        foreach (var item25 in SystemCategories) {
            item25.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)WhiskerScopes.Count));
        foreach (var item27 in WhiskerScopes) {
            item27.Write(writer);
        }
    }
}
