// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Applies a single update to the server data store from the client.
/// </summary>
public sealed class ServerboundDataStorePacket : Packet {
    public const int PacketId = 332;

    public DataStoreUpdate Update = new();

    public override void Deserialize(BinaryReader reader) {
        Update.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        Update.Write(writer);
    }
}
