// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to send a player's server position to the respective client at the end of movement.
/// </summary>
public sealed class ServerPlayerPostMovePositionPacket : Packet {
    public const int PacketId = 16;

    public Vec3 Pos = new();

    public override void Deserialize(BinaryReader reader) {
        Pos.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        Pos.Write(writer);
    }
}
