// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the client to the server when players change Pack Settings (pack UI).
/// </summary>
public sealed class ServerboundPackSettingChangePacket : Packet {
    public const int PacketId = 329;

    public UUID PackId = new();
    public string PackSettingName = string.Empty;
    public ServerboundPackSettingChangePacketPayloadPackSettingValueValue PackSettingValue = null!;

    public override void Deserialize(BinaryReader reader) {
        PackId.Read(reader);
        PackSettingName = reader.ReadVarString();
        PackSettingValue.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        PackId.Write(writer);
        writer.WriteVarString(PackSettingName);
        PackSettingValue.Write(writer);
    }
}
