// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the client to the server when a data driven screen is closed.
/// </summary>
public sealed class ServerboundDataDrivenScreenClosedPacket : Packet {
    public const int PacketId = 343;

    public uint? FormId;
    public DataDrivenScreenClosedReason CloseReason;

    public override void Deserialize(BinaryReader reader) {
        if (reader.ReadBool()) {
            FormId = reader.ReadUInt32(true);
        } else {
            FormId = default;
        }
        CloseReason = (global::BedrockProtocol.Enums.DataDrivenScreenClosedReason)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(FormId is not null);
        if (FormId is { } optionalValue1) {
            writer.WriteUInt32(optionalValue1, true);
        }
        writer.WriteUInt8((byte)CloseReason);
    }
}
