// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the client to the server to message to the server about the state of the loading screen.
/// </summary>
public sealed class ServerboundLoadingScreenPacket : Packet {
    public const int PacketId = 312;

    public ServerboundLoadingScreenPacketType LoadingScreenPacketType;
    public uint? LoadingScreenId;

    public override void Deserialize(BinaryReader reader) {
        LoadingScreenPacketType = (global::BedrockProtocol.Enums.ServerboundLoadingScreenPacketType)reader.ReadZigZag();
        if (reader.ReadBool()) {
            LoadingScreenId = reader.ReadUInt32(true);
        } else {
            LoadingScreenId = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)LoadingScreenPacketType);
        writer.WriteBool(LoadingScreenId is not null);
        if (LoadingScreenId is { } optionalValue3) {
            writer.WriteUInt32(optionalValue3, true);
        }
    }
}
