// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to send performance and other valuable stats back to the client
/// </summary>
public sealed class ServerStatsPacket : Packet {
    public const int PacketId = 192;

    public float ServerTime;
    public float NetworkTime;

    public override void Deserialize(BinaryReader reader) {
        ServerTime = reader.ReadF32(true);
        NetworkTime = reader.ReadF32(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteF32(ServerTime, true);
        writer.WriteF32(NetworkTime, true);
    }
}
