// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used for the server to set the velocity of a client actor.
/// </summary>
public sealed class SetActorMotionPacket : Packet {
    public const int PacketId = 40;

    public ActorRuntimeID TargetRuntimeID = new();
    public Vec3 Motion = new();
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        Motion.Read(reader);
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        Motion.Write(writer);
        Tick.Write(writer);
    }
}
