// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent by both client and server, only received by LegacyClientHandler.
/// </summary>
public sealed class SetActorLinkPacket : Packet {
    public const int PacketId = 41;

    public ActorLink Link = new();

    public override void Deserialize(BinaryReader reader) {
        Link.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        Link.Write(writer);
    }
}
