// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BedrockProtocol.Nbt;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Regular Actor Data delta packets, sent from the level on tick, mob and actor during normal tick
/// </summary>
public sealed class SetActorDataPacket : Packet {
    public const int PacketId = 39;

    private static readonly TagOptions NetworkNbtOptions = new(Name: true, Type: true, VarInt: true);

    public ActorRuntimeID TargetRuntimeID = new();
    public SynchedActorDataList ActorData = new();
    public PropertySyncData SynchedProperties = new();
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        ActorData.Read(reader);
        SynchedProperties.Read(reader);
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        ActorData.Write(writer);
        SynchedProperties.Write(writer);
        Tick.Write(writer);
    }
}
