// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used by the world settings screen, cheats, EDU builds for teachers, and various other places to enable cheats/commands
/// </summary>
public sealed class SetCommandsEnabledPacket : Packet {
    public const int PacketId = 59;

    public bool CommandsEnabled;

    public override void Deserialize(BinaryReader reader) {
        CommandsEnabled = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(CommandsEnabled);
    }
}
