// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set Difficulty
/// </summary>
public sealed class SetDifficultyPacket : Packet {
    public const int PacketId = 60;

    public uint Difficulty;

    public override void Deserialize(BinaryReader reader) {
        Difficulty = reader.ReadVarUInt();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(Difficulty);
    }
}
