// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server for 3rd party content to display current objectives and status
/// </summary>
public sealed class SetDisplayObjectivePacket : Packet {
    public const int PacketId = 107;

    public string DisplaySlotName = string.Empty;
    public string ObjectiveName = string.Empty;
    public string ObjectiveDisplayName = string.Empty;
    public string CriteriaName = string.Empty;
    public int SortOrder;

    public override void Deserialize(BinaryReader reader) {
        DisplaySlotName = reader.ReadVarString();
        ObjectiveName = reader.ReadVarString();
        ObjectiveDisplayName = reader.ReadVarString();
        CriteriaName = reader.ReadVarString();
        SortOrder = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(DisplaySlotName);
        writer.WriteVarString(ObjectiveName);
        writer.WriteVarString(ObjectiveDisplayName);
        writer.WriteVarString(CriteriaName);
        writer.WriteZigZag(SortOrder);
    }
}
