// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Same as SetPlayerGameTypePacket &amp; UpdatePlayerGameTypePacket, the only difference is that this changes the default for all clients.
/// </summary>
public sealed class SetDefaultGameTypePacket : Packet {
    public const int PacketId = 105;

    public GameType DefaultGameType;

    public override void Deserialize(BinaryReader reader) {
        DefaultGameType = (global::BedrockProtocol.Enums.GameType)reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)DefaultGameType);
    }
}
