// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This packet is only used via the set hud command. This is for 3rd party content.
/// </summary>
public sealed class SetHudPacket : Packet {
    public const int PacketId = 308;

    public List<HudElement> HudElement = [];
    public HudVisibility HudVisible;

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        HudElement = new List<HudElement>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            HudElement item0 = default!;
            item0 = (global::BedrockProtocol.Enums.HudElement)reader.ReadZigZag();
            HudElement.Add(item0);
        }
        HudVisible = (global::BedrockProtocol.Enums.HudVisibility)reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)HudElement.Count));
        foreach (var item1 in HudElement) {
            writer.WriteZigZag((int)item1);
        }
        writer.WriteZigZag((int)HudVisible);
    }
}
