// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This packet is sent to the client when the player is spawned in and when they respawn.
/// </summary>
public sealed class SetHealthPacket : Packet {
    public const int PacketId = 42;

    public int Health;

    public override void Deserialize(BinaryReader reader) {
        Health = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(Health);
    }
}
