// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Any time a player is hit, the id of the last mob that attacked them is sent to the client
/// </summary>
public sealed class SetLastHurtByPacket : Packet {
    public const int PacketId = 96;

    public ActorType LastHurtBy;

    public override void Deserialize(BinaryReader reader) {
        LastHurtBy = (global::BedrockProtocol.Enums.ActorType)reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)LastHurtBy);
    }
}
