// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set Local Player As Initialized
/// </summary>
public sealed class SetLocalPlayerAsInitializedPacket : Packet {
    public const int PacketId = 113;

    public ActorRuntimeID PlayerID = new();

    public override void Deserialize(BinaryReader reader) {
        PlayerID.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        PlayerID.Write(writer);
    }
}
