// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// SetPlayerInventoryOptionsPacket
/// </summary>
public sealed class SetPlayerInventoryOptionsPacket : Packet {
    public const int PacketId = 307;

    public InventoryOptions InventoryOptions = new();

    public override void Deserialize(BinaryReader reader) {
        InventoryOptions.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        InventoryOptions.Write(writer);
    }
}
