// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set Scoreboard Identity
/// </summary>
public sealed class SetScoreboardIdentityPacket : Packet {
    public const int PacketId = 112;

    public ScoreboardIdentityPacketType ScoreboardIdentityPacketType;
    public List<ScoreboardIdentityPacketInfo> ScoreboardIdentityInfo = [];

    public override void Deserialize(BinaryReader reader) {
        ScoreboardIdentityPacketType = (global::BedrockProtocol.Enums.ScoreboardIdentityPacketType)reader.ReadUInt8();
        int count2 = checked((int)reader.ReadVarUInt());
        ScoreboardIdentityInfo = new List<ScoreboardIdentityPacketInfo>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            ScoreboardIdentityPacketInfo item2 = default!;
            ScoreboardIdentityPacketInfo readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            ScoreboardIdentityInfo.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)ScoreboardIdentityPacketType);
        writer.WriteVarUInt(checked((uint)ScoreboardIdentityInfo.Count));
        foreach (var item3 in ScoreboardIdentityInfo) {
            item3.Write(writer);
        }
    }
}
