// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set Score
/// </summary>
public sealed class SetScorePacket : Packet {
    public const int PacketId = 108;

    public List<SetScoreScoreInfoVariant> ScoreInfo = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ScoreInfo = new List<SetScoreScoreInfoVariant>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            SetScoreScoreInfoVariant item0 = default!;
            ScorePacketEntryAction variant1000 = (global::BedrockProtocol.Enums.ScorePacketEntryAction)reader.ReadUInt8();
            switch (variant1000) {
                case global::BedrockProtocol.Enums.ScorePacketEntryAction.Remove: {
                    RemoveScore variantValue1000_0 = new();
                    variantValue1000_0.ScoreboardId.Read(reader);
                    if (reader.ReadBool()) {
                        variantValue1000_0.ObjectiveName = reader.ReadVarString();
                    } else {
                        variantValue1000_0.ObjectiveName = default;
                    }
                    item0 = variantValue1000_0;
                    break;
                }
                case global::BedrockProtocol.Enums.ScorePacketEntryAction.ChangePlayer: {
                    ChangePlayerScore variantValue1000_1 = new();
                    variantValue1000_1.ScoreboardId.Read(reader);
                    variantValue1000_1.ObjectiveName = reader.ReadVarString();
                    variantValue1000_1.ScoreValue = reader.ReadInt32(true);
                    variantValue1000_1.PlayerUniqueId.Read(reader);
                    item0 = variantValue1000_1;
                    break;
                }
                case global::BedrockProtocol.Enums.ScorePacketEntryAction.ChangeEntity: {
                    ChangeEntityScore variantValue1000_2 = new();
                    variantValue1000_2.ScoreboardId.Read(reader);
                    variantValue1000_2.ObjectiveName = reader.ReadVarString();
                    variantValue1000_2.ScoreValue = reader.ReadInt32(true);
                    variantValue1000_2.ActorId.Read(reader);
                    item0 = variantValue1000_2;
                    break;
                }
                case global::BedrockProtocol.Enums.ScorePacketEntryAction.ChangeFakePlayer: {
                    ChangeFakePlayerScore variantValue1000_3 = new();
                    variantValue1000_3.ScoreboardId.Read(reader);
                    variantValue1000_3.ObjectiveName = reader.ReadVarString();
                    variantValue1000_3.ScoreValue = reader.ReadInt32(true);
                    variantValue1000_3.FakePlayerName = reader.ReadVarString();
                    item0 = variantValue1000_3;
                    break;
                }
                default:
                    throw new FormatException($"Unknown union variant {variant1000} for item0.");
            }
            ScoreInfo.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ScoreInfo.Count));
        foreach (var item1 in ScoreInfo) {
            switch (item1) {
                case RemoveScore variantValue0:
                    variantValue0.Write(writer);
                    break;
                case ChangePlayerScore variantValue1:
                    variantValue1.Write(writer);
                    break;
                case ChangeEntityScore variantValue2:
                    variantValue2.Write(writer);
                    break;
                case ChangeFakePlayerScore variantValue3:
                    variantValue3.Write(writer);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for item1.");
            }
        }
    }
}
