// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// When a player logs in or the SetWorldSpawnCommand is used this is sent from the server to the client. Does not change when using a bed, that is a separate packet (RespawnPacket)
/// </summary>
public sealed class SetSpawnPositionPacket : Packet {
    public const int PacketId = 43;

    public SpawnPositionType SpawnPositionType;
    public BlockPos BlockPosition = new();
    public DimensionType DimensionType = new();
    public BlockPos SpawnBlockPos = new();

    public override void Deserialize(BinaryReader reader) {
        SpawnPositionType = (global::BedrockProtocol.Enums.SpawnPositionType)reader.ReadZigZag();
        BlockPosition.Read(reader);
        DimensionType.Read(reader);
        SpawnBlockPos.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)SpawnPositionType);
        BlockPosition.Write(writer);
        DimensionType.Write(writer);
        SpawnBlockPos.Write(writer);
    }
}
