// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set Score
/// </summary>
public sealed class SetScorePacket : Packet {
    public const int PacketId = 108;

    public List<SetScoreScoreInfoVariant> ScoreInfo = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        ScoreInfo = new List<SetScoreScoreInfoVariant>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            SetScoreScoreInfoVariant item0 = default!;
            uint variant1000 = reader.ReadVarUInt();
            switch (variant1000) {
                case 0: {
                    RemoveScore variantValue1000_0 = new();
                    string variantName1000_0 = reader.ReadVarString();
                    if (variantName1000_0 != "remove") {
                        throw new FormatException($"Expected remove, got {variantName1000_0}.");
                    }
                    variantValue1000_0.ScoreboardId.Read(reader);
                    if (reader.ReadBool()) {
                        if (reader.ReadBool()) {
                            variantValue1000_0.ObjectiveName = reader.ReadVarString();
                        } else {
                            variantValue1000_0.ObjectiveName = default;
                        }
                    } else {
                        variantValue1000_0.ObjectiveName = default;
                    }
                    item0 = variantValue1000_0;
                    break;
                }
                case 1: {
                    ChangePlayerScore variantValue1000_1 = new();
                    string variantName1000_1 = reader.ReadVarString();
                    if (variantName1000_1 != "changeplayer") {
                        throw new FormatException($"Expected changeplayer, got {variantName1000_1}.");
                    }
                    variantValue1000_1.ScoreboardId.Read(reader);
                    variantValue1000_1.ObjectiveName = reader.ReadVarString();
                    variantValue1000_1.ScoreValue = reader.ReadInt32(true);
                    variantValue1000_1.PlayerUniqueId.Read(reader);
                    item0 = variantValue1000_1;
                    break;
                }
                case 2: {
                    ChangeEntityScore variantValue1000_2 = new();
                    string variantName1000_2 = reader.ReadVarString();
                    if (variantName1000_2 != "changeentity") {
                        throw new FormatException($"Expected changeentity, got {variantName1000_2}.");
                    }
                    variantValue1000_2.ScoreboardId.Read(reader);
                    variantValue1000_2.ObjectiveName = reader.ReadVarString();
                    variantValue1000_2.ScoreValue = reader.ReadInt32(true);
                    variantValue1000_2.ActorId.Read(reader);
                    item0 = variantValue1000_2;
                    break;
                }
                case 3: {
                    ChangeFakePlayerScore variantValue1000_3 = new();
                    string variantName1000_3 = reader.ReadVarString();
                    if (variantName1000_3 != "changefakeplayer") {
                        throw new FormatException($"Expected changefakeplayer, got {variantName1000_3}.");
                    }
                    variantValue1000_3.ScoreboardId.Read(reader);
                    variantValue1000_3.ObjectiveName = reader.ReadVarString();
                    variantValue1000_3.ScoreValue = reader.ReadInt32(true);
                    variantValue1000_3.FakePlayerName = reader.ReadVarString();
                    item0 = variantValue1000_3;
                    break;
                }
                default:
                    throw new FormatException($"Unknown union variant {variant1000} for item0.");
            }
            ScoreInfo.Add(item0);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)ScoreInfo.Count));
        foreach (var item1 in ScoreInfo) {
            switch (item1) {
                case RemoveScore variantValue0:
                    writer.WriteVarUInt(0u);
                    writer.WriteVarString("remove");
                    variantValue0.ScoreboardId.Write(writer);
                    writer.WriteBool(true);
                    writer.WriteBool(variantValue0.ObjectiveName is not null);
                    if (variantValue0.ObjectiveName is { } optionalValue4000) {
                        writer.WriteVarString(optionalValue4000);
                    }
                    break;
                case ChangePlayerScore variantValue1:
                    writer.WriteVarUInt(1u);
                    writer.WriteVarString("changeplayer");
                    variantValue1.ScoreboardId.Write(writer);
                    writer.WriteVarString(variantValue1.ObjectiveName);
                    writer.WriteInt32(variantValue1.ScoreValue, true);
                    variantValue1.PlayerUniqueId.Write(writer);
                    break;
                case ChangeEntityScore variantValue2:
                    writer.WriteVarUInt(2u);
                    writer.WriteVarString("changeentity");
                    variantValue2.ScoreboardId.Write(writer);
                    writer.WriteVarString(variantValue2.ObjectiveName);
                    writer.WriteInt32(variantValue2.ScoreValue, true);
                    variantValue2.ActorId.Write(writer);
                    break;
                case ChangeFakePlayerScore variantValue3:
                    writer.WriteVarUInt(3u);
                    writer.WriteVarString("changefakeplayer");
                    variantValue3.ScoreboardId.Write(writer);
                    writer.WriteVarString(variantValue3.ObjectiveName);
                    writer.WriteInt32(variantValue3.ScoreValue, true);
                    writer.WriteVarString(variantValue3.FakePlayerName);
                    break;
                default:
                    throw new InvalidOperationException("Unsupported union value for item1.");
            }
        }
    }
}
