// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Requests a setting to be changed through commands.
/// </summary>
public sealed class SettingsCommandPacket : Packet {
    public const int PacketId = 140;

    public string Command = string.Empty;
    public bool SuppressOutput;

    public override void Deserialize(BinaryReader reader) {
        Command = reader.ReadVarString();
        SuppressOutput = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(Command);
        writer.WriteBool(SuppressOutput);
    }
}
