// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used by 3rd party content for the purpose of showing ui banners
/// </summary>
public sealed class SetTitlePacket : Packet {
    public const int PacketId = 88;

    public SetTitlePacketTitleType TitleType;
    public string TitleText = string.Empty;
    public int FadeInTime;
    public int StayTime;
    public int FadeOutTime;
    public string Xuid = string.Empty;
    public string PlatformOnlineId = string.Empty;
    public string FilteredTitleMessage = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        TitleType = (global::BedrockProtocol.Enums.SetTitlePacketTitleType)reader.ReadZigZag();
        TitleText = reader.ReadVarString();
        FadeInTime = reader.ReadZigZag();
        StayTime = reader.ReadZigZag();
        FadeOutTime = reader.ReadZigZag();
        Xuid = reader.ReadVarString();
        PlatformOnlineId = reader.ReadVarString();
        FilteredTitleMessage = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)TitleType);
        writer.WriteVarString(TitleText);
        writer.WriteZigZag(FadeInTime);
        writer.WriteZigZag(StayTime);
        writer.WriteZigZag(FadeOutTime);
        writer.WriteVarString(Xuid);
        writer.WriteVarString(PlatformOnlineId);
        writer.WriteVarString(FilteredTitleMessage);
    }
}
