// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Set Time
/// </summary>
public sealed class SetTimePacket : Packet {
    public const int PacketId = 10;

    public int Time;

    public override void Deserialize(BinaryReader reader) {
        Time = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag(Time);
    }
}
