// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Starts on server when the credits screen should pop up.
/// </summary>
public sealed class ShowCreditsPacket : Packet {
    public const int PacketId = 75;

    public ActorRuntimeID PlayerRuntimeID = new();
    public int CreditsState;

    public override void Deserialize(BinaryReader reader) {
        PlayerRuntimeID.Read(reader);
        CreditsState = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        PlayerRuntimeID.Write(writer);
        writer.WriteZigZag(CreditsState);
    }
}
