// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used for redirecting a user to the right offer.
/// </summary>
public sealed class ShowStoreOfferPacket : Packet {
    public const int PacketId = 91;

    public UUID OfferId = new();
    public ShowStoreOfferRedirectType RedirectType;

    public override void Deserialize(BinaryReader reader) {
        OfferId.Read(reader);
        RedirectType = (global::BedrockProtocol.Enums.ShowStoreOfferRedirectType)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        OfferId.Write(writer);
        writer.WriteUInt8((byte)RedirectType);
    }
}
