// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This packet is used for enabling/disabling commands and for unlocking world template settings (both unlocking UI buttons on client and the actual setting on the server).
/// </summary>
public sealed class SimpleEventPacket : Packet {
    public const int PacketId = 64;

    public Subtype Type;

    public override void Deserialize(BinaryReader reader) {
        Type = (global::BedrockProtocol.Enums.Subtype)reader.ReadUInt16(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt16((ushort)Type, true);
    }
}
