// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to the client when setting the simulation type for toolbox mode. (Not yet suported)
/// </summary>
public sealed class SimulationTypePacket : Packet {
    public const int PacketId = 168;

    public SimulationType SimType;

    public override void Deserialize(BinaryReader reader) {
        SimType = (global::BedrockProtocol.Enums.SimulationType)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)SimType);
    }
}
