// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Spawn Experience Orb
/// </summary>
public sealed class SpawnExperienceOrbPacket : Packet {
    public const int PacketId = 66;

    public Vec3 Position = new();
    public int XPValue;

    public override void Deserialize(BinaryReader reader) {
        Position.Read(reader);
        XPValue = reader.ReadZigZag();
    }

    public override void Serialize(BinaryWriter writer) {
        Position.Write(writer);
        writer.WriteZigZag(XPValue);
    }
}
