// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Tell client to spawn a particle effect.
/// </summary>
public sealed class SpawnParticleEffectPacket : Packet {
    public const int PacketId = 118;

    public byte DimensionId;
    public ActorUniqueID ActorId = new();
    public Vec3 Position = new();
    public string EffectName = string.Empty;
    public string MolangVariables = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        DimensionId = reader.ReadUInt8();
        ActorId.Read(reader);
        Position.Read(reader);
        EffectName = reader.ReadVarString();
        MolangVariables = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(DimensionId);
        ActorId.Write(writer);
        Position.Write(writer);
        writer.WriteVarString(EffectName);
        writer.WriteVarString(MolangVariables);
    }
}
