// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BedrockProtocol.Nbt;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server to client when the game is starting (or client joins), gives ids and current tick.
/// </summary>
public sealed class StartGamePacket : Packet {
    public const int PacketId = 11;

    private static readonly TagOptions NetworkNbtOptions = new(Name: true, Type: true, VarInt: true);

    public ActorUniqueID EntityID = new();
    public ActorRuntimeID RuntimeID = new();
    public GameType GameType;
    public Vec3 Position = new();
    public Vec2 Rotation = new();
    public LevelSettings Settings = new();
    public string LevelID = string.Empty;
    public string LevelName = string.Empty;
    public string TemplateContentIdentity = string.Empty;
    public bool IsTrial;
    public SyncedPlayerMovementSettings MovementSettings = new();
    public ulong LevelCurrentTime;
    public int EnchantmentSeed;
    public List<ServerBlockProperty> BlockProperties = [];
    public string MultiplayerCorrelationId = string.Empty;
    public bool EnableItemStackNetManager;
    public string ServerVersion = string.Empty;
    public CompoundTag PlayerPropertyData = new();
    public ulong ServerBlockTypeRegistryChecksum;
    public UUID WorldTemplateID = new();
    public bool ServerEnabledClientSideGeneration;
    public bool BlockNetworkIdsAreHashes;
    public NetworkPermissions NetworkPermissions = new();
    public server_config? ServerConfigurationJoinInfo;
    public ServerTelemetryData ServerTelemetryData = new();

    public override void Deserialize(BinaryReader reader) {
        EntityID.Read(reader);
        RuntimeID.Read(reader);
        GameType = (global::BedrockProtocol.Enums.GameType)reader.ReadZigZag();
        Position.Read(reader);
        Rotation.Read(reader);
        Settings.Read(reader);
        LevelID = reader.ReadVarString();
        LevelName = reader.ReadVarString();
        TemplateContentIdentity = reader.ReadVarString();
        IsTrial = reader.ReadBool();
        MovementSettings.Read(reader);
        LevelCurrentTime = reader.ReadUInt64(true);
        EnchantmentSeed = reader.ReadZigZag();
        int count26 = checked((int)reader.ReadVarUInt());
        BlockProperties = new List<ServerBlockProperty>(count26);
        for (int i26 = 0; i26 < count26; i26++) {
            ServerBlockProperty item26 = default!;
            ServerBlockProperty readValue1026 = new();
            readValue1026.Read(reader);
            item26 = readValue1026;
            BlockProperties.Add(item26);
        }
        MultiplayerCorrelationId = reader.ReadVarString();
        EnableItemStackNetManager = reader.ReadBool();
        ServerVersion = reader.ReadVarString();
        PlayerPropertyData = NBT.ReadTag<CompoundTag>(reader, NetworkNbtOptions);
        ServerBlockTypeRegistryChecksum = reader.ReadUInt64(true);
        WorldTemplateID.Read(reader);
        ServerEnabledClientSideGeneration = reader.ReadBool();
        BlockNetworkIdsAreHashes = reader.ReadBool();
        NetworkPermissions.Read(reader);
        if (reader.ReadBool()) {
            server_config readValue46 = new();
            readValue46.Read(reader);
            ServerConfigurationJoinInfo = readValue46;
        } else {
            ServerConfigurationJoinInfo = default;
        }
        ServerTelemetryData.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        EntityID.Write(writer);
        RuntimeID.Write(writer);
        writer.WriteZigZag((int)GameType);
        Position.Write(writer);
        Rotation.Write(writer);
        Settings.Write(writer);
        writer.WriteVarString(LevelID);
        writer.WriteVarString(LevelName);
        writer.WriteVarString(TemplateContentIdentity);
        writer.WriteBool(IsTrial);
        MovementSettings.Write(writer);
        writer.WriteUInt64(LevelCurrentTime, true);
        writer.WriteZigZag(EnchantmentSeed);
        writer.WriteVarUInt(checked((uint)BlockProperties.Count));
        foreach (var item27 in BlockProperties) {
            item27.Write(writer);
        }
        writer.WriteVarString(MultiplayerCorrelationId);
        writer.WriteBool(EnableItemStackNetManager);
        writer.WriteVarString(ServerVersion);
        NBT.WriteTag(writer, PlayerPropertyData, NetworkNbtOptions);
        writer.WriteUInt64(ServerBlockTypeRegistryChecksum, true);
        WorldTemplateID.Write(writer);
        writer.WriteBool(ServerEnabledClientSideGeneration);
        writer.WriteBool(BlockNetworkIdsAreHashes);
        NetworkPermissions.Write(writer);
        writer.WriteBool(ServerConfigurationJoinInfo is not null);
        if (ServerConfigurationJoinInfo is { } optionalValue47) {
            optionalValue47.Write(writer);
        }
        ServerTelemetryData.Write(writer);
    }
}
