// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Allows you to stop a sound or all sounds on all clients, only used in a /command
/// </summary>
public sealed class StopSoundPacket : Packet {
    public const int PacketId = 87;

    public string SoundName = string.Empty;
    public bool StopAllSounds;
    public bool StopMusicLegacy;

    public override void Deserialize(BinaryReader reader) {
        SoundName = reader.ReadVarString();
        StopAllSounds = reader.ReadBool();
        StopMusicLegacy = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(SoundName);
        writer.WriteBool(StopAllSounds);
        writer.WriteBool(StopMusicLegacy);
    }
}
