// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// After the client makes changes in the Structure Block Screen we tell the server to update based off of that. This only sent when you close the UI.
/// </summary>
public sealed class StructureBlockUpdatePacket : Packet {
    public const int PacketId = 90;

    public BlockPos BlockPosition = new();
    public StructureEditorData StructureData = new();
    public bool Trigger;
    public bool IsWaterlogged;

    public override void Deserialize(BinaryReader reader) {
        BlockPosition.Read(reader);
        StructureData.Read(reader);
        Trigger = reader.ReadBool();
        IsWaterlogged = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        BlockPosition.Write(writer);
        StructureData.Write(writer);
        writer.WriteBool(Trigger);
        writer.WriteBool(IsWaterlogged);
    }
}
