// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to request structure information from a server.
/// </summary>
public sealed class StructureTemplateDataRequestPacket : Packet {
    public const int PacketId = 132;

    public string StructureName = string.Empty;
    public BlockPos StructurePosition = new();
    public StructureSettings StructureSettings = new();
    public StructureTemplateRequestOperation RequestedOperation;

    public override void Deserialize(BinaryReader reader) {
        StructureName = reader.ReadVarString();
        StructurePosition.Read(reader);
        StructureSettings.Read(reader);
        RequestedOperation = (global::BedrockProtocol.Enums.StructureTemplateRequestOperation)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(StructureName);
        StructurePosition.Write(writer);
        StructureSettings.Write(writer);
        writer.WriteUInt8((byte)RequestedOperation);
    }
}
