// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used in exporting from load, exporting from save, and querying saved structures from structure blocks.
/// </summary>
public sealed class StructureTemplateDataResponsePacket : Packet {
    public const int PacketId = 133;

    public string StructureName = string.Empty;
    public object StructureSNBT = null!;
    public StructureTemplateResponseType ResponseType;

    public delegate object StructureSNBTReader(BinaryReader reader);
    public delegate void StructureSNBTWriter(BinaryWriter writer, object value);
    public StructureSNBTReader? ReadStructureSNBT { get; set; }
    public StructureSNBTWriter? WriteStructureSNBT { get; set; }

    public override void Deserialize(BinaryReader reader) {
        StructureName = reader.ReadVarString();
        StructureSNBT = (ReadStructureSNBT ?? throw new InvalidOperationException("StructureTemplateDataResponsePacket.ReadStructureSNBT must be configured before deserialization."))(reader);
        ResponseType = (global::BedrockProtocol.Enums.StructureTemplateResponseType)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(StructureName);
        (WriteStructureSNBT ?? throw new InvalidOperationException("StructureTemplateDataResponsePacket.WriteStructureSNBT must be configured before serialization."))(writer, StructureSNBT);
        writer.WriteUInt8((byte)ResponseType);
    }
}
