// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This packet starts the login process of subclients (splitscreen)
/// </summary>
public sealed class SubClientLoginPacket : Packet {
    public const int PacketId = 94;

    public string SubClientConnectionRequest = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        SubClientConnectionRequest = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(SubClientConnectionRequest);
    }
}
