// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from server to client representing a batch of subchunk data.
/// </summary>
public sealed class SubChunkPacket : Packet {
    public const int PacketId = 174;

    public bool CacheEnabled;
    public DimensionType DimensionType = new();
    public SubChunkPos CenterPos = new();
    public List<SubChunkPacketData> SubChunkData = [];

    public override void Deserialize(BinaryReader reader) {
        CacheEnabled = reader.ReadBool();
        DimensionType.Read(reader);
        CenterPos.Read(reader);
        int count6 = checked((int)reader.ReadVarUInt());
        SubChunkData = new List<SubChunkPacketData>(count6);
        for (int i6 = 0; i6 < count6; i6++) {
            SubChunkPacketData item6 = default!;
            SubChunkPacketData readValue1006 = new();
            readValue1006.Read(reader);
            item6 = readValue1006;
            SubChunkData.Add(item6);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(CacheEnabled);
        DimensionType.Write(writer);
        CenterPos.Write(writer);
        writer.WriteVarUInt(checked((uint)SubChunkData.Count));
        foreach (var item7 in SubChunkData) {
            item7.Write(writer);
        }
    }
}
