// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the client to the server representing a batch of subchunks that the client requests from the server
/// </summary>
public sealed class SubChunkRequestPacket : Packet {
    public const int PacketId = 175;

    public DimensionType DimensionType = new();
    public List<SubChunkPosOffset> SubChunkPositionOffsetList = [];
    public SubChunkPos CenterPos = new();

    public override void Deserialize(BinaryReader reader) {
        DimensionType.Read(reader);
        int count2 = checked((int)reader.ReadVarUInt());
        SubChunkPositionOffsetList = new List<SubChunkPosOffset>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            SubChunkPosOffset item2 = default!;
            SubChunkPosOffset readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            SubChunkPositionOffsetList.Add(item2);
        }
        CenterPos.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        DimensionType.Write(writer);
        writer.WriteVarUInt(checked((uint)SubChunkPositionOffsetList.Count));
        foreach (var item3 in SubChunkPositionOffsetList) {
            item3.Write(writer);
        }
        CenterPos.Write(writer);
    }
}
