// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Allows us to synchronize Actor properties across the network.
/// </summary>
public sealed class SyncActorPropertyPacket : Packet {
    public const int PacketId = 165;

    public object PropertyData = null!;

    public delegate object PropertyDataReader(BinaryReader reader);
    public delegate void PropertyDataWriter(BinaryWriter writer, object value);
    public PropertyDataReader? ReadPropertyData { get; set; }
    public PropertyDataWriter? WritePropertyData { get; set; }

    public override void Deserialize(BinaryReader reader) {
        PropertyData = (ReadPropertyData ?? throw new InvalidOperationException("SyncActorPropertyPacket.ReadPropertyData must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        (WritePropertyData ?? throw new InvalidOperationException("SyncActorPropertyPacket.WritePropertyData must be configured before serialization."))(writer, PropertyData);
    }
}
