// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// A packet sent to the server when deal with picking up an item off the ground in the world.
/// </summary>
public sealed class TakeItemActorPacket : Packet {
    public const int PacketId = 17;

    public ActorRuntimeID ItemRuntimeID = new();
    public ActorRuntimeID ActorRuntimeID = new();

    public override void Deserialize(BinaryReader reader) {
        ItemRuntimeID.Read(reader);
        ActorRuntimeID.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        ItemRuntimeID.Write(writer);
        ActorRuntimeID.Write(writer);
    }
}
