// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Represents a text message that needs to be displayed in-game
/// </summary>
public sealed class TextPacket : Packet {
    public const int PacketId = 9;

    public bool Localize;
    public TextBodyVariant Body = null!;
    public string SenderSXUID = string.Empty;
    public string PlatformId = string.Empty;
    public string? FilteredMessage;

    public override void Deserialize(BinaryReader reader) {
        Localize = reader.ReadBool();
        uint variant2 = reader.ReadVarUInt();
        switch (variant2) {
            case 0:
                MessageOnly readValue3002 = new();
                readValue3002.Read(reader);
                Body = readValue3002;
                break;
            case 1:
                AuthorAndMessage readValue3003 = new();
                readValue3003.Read(reader);
                Body = readValue3003;
                break;
            case 2:
                MessageAndParams readValue3004 = new();
                readValue3004.Read(reader);
                Body = readValue3004;
                break;
            default:
                throw new FormatException($"Unknown union variant {variant2} for Body.");
        }
        SenderSXUID = reader.ReadVarString();
        PlatformId = reader.ReadVarString();
        if (reader.ReadBool()) {
            FilteredMessage = reader.ReadVarString();
        } else {
            FilteredMessage = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(Localize);
        switch (Body) {
            case MessageOnly variantValue0:
                writer.WriteVarUInt(0);
                variantValue0.Write(writer);
                break;
            case AuthorAndMessage variantValue1:
                writer.WriteVarUInt(1);
                variantValue1.Write(writer);
                break;
            case MessageAndParams variantValue2:
                writer.WriteVarUInt(2);
                variantValue2.Write(writer);
                break;
            default:
                throw new InvalidOperationException("Unsupported union value for Body.");
        }
        writer.WriteVarString(SenderSXUID);
        writer.WriteVarString(PlatformId);
        writer.WriteBool(FilteredMessage is not null);
        if (FilteredMessage is { } optionalValue9) {
            writer.WriteVarString(optionalValue9);
        }
    }
}
