// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to inform the client that the server is waiting for ticking areas to finish preloading.
/// </summary>
public sealed class TickingAreasLoadStatusPacket : Packet {
    public const int PacketId = 179;

    public bool WaitingForPreload;

    public override void Deserialize(BinaryReader reader) {
        WaitingForPreload = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteBool(WaitingForPreload);
    }
}
