// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Pushes a UI toast message to be displayed by the client
/// </summary>
public sealed class ToastRequestPacket : Packet {
    public const int PacketId = 186;

    public string Title = string.Empty;
    public string Content = string.Empty;

    public override void Deserialize(BinaryReader reader) {
        Title = reader.ReadVarString();
        Content = reader.ReadVarString();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(Title);
        writer.WriteVarString(Content);
    }
}
