// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to kick off transferring the client between online games, or it can be used to cause players to quit the world and rejoin.
/// </summary>
public sealed class TransferPacket : Packet {
    public const int PacketId = 85;

    public string ServerAddress = string.Empty;
    public ushort ServerPort;
    public bool ReloadWorld;
    public gatheringsConfig? GatheringsConfiguration;

    public override void Deserialize(BinaryReader reader) {
        ServerAddress = reader.ReadVarString();
        ServerPort = reader.ReadUInt16(true);
        ReloadWorld = reader.ReadBool();
        if (reader.ReadBool()) {
            gatheringsConfig readValue6 = new();
            readValue6.Read(reader);
            GatheringsConfiguration = readValue6;
        } else {
            GatheringsConfiguration = default;
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(ServerAddress);
        writer.WriteUInt16(ServerPort, true);
        writer.WriteBool(ReloadWorld);
        writer.WriteBool(GatheringsConfiguration is not null);
        if (GatheringsConfiguration is { } optionalValue7) {
            optionalValue7.Write(writer);
        }
    }
}
