// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from the server on level startup to send all trim patterns to the client.
/// </summary>
public sealed class TrimDataPacket : Packet {
    public const int PacketId = 302;

    public List<TrimPattern> TrimPatternList = [];
    public List<TrimMaterial> TrimMaterialList = [];

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        TrimPatternList = new List<TrimPattern>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            TrimPattern item0 = default!;
            TrimPattern readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            TrimPatternList.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        TrimMaterialList = new List<TrimMaterial>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            TrimMaterial item2 = default!;
            TrimMaterial readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            TrimMaterialList.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)TrimPatternList.Count));
        foreach (var item1 in TrimPatternList) {
            item1.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)TrimMaterialList.Count));
        foreach (var item3 in TrimMaterialList) {
            item3.Write(writer);
        }
    }
}
