// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent from server to client, for all previously unlocked recipes on load and for any newly unlocked recipes during gameplay.
/// </summary>
public sealed class UnlockedRecipesPacket : Packet {
    public const int PacketId = 199;

    public PacketType PacketType;
    public List<string> UnlockedRecipesList = [];

    public override void Deserialize(BinaryReader reader) {
        PacketType = (global::BedrockProtocol.Enums.PacketType)reader.ReadUInt32(true);
        int count2 = checked((int)reader.ReadVarUInt());
        UnlockedRecipesList = new List<string>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            string item2 = default!;
            item2 = reader.ReadVarString();
            UnlockedRecipesList.Add(item2);
        }
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt32((uint)PacketType, true);
        writer.WriteVarUInt(checked((uint)UnlockedRecipesList.Count));
        foreach (var item3 in UnlockedRecipesList) {
            writer.WriteVarString(item3);
        }
    }
}
