// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// The server will send this back to all clients on receipt of the SetPlayerGameTypePacket so that cached game type and permissions flags in mLevel on all clients is kept up to date.
/// </summary>
public sealed class UpdatePlayerGameTypePacket : Packet {
    public const int PacketId = 151;

    public GameType PlayerGameType;
    public ActorUniqueID TargetPlayer = new();
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        PlayerGameType = (global::BedrockProtocol.Enums.GameType)reader.ReadZigZag();
        TargetPlayer.Read(reader);
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteZigZag((int)PlayerGameType);
        TargetPlayer.Write(writer);
        Tick.Write(writer);
    }
}
