// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used when the player trades with an npc. This sends all of the updated trade info in one big ol' packet.
/// </summary>
public sealed class UpdateTradePacket : Packet {
    public const int PacketId = 80;

    public byte ContainerId;
    public byte Type;
    public int Size;
    public int TraderTier;
    public ActorUniqueID EntityUniqueId = new();
    public ActorUniqueID LastTradingPlayer = new();
    public string DisplayName = string.Empty;
    public bool UseNewTradeScreen;
    public bool UsingEconomyTrade;
    public object Data = null!;

    public delegate object DataReader(BinaryReader reader);
    public delegate void DataWriter(BinaryWriter writer, object value);
    public DataReader? ReadData { get; set; }
    public DataWriter? WriteData { get; set; }

    public override void Deserialize(BinaryReader reader) {
        ContainerId = reader.ReadUInt8();
        Type = reader.ReadUInt8();
        Size = reader.ReadZigZag();
        TraderTier = reader.ReadZigZag();
        EntityUniqueId.Read(reader);
        LastTradingPlayer.Read(reader);
        DisplayName = reader.ReadVarString();
        UseNewTradeScreen = reader.ReadBool();
        UsingEconomyTrade = reader.ReadBool();
        Data = (ReadData ?? throw new InvalidOperationException("UpdateTradePacket.ReadData must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(ContainerId);
        writer.WriteUInt8(Type);
        writer.WriteZigZag(Size);
        writer.WriteZigZag(TraderTier);
        EntityUniqueId.Write(writer);
        LastTradingPlayer.Write(writer);
        writer.WriteVarString(DisplayName);
        writer.WriteBool(UseNewTradeScreen);
        writer.WriteBool(UsingEconomyTrade);
        (WriteData ?? throw new InvalidOperationException("UpdateTradePacket.WriteData must be configured before serialization."))(writer, Data);
    }
}
