// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// This is used for the scoreboard and tag systems (overwhelmingly used by 3rd party content)
/// </summary>
public sealed class UpdateSoftEnumPacket : Packet {
    public const int PacketId = 114;

    public string EnumName = string.Empty;
    public List<string> Values = [];
    public SoftEnumUpdateType UpdateType;

    public override void Deserialize(BinaryReader reader) {
        EnumName = reader.ReadVarString();
        int count2 = checked((int)reader.ReadVarUInt());
        Values = new List<string>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            string item2 = default!;
            item2 = reader.ReadVarString();
            Values.Add(item2);
        }
        UpdateType = (global::BedrockProtocol.Enums.SoftEnumUpdateType)reader.ReadUInt8();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarString(EnumName);
        writer.WriteVarUInt(checked((uint)Values.Count));
        foreach (var item3 in Values) {
            writer.WriteVarString(item3);
        }
        writer.WriteUInt8((byte)UpdateType);
    }
}
