// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// UpdateClientInputLocksPacket
/// </summary>
public sealed class UpdateClientInputLocksPacket : Packet {
    public const int PacketId = 196;

    public uint InputLockComponentData;

    public override void Deserialize(BinaryReader reader) {
        InputLockComponentData = reader.ReadVarUInt();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(InputLockComponentData);
    }
}
