// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Packet sent for every set of blocks changed in a sub chunk every tick.
/// </summary>
public sealed class UpdateSubChunkBlocksPacket : Packet {
    public const int PacketId = 172;

    public BlockPos SubChunkBlockPosition = new();
    public UpdateSubChunkBlocksChangedInfo BlocksChanged = new();

    public override void Deserialize(BinaryReader reader) {
        SubChunkBlockPosition.Read(reader);
        BlocksChanged.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        SubChunkBlockPosition.Write(writer);
        BlocksChanged.Write(writer);
    }
}
