// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Update Attributes
/// </summary>
public sealed class UpdateAttributesPacket : Packet {
    public const int PacketId = 29;

    public ActorRuntimeID TargetRuntimeID = new();
    public List<AttributeData> AttributeList = [];
    public PlayerInputTick Tick = new();

    public override void Deserialize(BinaryReader reader) {
        TargetRuntimeID.Read(reader);
        int count2 = checked((int)reader.ReadVarUInt());
        AttributeList = new List<AttributeData>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            AttributeData item2 = default!;
            AttributeData readValue1002 = new();
            readValue1002.Read(reader);
            item2 = readValue1002;
            AttributeList.Add(item2);
        }
        Tick.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        TargetRuntimeID.Write(writer);
        writer.WriteVarUInt(checked((uint)AttributeList.Count));
        foreach (var item3 in AttributeList) {
            item3.Write(writer);
        }
        Tick.Write(writer);
    }
}
