// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Used to sync moving blocks with clients so they render correctly
/// </summary>
public sealed class UpdateBlockSyncedPacket : Packet {
    public const int PacketId = 110;

    public BlockPos BlockPosition = new();
    public uint BlockRuntimeID;
    public uint Flags;
    public uint Layer;
    public ulong UniqueActorId;
    public ulong ActorSyncMessage;

    public override void Deserialize(BinaryReader reader) {
        BlockPosition.Read(reader);
        BlockRuntimeID = reader.ReadVarUInt();
        Flags = reader.ReadVarUInt();
        Layer = reader.ReadVarUInt();
        UniqueActorId = reader.ReadVarULong();
        ActorSyncMessage = reader.ReadVarULong();
    }

    public override void Serialize(BinaryWriter writer) {
        BlockPosition.Write(writer);
        writer.WriteVarUInt(BlockRuntimeID);
        writer.WriteVarUInt(Flags);
        writer.WriteVarUInt(Layer);
        writer.WriteVarULong(UniqueActorId);
        writer.WriteVarULong(ActorSyncMessage);
    }
}
