// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Seemingly only used for the Horse Inventory... More specifically when the player opens the horse inventory.
/// </summary>
public sealed class UpdateEquipPacket : Packet {
    public const int PacketId = 81;

    public byte ContainerId;
    public byte Type;
    public int Size;
    public ActorUniqueID EntityUniqueId = new();
    public object Data = null!;

    public delegate object DataReader(BinaryReader reader);
    public delegate void DataWriter(BinaryWriter writer, object value);
    public DataReader? ReadData { get; set; }
    public DataWriter? WriteData { get; set; }

    public override void Deserialize(BinaryReader reader) {
        ContainerId = reader.ReadUInt8();
        Type = reader.ReadUInt8();
        Size = reader.ReadZigZag();
        EntityUniqueId.Read(reader);
        Data = (ReadData ?? throw new InvalidOperationException("UpdateEquipPacket.ReadData must be configured before deserialization."))(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8(ContainerId);
        writer.WriteUInt8(Type);
        writer.WriteZigZag(Size);
        EntityUniqueId.Write(writer);
        (WriteData ?? throw new InvalidOperationException("UpdateEquipPacket.WriteData must be configured before serialization."))(writer, Data);
    }
}
