// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Occasional packets sent from server when blocks update or are ticked. (For example, when digging.)
/// </summary>
public sealed class UpdateBlockPacket : Packet {
    public const int PacketId = 21;

    public BlockPos BlockPosition = new();
    public uint BlockRuntimeID;
    public uint Flags;
    public uint Layer;

    public override void Deserialize(BinaryReader reader) {
        BlockPosition.Read(reader);
        BlockRuntimeID = reader.ReadVarUInt();
        Flags = reader.ReadVarUInt();
        Layer = reader.ReadVarUInt();
    }

    public override void Serialize(BinaryWriter writer) {
        BlockPosition.Write(writer);
        writer.WriteVarUInt(BlockRuntimeID);
        writer.WriteVarUInt(Flags);
        writer.WriteVarUInt(Layer);
    }
}
