// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using BedrockProtocol.Enums;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sent by the server to update the state of a player's Abilities.
/// </summary>
public sealed class UpdateAbilitiesPacket : Packet {
    public const int PacketId = 187;

    public SerializedAbilitiesData Data = new();

    public override void Deserialize(BinaryReader reader) {
        Data.Read(reader);
    }

    public override void Serialize(BinaryWriter writer) {
        Data.Write(writer);
    }
}
