// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using BedrockProtocol.Enums;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Sync the player's options (mostly settings) to the server.
/// </summary>
public sealed class UpdateClientOptionsPacket : Packet {
    public const int PacketId = 323;

    public GraphicsMode GraphicsModeChange;
    public bool FilterProfanityChange;

    public override void Deserialize(BinaryReader reader) {
        GraphicsModeChange = (global::BedrockProtocol.Enums.GraphicsMode)reader.ReadUInt8();
        FilterProfanityChange = reader.ReadBool();
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteUInt8((byte)GraphicsModeChange);
        writer.WriteBool(FilterProfanityChange);
    }
}
