// -----------------------------------------------------------------------------
// <auto-generated />
// Source: Mojang Bedrock Protocol Docs
//         https://github.com/Mojang/bedrock-protocol-docs
// Generator: AnyBananaGAME
//           https://github.com/AnyBananaGAME
// Generated for: BasaltBE
// This generated code is free for everyone to use.
// Do not edit this file manually.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using BedrockProtocol.Types;
using BinaryReader = Basalt.Binary.BinaryReader;
using BinaryWriter = Basalt.Binary.BinaryWriter;

namespace BedrockProtocol.Packets;

/// <summary>
/// Syncs client with server voxel shape data on world join. This packet contains a copy of all behavior pack voxel shapes data and is used by StartGamePacket.
/// </summary>
public sealed class VoxelShapesPacket : Packet {
    public const int PacketId = 337;

    public List<SerializableVoxelShape> Shapes = [];
    public Dictionary<string, RegistryHandle> NameMap = [];
    public ushort CustomShapeCount;

    public override void Deserialize(BinaryReader reader) {
        int count0 = checked((int)reader.ReadVarUInt());
        Shapes = new List<SerializableVoxelShape>(count0);
        for (int i0 = 0; i0 < count0; i0++) {
            SerializableVoxelShape item0 = default!;
            SerializableVoxelShape readValue1000 = new();
            readValue1000.Read(reader);
            item0 = readValue1000;
            Shapes.Add(item0);
        }
        int count2 = checked((int)reader.ReadVarUInt());
        NameMap = new Dictionary<string, RegistryHandle>(count2);
        for (int i2 = 0; i2 < count2; i2++) {
            string key2 = default!;
            key2 = reader.ReadVarString();
            RegistryHandle value2 = default!;
            RegistryHandle readValue2002 = new();
            readValue2002.Read(reader);
            value2 = readValue2002;
            NameMap.Add(key2, value2);
        }
        CustomShapeCount = reader.ReadUInt16(true);
    }

    public override void Serialize(BinaryWriter writer) {
        writer.WriteVarUInt(checked((uint)Shapes.Count));
        foreach (var item1 in Shapes) {
            item1.Write(writer);
        }
        writer.WriteVarUInt(checked((uint)NameMap.Count));
        foreach (var pair3 in NameMap) {
            writer.WriteVarString(pair3.Key);
            pair3.Value.Write(writer);
        }
        writer.WriteUInt16(CustomShapeCount, true);
    }
}
